/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AutocompleteAddtocartSchema,
  AutocompleteRedirectSchema,
  AutocompleteSchema,
  Model400Response,
  Model404Response,
} from '../models/index';
import {
    AutocompleteAddtocartSchemaFromJSON,
    AutocompleteAddtocartSchemaToJSON,
    AutocompleteRedirectSchemaFromJSON,
    AutocompleteRedirectSchemaToJSON,
    AutocompleteSchemaFromJSON,
    AutocompleteSchemaToJSON,
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
} from '../models/index';

export interface AutocompleteAddtocartRequest {
    siteId: string;
    autocompleteAddtocartSchema: AutocompleteAddtocartSchema;
}

export interface AutocompleteClickthroughRequest {
    siteId: string;
    autocompleteSchema: AutocompleteSchema;
}

export interface AutocompleteImpressionRequest {
    siteId: string;
    autocompleteSchema: AutocompleteSchema;
}

export interface AutocompleteRedirectRequest {
    siteId: string;
    autocompleteRedirectSchema: AutocompleteRedirectSchema;
}

export interface AutocompleteRenderRequest {
    siteId: string;
    autocompleteSchema: AutocompleteSchema;
}

/**
 * 
 */
export class AutocompleteApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/addtocart</i><br><br>Shopper adds a Searchspring autocomplete result to the cart via a `Quick Add to Cart` button in the Autocomplete Module. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async autocompleteAddtocartRaw(requestParameters: AutocompleteAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteAddtocart().'
            );
        }

        if (requestParameters['autocompleteAddtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'autocompleteAddtocartSchema',
                'Required parameter "autocompleteAddtocartSchema" was null or undefined when calling autocompleteAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/autocomplete/addtocart`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AutocompleteAddtocartSchemaToJSON(requestParameters['autocompleteAddtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/addtocart</i><br><br>Shopper adds a Searchspring autocomplete result to the cart via a `Quick Add to Cart` button in the Autocomplete Module. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async autocompleteAddtocart(requestParameters: AutocompleteAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.autocompleteAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/clickthrough</i><br><br>Shopper clicks on a Searchspring autocomplete search result rendered in the Autocomplete Module, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async autocompleteClickthroughRaw(requestParameters: AutocompleteClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteClickthrough().'
            );
        }

        if (requestParameters['autocompleteSchema'] == null) {
            throw new runtime.RequiredError(
                'autocompleteSchema',
                'Required parameter "autocompleteSchema" was null or undefined when calling autocompleteClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/autocomplete/clickthrough`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AutocompleteSchemaToJSON(requestParameters['autocompleteSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/clickthrough</i><br><br>Shopper clicks on a Searchspring autocomplete search result rendered in the Autocomplete Module, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async autocompleteClickthrough(requestParameters: AutocompleteClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.autocompleteClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/impression</i><br><br>Shopper views the rendered Searchspring autocomplete results in the Autocomplete Module.
     * impression
     */
    async autocompleteImpressionRaw(requestParameters: AutocompleteImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteImpression().'
            );
        }

        if (requestParameters['autocompleteSchema'] == null) {
            throw new runtime.RequiredError(
                'autocompleteSchema',
                'Required parameter "autocompleteSchema" was null or undefined when calling autocompleteImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/autocomplete/impression`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AutocompleteSchemaToJSON(requestParameters['autocompleteSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/impression</i><br><br>Shopper views the rendered Searchspring autocomplete results in the Autocomplete Module.
     * impression
     */
    async autocompleteImpression(requestParameters: AutocompleteImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.autocompleteImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/redirect</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Searchspring autocomplete search results are rendered, but a redirect URL is returned in the Autocomplete API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async autocompleteRedirectRaw(requestParameters: AutocompleteRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteRedirect().'
            );
        }

        if (requestParameters['autocompleteRedirectSchema'] == null) {
            throw new runtime.RequiredError(
                'autocompleteRedirectSchema',
                'Required parameter "autocompleteRedirectSchema" was null or undefined when calling autocompleteRedirect().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/autocomplete/redirect`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AutocompleteRedirectSchemaToJSON(requestParameters['autocompleteRedirectSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/redirect</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Searchspring autocomplete search results are rendered, but a redirect URL is returned in the Autocomplete API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async autocompleteRedirect(requestParameters: AutocompleteRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.autocompleteRedirectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/render</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Searchspring autocomplete search results are rendered.
     * render
     */
    async autocompleteRenderRaw(requestParameters: AutocompleteRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteRender().'
            );
        }

        if (requestParameters['autocompleteSchema'] == null) {
            throw new runtime.RequiredError(
                'autocompleteSchema',
                'Required parameter "autocompleteSchema" was null or undefined when calling autocompleteRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/autocomplete/render`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AutocompleteSchemaToJSON(requestParameters['autocompleteSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/render</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Searchspring autocomplete search results are rendered.
     * render
     */
    async autocompleteRender(requestParameters: AutocompleteRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.autocompleteRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
