/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddtocartSchema,
  ClickthroughSchema,
  ErrorResponseBody,
  ImpressionSchema,
  InlineObject,
  InlineObject1,
  RedirectSchema,
  RenderSchema,
} from '../models/index';
import {
    AddtocartSchemaFromJSON,
    AddtocartSchemaToJSON,
    ClickthroughSchemaFromJSON,
    ClickthroughSchemaToJSON,
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    ImpressionSchemaFromJSON,
    ImpressionSchemaToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    RedirectSchemaFromJSON,
    RedirectSchemaToJSON,
    RenderSchemaFromJSON,
    RenderSchemaToJSON,
} from '../models/index';

export interface AutocompleteAddtocartRequest {
    siteId: string;
    addtocartSchema: AddtocartSchema;
}

export interface AutocompleteClickthroughRequest {
    siteId: string;
    clickthroughSchema: ClickthroughSchema;
}

export interface AutocompleteImpressionRequest {
    siteId: string;
    impressionSchema: ImpressionSchema;
}

export interface AutocompleteRedirectRequest {
    siteId: string;
    redirectSchema: RedirectSchema;
}

export interface AutocompleteRenderRequest {
    siteId: string;
    renderSchema: RenderSchema;
}

/**
 * 
 */
export class AutocompleteApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/addtocart</i><br><br>Shopper adds a Athos Commerce autocomplete result to the cart via a `Quick Add to Cart` button in the Autocomplete Module. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async autocompleteAddtocartRaw(requestParameters: AutocompleteAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteAddtocart().'
            );
        }

        if (requestParameters['addtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'addtocartSchema',
                'Required parameter "addtocartSchema" was null or undefined when calling autocompleteAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/autocomplete/addtocart`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddtocartSchemaToJSON(requestParameters['addtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/addtocart</i><br><br>Shopper adds a Athos Commerce autocomplete result to the cart via a `Quick Add to Cart` button in the Autocomplete Module. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async autocompleteAddtocart(requestParameters: AutocompleteAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.autocompleteAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/clickthrough</i><br><br>Shopper clicks on a Athos Commerce autocomplete search result rendered in the Autocomplete Module, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async autocompleteClickthroughRaw(requestParameters: AutocompleteClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteClickthrough().'
            );
        }

        if (requestParameters['clickthroughSchema'] == null) {
            throw new runtime.RequiredError(
                'clickthroughSchema',
                'Required parameter "clickthroughSchema" was null or undefined when calling autocompleteClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/autocomplete/clickthrough`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClickthroughSchemaToJSON(requestParameters['clickthroughSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/clickthrough</i><br><br>Shopper clicks on a Athos Commerce autocomplete search result rendered in the Autocomplete Module, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async autocompleteClickthrough(requestParameters: AutocompleteClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.autocompleteClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/impression</i><br><br>Shopper views the rendered Athos Commerce autocomplete results in the Autocomplete Module.
     * impression
     */
    async autocompleteImpressionRaw(requestParameters: AutocompleteImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteImpression().'
            );
        }

        if (requestParameters['impressionSchema'] == null) {
            throw new runtime.RequiredError(
                'impressionSchema',
                'Required parameter "impressionSchema" was null or undefined when calling autocompleteImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/autocomplete/impression`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImpressionSchemaToJSON(requestParameters['impressionSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/impression</i><br><br>Shopper views the rendered Athos Commerce autocomplete results in the Autocomplete Module.
     * impression
     */
    async autocompleteImpression(requestParameters: AutocompleteImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.autocompleteImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/redirect</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Athos Commerce autocomplete search results are rendered, but a redirect URL is returned in the Autocomplete API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async autocompleteRedirectRaw(requestParameters: AutocompleteRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteRedirect().'
            );
        }

        if (requestParameters['redirectSchema'] == null) {
            throw new runtime.RequiredError(
                'redirectSchema',
                'Required parameter "redirectSchema" was null or undefined when calling autocompleteRedirect().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/autocomplete/redirect`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RedirectSchemaToJSON(requestParameters['redirectSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/redirect</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Athos Commerce autocomplete search results are rendered, but a redirect URL is returned in the Autocomplete API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async autocompleteRedirect(requestParameters: AutocompleteRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.autocompleteRedirectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/render</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Athos Commerce autocomplete search results are rendered.
     * render
     */
    async autocompleteRenderRaw(requestParameters: AutocompleteRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling autocompleteRender().'
            );
        }

        if (requestParameters['renderSchema'] == null) {
            throw new runtime.RequiredError(
                'renderSchema',
                'Required parameter "renderSchema" was null or undefined when calling autocompleteRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/autocomplete/render`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenderSchemaToJSON(requestParameters['renderSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/autocomplete/render</i><br><br>Shopper types in the searchbar and an Autocomplete Module with Athos Commerce autocomplete search results are rendered.
     * render
     */
    async autocompleteRender(requestParameters: AutocompleteRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.autocompleteRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
