/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
	BundlesAddtocartSchema,
	BundlesClickthroughSchema,
	BundlesImpressionSchema,
	BundlesRenderSchema,
	ErrorResponseBody,
	InlineObject,
	InlineObject1,
} from '../models/index';
import {
	BundlesAddtocartSchemaFromJSON,
	BundlesAddtocartSchemaToJSON,
	BundlesClickthroughSchemaFromJSON,
	BundlesClickthroughSchemaToJSON,
	BundlesImpressionSchemaFromJSON,
	BundlesImpressionSchemaToJSON,
	BundlesRenderSchemaFromJSON,
	BundlesRenderSchemaToJSON,
	ErrorResponseBodyFromJSON,
	ErrorResponseBodyToJSON,
	InlineObjectFromJSON,
	InlineObjectToJSON,
	InlineObject1FromJSON,
	InlineObject1ToJSON,
} from '../models/index';

export interface BundlesAddtocartRequest {
	siteId: string;
	bundlesAddtocartSchema: BundlesAddtocartSchema;
}

export interface BundlesClickthroughRequest {
	siteId: string;
	bundlesClickthroughSchema: BundlesClickthroughSchema;
}

export interface BundlesImpressionRequest {
	siteId: string;
	bundlesImpressionSchema: BundlesImpressionSchema;
}

export interface BundlesRenderRequest {
	siteId: string;
	bundlesRenderSchema: BundlesRenderSchema;
}

/**
 *
 */
export class BundlesApi extends runtime.BaseAPI {
	/**
	 * <i>/beacon/v2/{siteId}/bundles/addtocart</i><br><br>Shopper adds a Athos Commerce personalized bundle result to the cart via a `Quick Add to Cart` button in the rendered product card. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
	 * addtocart
	 */
	async bundlesAddtocartRaw(
		requestParameters: BundlesAddtocartRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling bundlesAddtocart().');
		}

		if (requestParameters['bundlesAddtocartSchema'] == null) {
			throw new runtime.RequiredError(
				'bundlesAddtocartSchema',
				'Required parameter "bundlesAddtocartSchema" was null or undefined when calling bundlesAddtocart().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/bundles/addtocart`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: BundlesAddtocartSchemaToJSON(requestParameters['bundlesAddtocartSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/bundles/addtocart</i><br><br>Shopper adds a Athos Commerce personalized bundle result to the cart via a `Quick Add to Cart` button in the rendered product card. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
	 * addtocart
	 */
	async bundlesAddtocart(
		requestParameters: BundlesAddtocartRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<InlineObject> {
		const response = await this.bundlesAddtocartRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * <i>/beacon/v2/{siteId}/bundles/clickthrough</i><br><br>Shopper clicks on a rendered Athos Commerce personalized bundle result, and is taken to the product detail page (PDP).
	 * clickthrough
	 */
	async bundlesClickthroughRaw(
		requestParameters: BundlesClickthroughRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling bundlesClickthrough().');
		}

		if (requestParameters['bundlesClickthroughSchema'] == null) {
			throw new runtime.RequiredError(
				'bundlesClickthroughSchema',
				'Required parameter "bundlesClickthroughSchema" was null or undefined when calling bundlesClickthrough().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/bundles/clickthrough`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: BundlesClickthroughSchemaToJSON(requestParameters['bundlesClickthroughSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/bundles/clickthrough</i><br><br>Shopper clicks on a rendered Athos Commerce personalized bundle result, and is taken to the product detail page (PDP).
	 * clickthrough
	 */
	async bundlesClickthrough(
		requestParameters: BundlesClickthroughRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<InlineObject> {
		const response = await this.bundlesClickthroughRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * <i>/beacon/v2/{siteId}/bundles/impression</i><br><br>Shopper scrolls into view rendered Athos Commerce personalized bundle results. Results sent ***must*** only be results in the shoppers view at the time of the event.
	 * impression
	 */
	async bundlesImpressionRaw(
		requestParameters: BundlesImpressionRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling bundlesImpression().');
		}

		if (requestParameters['bundlesImpressionSchema'] == null) {
			throw new runtime.RequiredError(
				'bundlesImpressionSchema',
				'Required parameter "bundlesImpressionSchema" was null or undefined when calling bundlesImpression().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/bundles/impression`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: BundlesImpressionSchemaToJSON(requestParameters['bundlesImpressionSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/bundles/impression</i><br><br>Shopper scrolls into view rendered Athos Commerce personalized bundle results. Results sent ***must*** only be results in the shoppers view at the time of the event.
	 * impression
	 */
	async bundlesImpression(
		requestParameters: BundlesImpressionRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<InlineObject> {
		const response = await this.bundlesImpressionRaw(requestParameters, initOverrides);
		return await response.value();
	}

	/**
	 * <i>/beacon/v2/{siteId}/bundles/render</i><br><br>Shopper navigates to a page where Athos Commerce personalized bundles are requested from the [Personalized Bundles API endpoint](https://docs.searchspring.com/reference/get-bundles) and rendered on the page.
	 * render
	 */
	async bundlesRenderRaw(
		requestParameters: BundlesRenderRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<InlineObject>> {
		if (requestParameters['siteId'] == null) {
			throw new runtime.RequiredError('siteId', 'Required parameter "siteId" was null or undefined when calling bundlesRender().');
		}

		if (requestParameters['bundlesRenderSchema'] == null) {
			throw new runtime.RequiredError(
				'bundlesRenderSchema',
				'Required parameter "bundlesRenderSchema" was null or undefined when calling bundlesRender().'
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters['Content-Type'] = 'text/plain';

		let urlPath = `/{siteId}/bundles/render`;
		urlPath = urlPath.replace(`{${'siteId'}}`, encodeURIComponent(String(requestParameters['siteId'])));

		const response = await this.request(
			{
				path: urlPath,
				method: 'POST',
				headers: headerParameters,
				query: queryParameters,
				body: BundlesRenderSchemaToJSON(requestParameters['bundlesRenderSchema']),
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
	}

	/**
	 * <i>/beacon/v2/{siteId}/bundles/render</i><br><br>Shopper navigates to a page where Athos Commerce personalized bundles are requested from the [Personalized Bundles API endpoint](https://docs.searchspring.com/reference/get-bundles) and rendered on the page.
	 * render
	 */
	async bundlesRender(requestParameters: BundlesRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
		const response = await this.bundlesRenderRaw(requestParameters, initOverrides);
		return await response.value();
	}
}
