/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CartSchema,
  Model400Response,
  Model404Response,
} from '../models/index';
import {
    CartSchemaFromJSON,
    CartSchemaToJSON,
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
} from '../models/index';

export interface CartAddRequest {
    siteId: string;
    cartSchema: CartSchema;
}

export interface CartRemoveRequest {
    siteId: string;
    cartSchema: CartSchema;
}

/**
 * 
 */
export class CartApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/cart/add</i><br><br>Shopper adds additional item quantities to an item in the cart via the cart page or a slideout cart.
     * add
     */
    async cartAddRaw(requestParameters: CartAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling cartAdd().'
            );
        }

        if (requestParameters['cartSchema'] == null) {
            throw new runtime.RequiredError(
                'cartSchema',
                'Required parameter "cartSchema" was null or undefined when calling cartAdd().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/cart/add`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CartSchemaToJSON(requestParameters['cartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/cart/add</i><br><br>Shopper adds additional item quantities to an item in the cart via the cart page or a slideout cart.
     * add
     */
    async cartAdd(requestParameters: CartAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.cartAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/cart/remove</i><br><br>Shopper removes an item or reduces an items quantity in the cart via the cart page or a slideout cart.
     * remove
     */
    async cartRemoveRaw(requestParameters: CartRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling cartRemove().'
            );
        }

        if (requestParameters['cartSchema'] == null) {
            throw new runtime.RequiredError(
                'cartSchema',
                'Required parameter "cartSchema" was null or undefined when calling cartRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/cart/remove`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CartSchemaToJSON(requestParameters['cartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/cart/remove</i><br><br>Shopper removes an item or reduces an items quantity in the cart via the cart page or a slideout cart.
     * remove
     */
    async cartRemove(requestParameters: CartRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.cartRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
