/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddtocartSchema,
  ClickthroughSchema,
  ErrorResponseBody,
  ImpressionSchema,
  InlineObject,
  InlineObject1,
  RenderSchema,
} from '../models/index';
import {
    AddtocartSchemaFromJSON,
    AddtocartSchemaToJSON,
    ClickthroughSchemaFromJSON,
    ClickthroughSchemaToJSON,
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    ImpressionSchemaFromJSON,
    ImpressionSchemaToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    RenderSchemaFromJSON,
    RenderSchemaToJSON,
} from '../models/index';

export interface CategoryAddtocartRequest {
    siteId: string;
    addtocartSchema: AddtocartSchema;
}

export interface CategoryClickthroughRequest {
    siteId: string;
    clickthroughSchema: ClickthroughSchema;
}

export interface CategoryImpressionRequest {
    siteId: string;
    impressionSchema: ImpressionSchema;
}

export interface CategoryRenderRequest {
    siteId: string;
    renderSchema: RenderSchema;
}

/**
 * 
 */
export class CategoryApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/category/addtocart</i><br><br>Shopper lands on a category results page where Athos Commerce results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async categoryAddtocartRaw(requestParameters: CategoryAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryAddtocart().'
            );
        }

        if (requestParameters['addtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'addtocartSchema',
                'Required parameter "addtocartSchema" was null or undefined when calling categoryAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/category/addtocart`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddtocartSchemaToJSON(requestParameters['addtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/category/addtocart</i><br><br>Shopper lands on a category results page where Athos Commerce results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async categoryAddtocart(requestParameters: CategoryAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.categoryAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/category/clickthrough</i><br><br>Shopper lands on a category results page, clicks on a Athos Commerce result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async categoryClickthroughRaw(requestParameters: CategoryClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryClickthrough().'
            );
        }

        if (requestParameters['clickthroughSchema'] == null) {
            throw new runtime.RequiredError(
                'clickthroughSchema',
                'Required parameter "clickthroughSchema" was null or undefined when calling categoryClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/category/clickthrough`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClickthroughSchemaToJSON(requestParameters['clickthroughSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/category/clickthrough</i><br><br>Shopper lands on a category results page, clicks on a Athos Commerce result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async categoryClickthrough(requestParameters: CategoryClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.categoryClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/category/impression</i><br><br>Shopper lands on a category results page and Athos Commerce results receive an impression.
     * impression
     */
    async categoryImpressionRaw(requestParameters: CategoryImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryImpression().'
            );
        }

        if (requestParameters['impressionSchema'] == null) {
            throw new runtime.RequiredError(
                'impressionSchema',
                'Required parameter "impressionSchema" was null or undefined when calling categoryImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/category/impression`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImpressionSchemaToJSON(requestParameters['impressionSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/category/impression</i><br><br>Shopper lands on a category results page and Athos Commerce results receive an impression.
     * impression
     */
    async categoryImpression(requestParameters: CategoryImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.categoryImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/category/render</i><br><br>Shopper lands on a category results page and Athos Commerce results are rendered.
     * render
     */
    async categoryRenderRaw(requestParameters: CategoryRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryRender().'
            );
        }

        if (requestParameters['renderSchema'] == null) {
            throw new runtime.RequiredError(
                'renderSchema',
                'Required parameter "renderSchema" was null or undefined when calling categoryRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/category/render`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenderSchemaToJSON(requestParameters['renderSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/category/render</i><br><br>Shopper lands on a category results page and Athos Commerce results are rendered.
     * render
     */
    async categoryRender(requestParameters: CategoryRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.categoryRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
