/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoryAddtocartSchema,
  CategorySchema,
  Model400Response,
  Model404Response,
} from '../models/index';
import {
    CategoryAddtocartSchemaFromJSON,
    CategoryAddtocartSchemaToJSON,
    CategorySchemaFromJSON,
    CategorySchemaToJSON,
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
} from '../models/index';

export interface CategoryAddtocartRequest {
    siteId: string;
    categoryAddtocartSchema: CategoryAddtocartSchema;
}

export interface CategoryClickthroughRequest {
    siteId: string;
    categorySchema: CategorySchema;
}

export interface CategoryImpressionRequest {
    siteId: string;
    categorySchema: CategorySchema;
}

export interface CategoryRenderRequest {
    siteId: string;
    categorySchema: CategorySchema;
}

/**
 * 
 */
export class CategoryApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/category/addtocart</i><br><br>Shopper lands on a category results page where Searchspring results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async categoryAddtocartRaw(requestParameters: CategoryAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryAddtocart().'
            );
        }

        if (requestParameters['categoryAddtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'categoryAddtocartSchema',
                'Required parameter "categoryAddtocartSchema" was null or undefined when calling categoryAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/category/addtocart`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategoryAddtocartSchemaToJSON(requestParameters['categoryAddtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/category/addtocart</i><br><br>Shopper lands on a category results page where Searchspring results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async categoryAddtocart(requestParameters: CategoryAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.categoryAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/category/clickthrough</i><br><br>Shopper lands on a category results page, clicks on a Searchspring result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async categoryClickthroughRaw(requestParameters: CategoryClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryClickthrough().'
            );
        }

        if (requestParameters['categorySchema'] == null) {
            throw new runtime.RequiredError(
                'categorySchema',
                'Required parameter "categorySchema" was null or undefined when calling categoryClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/category/clickthrough`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategorySchemaToJSON(requestParameters['categorySchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/category/clickthrough</i><br><br>Shopper lands on a category results page, clicks on a Searchspring result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async categoryClickthrough(requestParameters: CategoryClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.categoryClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/category/impression</i><br><br>Shopper lands on a category results page and Searchspring results receive an impression.
     * impression
     */
    async categoryImpressionRaw(requestParameters: CategoryImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryImpression().'
            );
        }

        if (requestParameters['categorySchema'] == null) {
            throw new runtime.RequiredError(
                'categorySchema',
                'Required parameter "categorySchema" was null or undefined when calling categoryImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/category/impression`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategorySchemaToJSON(requestParameters['categorySchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/category/impression</i><br><br>Shopper lands on a category results page and Searchspring results receive an impression.
     * impression
     */
    async categoryImpression(requestParameters: CategoryImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.categoryImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/category/render</i><br><br>Shopper lands on a category results page and Searchspring results are rendered.
     * render
     */
    async categoryRenderRaw(requestParameters: CategoryRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling categoryRender().'
            );
        }

        if (requestParameters['categorySchema'] == null) {
            throw new runtime.RequiredError(
                'categorySchema',
                'Required parameter "categorySchema" was null or undefined when calling categoryRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/category/render`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategorySchemaToJSON(requestParameters['categorySchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/category/render</i><br><br>Shopper lands on a category results page and Searchspring results are rendered.
     * render
     */
    async categoryRender(requestParameters: CategoryRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.categoryRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
