/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponseBody,
  InlineObject,
  InlineObject1,
  LogSchema,
  PersonalizationLogSchema,
} from '../models/index';
import {
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    LogSchemaFromJSON,
    LogSchemaToJSON,
    PersonalizationLogSchemaFromJSON,
    PersonalizationLogSchemaToJSON,
} from '../models/index';

export interface LogPersonalizationRequest {
    siteId: string;
    personalizationLogSchema: PersonalizationLogSchema;
}

export interface LogShopifypixelRequest {
    siteId: string;
    logSchema: LogSchema;
}

export interface LogSnapRequest {
    siteId: string;
    logSchema: LogSchema;
}

/**
 * 
 */
export class ErrorLogsApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/log/personalization</i><br><br>Personalization error log events
     * personalization
     */
    async logPersonalizationRaw(requestParameters: LogPersonalizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling logPersonalization().'
            );
        }

        if (requestParameters['personalizationLogSchema'] == null) {
            throw new runtime.RequiredError(
                'personalizationLogSchema',
                'Required parameter "personalizationLogSchema" was null or undefined when calling logPersonalization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/log/personalization`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonalizationLogSchemaToJSON(requestParameters['personalizationLogSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/log/personalization</i><br><br>Personalization error log events
     * personalization
     */
    async logPersonalization(requestParameters: LogPersonalizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.logPersonalizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/log/shopifypixel</i><br><br>Shopify Pixel Extension error log events
     * shopifypixel
     */
    async logShopifypixelRaw(requestParameters: LogShopifypixelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling logShopifypixel().'
            );
        }

        if (requestParameters['logSchema'] == null) {
            throw new runtime.RequiredError(
                'logSchema',
                'Required parameter "logSchema" was null or undefined when calling logShopifypixel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/log/shopifypixel`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogSchemaToJSON(requestParameters['logSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/log/shopifypixel</i><br><br>Shopify Pixel Extension error log events
     * shopifypixel
     */
    async logShopifypixel(requestParameters: LogShopifypixelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.logShopifypixelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/log/snap</i><br><br>Snap error log events
     * snap
     */
    async logSnapRaw(requestParameters: LogSnapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling logSnap().'
            );
        }

        if (requestParameters['logSchema'] == null) {
            throw new runtime.RequiredError(
                'logSchema',
                'Required parameter "logSchema" was null or undefined when calling logSnap().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/log/snap`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LogSchemaToJSON(requestParameters['logSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/log/snap</i><br><br>Snap error log events
     * snap
     */
    async logSnap(requestParameters: LogSnapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.logSnapRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
