/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Model400Response,
  Model404Response,
  PersonalizationLogEvent,
  ShopifyPixelExtensionLogEvent,
  SnapLogEvent,
} from '../models/index';
import {
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
    PersonalizationLogEventFromJSON,
    PersonalizationLogEventToJSON,
    ShopifyPixelExtensionLogEventFromJSON,
    ShopifyPixelExtensionLogEventToJSON,
    SnapLogEventFromJSON,
    SnapLogEventToJSON,
} from '../models/index';

export interface LogPersonalizationRequest {
    siteId: string;
    personalizationLogEvent: PersonalizationLogEvent;
}

export interface LogShopifypixelRequest {
    siteId: string;
    shopifyPixelExtensionLogEvent: ShopifyPixelExtensionLogEvent;
}

export interface LogSnapRequest {
    siteId: string;
    snapLogEvent: SnapLogEvent;
}

/**
 * 
 */
export class ErrorLogsApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/log/personalization</i><br><br>Personalization error log events
     * personalization
     */
    async logPersonalizationRaw(requestParameters: LogPersonalizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling logPersonalization().'
            );
        }

        if (requestParameters['personalizationLogEvent'] == null) {
            throw new runtime.RequiredError(
                'personalizationLogEvent',
                'Required parameter "personalizationLogEvent" was null or undefined when calling logPersonalization().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/log/personalization`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonalizationLogEventToJSON(requestParameters['personalizationLogEvent']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/log/personalization</i><br><br>Personalization error log events
     * personalization
     */
    async logPersonalization(requestParameters: LogPersonalizationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.logPersonalizationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/log/shopifypixel</i><br><br>Shopify Pixel Extension error log events
     * shopifypixel
     */
    async logShopifypixelRaw(requestParameters: LogShopifypixelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling logShopifypixel().'
            );
        }

        if (requestParameters['shopifyPixelExtensionLogEvent'] == null) {
            throw new runtime.RequiredError(
                'shopifyPixelExtensionLogEvent',
                'Required parameter "shopifyPixelExtensionLogEvent" was null or undefined when calling logShopifypixel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/log/shopifypixel`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShopifyPixelExtensionLogEventToJSON(requestParameters['shopifyPixelExtensionLogEvent']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/log/shopifypixel</i><br><br>Shopify Pixel Extension error log events
     * shopifypixel
     */
    async logShopifypixel(requestParameters: LogShopifypixelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.logShopifypixelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/log/snap</i><br><br>Snap error log events
     * snap
     */
    async logSnapRaw(requestParameters: LogSnapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling logSnap().'
            );
        }

        if (requestParameters['snapLogEvent'] == null) {
            throw new runtime.RequiredError(
                'snapLogEvent',
                'Required parameter "snapLogEvent" was null or undefined when calling logSnap().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/log/snap`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SnapLogEventToJSON(requestParameters['snapLogEvent']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/log/snap</i><br><br>Snap error log events
     * snap
     */
    async logSnap(requestParameters: LogSnapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.logSnapRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
