/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponseBody,
  InlineObject,
  InlineObject1,
  MessagingSchema,
} from '../models/index';
import {
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    MessagingSchemaFromJSON,
    MessagingSchemaToJSON,
} from '../models/index';

export interface MessagingEmailClickthroughRequest {
    siteId: string;
    messagingSchema: MessagingSchema;
}

export interface MessagingEmailRenderRequest {
    siteId: string;
    messagingSchema: MessagingSchema;
}

export interface MessagingSmsClickthroughRequest {
    siteId: string;
    messagingSchema: MessagingSchema;
}

export interface MessagingSmsRenderRequest {
    siteId: string;
    messagingSchema: MessagingSchema;
}

/**
 * 
 */
export class MessagingRecommendationsApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/messaging/email/clickthrough</i><br><br>This event tracks when a shopper clicks through a messaging recommendation section in an email and is navigated to the website.
     * email/clickthrough
     */
    async messagingEmailClickthroughRaw(requestParameters: MessagingEmailClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling messagingEmailClickthrough().'
            );
        }

        if (requestParameters['messagingSchema'] == null) {
            throw new runtime.RequiredError(
                'messagingSchema',
                'Required parameter "messagingSchema" was null or undefined when calling messagingEmailClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/email/clickthrough`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessagingSchemaToJSON(requestParameters['messagingSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/messaging/email/clickthrough</i><br><br>This event tracks when a shopper clicks through a messaging recommendation section in an email and is navigated to the website.
     * email/clickthrough
     */
    async messagingEmailClickthrough(requestParameters: MessagingEmailClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.messagingEmailClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/messaging/email/render</i><br><br>This event tracks the rendering of a messaging recommendation section in an email.
     * email/render
     */
    async messagingEmailRenderRaw(requestParameters: MessagingEmailRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling messagingEmailRender().'
            );
        }

        if (requestParameters['messagingSchema'] == null) {
            throw new runtime.RequiredError(
                'messagingSchema',
                'Required parameter "messagingSchema" was null or undefined when calling messagingEmailRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/email/render`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessagingSchemaToJSON(requestParameters['messagingSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/messaging/email/render</i><br><br>This event tracks the rendering of a messaging recommendation section in an email.
     * email/render
     */
    async messagingEmailRender(requestParameters: MessagingEmailRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.messagingEmailRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/messaging/sms/clickthrough</i><br><br>This event tracks when a shopper clicks through a SMS recommendation section in an SMS text and is navigated to the website.
     * sms/clickthrough
     */
    async messagingSmsClickthroughRaw(requestParameters: MessagingSmsClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling messagingSmsClickthrough().'
            );
        }

        if (requestParameters['messagingSchema'] == null) {
            throw new runtime.RequiredError(
                'messagingSchema',
                'Required parameter "messagingSchema" was null or undefined when calling messagingSmsClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/sms/clickthrough`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessagingSchemaToJSON(requestParameters['messagingSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/messaging/sms/clickthrough</i><br><br>This event tracks when a shopper clicks through a SMS recommendation section in an SMS text and is navigated to the website.
     * sms/clickthrough
     */
    async messagingSmsClickthrough(requestParameters: MessagingSmsClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.messagingSmsClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/messaging/sms/render</i><br><br>This event tracks the rendering of an SMS recommendation section in an SMS text.
     * sms/render
     */
    async messagingSmsRenderRaw(requestParameters: MessagingSmsRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling messagingSmsRender().'
            );
        }

        if (requestParameters['messagingSchema'] == null) {
            throw new runtime.RequiredError(
                'messagingSchema',
                'Required parameter "messagingSchema" was null or undefined when calling messagingSmsRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/sms/render`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MessagingSchemaToJSON(requestParameters['messagingSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/messaging/sms/render</i><br><br>This event tracks the rendering of an SMS recommendation section in an SMS text.
     * sms/render
     */
    async messagingSmsRender(requestParameters: MessagingSmsRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.messagingSmsRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
