/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Model400Response,
  Model404Response,
  OrderTransactionSchema,
} from '../models/index';
import {
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
    OrderTransactionSchemaFromJSON,
    OrderTransactionSchemaToJSON,
} from '../models/index';

export interface OrderTransactionRequest {
    siteId: string;
    orderTransactionSchema: OrderTransactionSchema;
}

/**
 * 
 */
export class OrderApi extends runtime.BaseAPI {

    /**
     * Shopper has completed an order transaction. Tracks order contents.
     * /beacon/v2/{siteId}/order/transaction
     */
    async orderTransactionRaw(requestParameters: OrderTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling orderTransaction().'
            );
        }

        if (requestParameters['orderTransactionSchema'] == null) {
            throw new runtime.RequiredError(
                'orderTransactionSchema',
                'Required parameter "orderTransactionSchema" was null or undefined when calling orderTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/order/transaction`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderTransactionSchemaToJSON(requestParameters['orderTransactionSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Shopper has completed an order transaction. Tracks order contents.
     * /beacon/v2/{siteId}/order/transaction
     */
    async orderTransaction(requestParameters: OrderTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.orderTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
