/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponseBody,
  InlineObject,
  InlineObject1,
  OrderTransactionSchema,
} from '../models/index';
import {
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    OrderTransactionSchemaFromJSON,
    OrderTransactionSchemaToJSON,
} from '../models/index';

export interface OrderTransactionRequest {
    siteId: string;
    orderTransactionSchema: OrderTransactionSchema;
}

/**
 * 
 */
export class OrderApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/order/transaction</i><br><br>Shopper has completed an order transaction. Tracks order contents.
     * order transaction
     */
    async orderTransactionRaw(requestParameters: OrderTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling orderTransaction().'
            );
        }

        if (requestParameters['orderTransactionSchema'] == null) {
            throw new runtime.RequiredError(
                'orderTransactionSchema',
                'Required parameter "orderTransactionSchema" was null or undefined when calling orderTransaction().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/order/transaction`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderTransactionSchemaToJSON(requestParameters['orderTransactionSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/order/transaction</i><br><br>Shopper has completed an order transaction. Tracks order contents.
     * order transaction
     */
    async orderTransaction(requestParameters: OrderTransactionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.orderTransactionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
