/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Model400Response,
  Model404Response,
  ProductPageviewSchema,
} from '../models/index';
import {
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
    ProductPageviewSchemaFromJSON,
    ProductPageviewSchemaToJSON,
} from '../models/index';

export interface ProductPageviewRequest {
    siteId: string;
    productPageviewSchema: ProductPageviewSchema;
}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/product/pageview</i><br><br>Shopper has navigated to a product detail page (PDP).
     * pageview
     */
    async productPageviewRaw(requestParameters: ProductPageviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling productPageview().'
            );
        }

        if (requestParameters['productPageviewSchema'] == null) {
            throw new runtime.RequiredError(
                'productPageviewSchema',
                'Required parameter "productPageviewSchema" was null or undefined when calling productPageview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/product/pageview`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductPageviewSchemaToJSON(requestParameters['productPageviewSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/product/pageview</i><br><br>Shopper has navigated to a product detail page (PDP).
     * pageview
     */
    async productPageview(requestParameters: ProductPageviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.productPageviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
