/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Model400Response,
  Model404Response,
  RecommendationsAddtocartSchema,
  RecommendationsSchema,
} from '../models/index';
import {
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
    RecommendationsAddtocartSchemaFromJSON,
    RecommendationsAddtocartSchemaToJSON,
    RecommendationsSchemaFromJSON,
    RecommendationsSchemaToJSON,
} from '../models/index';

export interface RecommendationsAddtocartRequest {
    siteId: string;
    recommendationsAddtocartSchema: RecommendationsAddtocartSchema;
}

export interface RecommendationsClickthroughRequest {
    siteId: string;
    recommendationsSchema: RecommendationsSchema;
}

export interface RecommendationsImpressionRequest {
    siteId: string;
    recommendationsSchema: RecommendationsSchema;
}

export interface RecommendationsRenderRequest {
    siteId: string;
    recommendationsSchema: RecommendationsSchema;
}

/**
 * 
 */
export class RecommendationsApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/recommendations/addtocart</i><br><br>Shopper adds a Searchspring personalized recommendation result to the cart via a `Quick Add to Cart` button in the rendered product card. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async recommendationsAddtocartRaw(requestParameters: RecommendationsAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsAddtocart().'
            );
        }

        if (requestParameters['recommendationsAddtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsAddtocartSchema',
                'Required parameter "recommendationsAddtocartSchema" was null or undefined when calling recommendationsAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/recommendations/addtocart`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsAddtocartSchemaToJSON(requestParameters['recommendationsAddtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/addtocart</i><br><br>Shopper adds a Searchspring personalized recommendation result to the cart via a `Quick Add to Cart` button in the rendered product card. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async recommendationsAddtocart(requestParameters: RecommendationsAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.recommendationsAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/clickthrough</i><br><br>Shopper clicks on a rendered Searchspring personalized recommended result, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async recommendationsClickthroughRaw(requestParameters: RecommendationsClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsClickthrough().'
            );
        }

        if (requestParameters['recommendationsSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsSchema',
                'Required parameter "recommendationsSchema" was null or undefined when calling recommendationsClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/recommendations/clickthrough`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsSchemaToJSON(requestParameters['recommendationsSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/clickthrough</i><br><br>Shopper clicks on a rendered Searchspring personalized recommended result, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async recommendationsClickthrough(requestParameters: RecommendationsClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.recommendationsClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/impression</i><br><br>Shopper scrolls into view rendered Searchspring personalized recommended results. Results sent ***must*** only be results in the shoppers view at the time of the event.
     * impression
     */
    async recommendationsImpressionRaw(requestParameters: RecommendationsImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsImpression().'
            );
        }

        if (requestParameters['recommendationsSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsSchema',
                'Required parameter "recommendationsSchema" was null or undefined when calling recommendationsImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/recommendations/impression`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsSchemaToJSON(requestParameters['recommendationsSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/impression</i><br><br>Shopper scrolls into view rendered Searchspring personalized recommended results. Results sent ***must*** only be results in the shoppers view at the time of the event.
     * impression
     */
    async recommendationsImpression(requestParameters: RecommendationsImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.recommendationsImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/render</i><br><br>Shopper navigates to a page where Searchspring personalized recommendations are requested from the [Personalized Recommendations API endpoint](https://docs.searchspring.com/reference/get-recommendations) and rendered on the page.
     * render
     */
    async recommendationsRenderRaw(requestParameters: RecommendationsRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsRender().'
            );
        }

        if (requestParameters['recommendationsSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsSchema',
                'Required parameter "recommendationsSchema" was null or undefined when calling recommendationsRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/recommendations/render`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsSchemaToJSON(requestParameters['recommendationsSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/render</i><br><br>Shopper navigates to a page where Searchspring personalized recommendations are requested from the [Personalized Recommendations API endpoint](https://docs.searchspring.com/reference/get-recommendations) and rendered on the page.
     * render
     */
    async recommendationsRender(requestParameters: RecommendationsRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.recommendationsRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
