/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponseBody,
  InlineObject,
  InlineObject1,
  RecommendationsAddtocartSchema,
  RecommendationsClickthroughSchema,
  RecommendationsImpressionSchema,
  RecommendationsRenderSchema,
} from '../models/index';
import {
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    RecommendationsAddtocartSchemaFromJSON,
    RecommendationsAddtocartSchemaToJSON,
    RecommendationsClickthroughSchemaFromJSON,
    RecommendationsClickthroughSchemaToJSON,
    RecommendationsImpressionSchemaFromJSON,
    RecommendationsImpressionSchemaToJSON,
    RecommendationsRenderSchemaFromJSON,
    RecommendationsRenderSchemaToJSON,
} from '../models/index';

export interface RecommendationsAddtocartRequest {
    siteId: string;
    recommendationsAddtocartSchema: RecommendationsAddtocartSchema;
}

export interface RecommendationsClickthroughRequest {
    siteId: string;
    recommendationsClickthroughSchema: RecommendationsClickthroughSchema;
}

export interface RecommendationsImpressionRequest {
    siteId: string;
    recommendationsImpressionSchema: RecommendationsImpressionSchema;
}

export interface RecommendationsRenderRequest {
    siteId: string;
    recommendationsRenderSchema: RecommendationsRenderSchema;
}

/**
 * 
 */
export class RecommendationsApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/recommendations/addtocart</i><br><br>Shopper adds a Athos Commerce personalized recommendation result to the cart via a `Quick Add to Cart` button in the rendered product card. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async recommendationsAddtocartRaw(requestParameters: RecommendationsAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsAddtocart().'
            );
        }

        if (requestParameters['recommendationsAddtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsAddtocartSchema',
                'Required parameter "recommendationsAddtocartSchema" was null or undefined when calling recommendationsAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/recommendations/addtocart`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsAddtocartSchemaToJSON(requestParameters['recommendationsAddtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/addtocart</i><br><br>Shopper adds a Athos Commerce personalized recommendation result to the cart via a `Quick Add to Cart` button in the rendered product card. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async recommendationsAddtocart(requestParameters: RecommendationsAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.recommendationsAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/clickthrough</i><br><br>Shopper clicks on a rendered Athos Commerce personalized recommended result, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async recommendationsClickthroughRaw(requestParameters: RecommendationsClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsClickthrough().'
            );
        }

        if (requestParameters['recommendationsClickthroughSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsClickthroughSchema',
                'Required parameter "recommendationsClickthroughSchema" was null or undefined when calling recommendationsClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/recommendations/clickthrough`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsClickthroughSchemaToJSON(requestParameters['recommendationsClickthroughSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/clickthrough</i><br><br>Shopper clicks on a rendered Athos Commerce personalized recommended result, and is taken to the product detail page (PDP).
     * clickthrough
     */
    async recommendationsClickthrough(requestParameters: RecommendationsClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.recommendationsClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/impression</i><br><br>Shopper scrolls into view rendered Athos Commerce personalized recommended results. Results sent ***must*** only be results in the shoppers view at the time of the event.
     * impression
     */
    async recommendationsImpressionRaw(requestParameters: RecommendationsImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsImpression().'
            );
        }

        if (requestParameters['recommendationsImpressionSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsImpressionSchema',
                'Required parameter "recommendationsImpressionSchema" was null or undefined when calling recommendationsImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/recommendations/impression`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsImpressionSchemaToJSON(requestParameters['recommendationsImpressionSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/impression</i><br><br>Shopper scrolls into view rendered Athos Commerce personalized recommended results. Results sent ***must*** only be results in the shoppers view at the time of the event.
     * impression
     */
    async recommendationsImpression(requestParameters: RecommendationsImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.recommendationsImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/render</i><br><br>Shopper navigates to a page where Athos Commerce personalized recommendations are requested from the [Personalized Recommendations API endpoint](https://docs.searchspring.com/reference/get-recommendations) and rendered on the page.
     * render
     */
    async recommendationsRenderRaw(requestParameters: RecommendationsRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling recommendationsRender().'
            );
        }

        if (requestParameters['recommendationsRenderSchema'] == null) {
            throw new runtime.RequiredError(
                'recommendationsRenderSchema',
                'Required parameter "recommendationsRenderSchema" was null or undefined when calling recommendationsRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/recommendations/render`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecommendationsRenderSchemaToJSON(requestParameters['recommendationsRenderSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/recommendations/render</i><br><br>Shopper navigates to a page where Athos Commerce personalized recommendations are requested from the [Personalized Recommendations API endpoint](https://docs.searchspring.com/reference/get-recommendations) and rendered on the page.
     * render
     */
    async recommendationsRender(requestParameters: RecommendationsRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.recommendationsRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
