/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddtocartSchema,
  ClickthroughSchema,
  ErrorResponseBody,
  ImpressionSchema,
  InlineObject,
  InlineObject1,
  RedirectSchema,
  RenderSchema,
} from '../models/index';
import {
    AddtocartSchemaFromJSON,
    AddtocartSchemaToJSON,
    ClickthroughSchemaFromJSON,
    ClickthroughSchemaToJSON,
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    ImpressionSchemaFromJSON,
    ImpressionSchemaToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    RedirectSchemaFromJSON,
    RedirectSchemaToJSON,
    RenderSchemaFromJSON,
    RenderSchemaToJSON,
} from '../models/index';

export interface SearchAddtocartRequest {
    siteId: string;
    addtocartSchema: AddtocartSchema;
}

export interface SearchClickthroughRequest {
    siteId: string;
    clickthroughSchema: ClickthroughSchema;
}

export interface SearchImpressionRequest {
    siteId: string;
    impressionSchema: ImpressionSchema;
}

export interface SearchRedirectRequest {
    siteId: string;
    redirectSchema: RedirectSchema;
}

export interface SearchRenderRequest {
    siteId: string;
    renderSchema: RenderSchema;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/search/addtocart</i><br><br>This event should be triggered when a shopper lands on a search results page where Athos Commerce search results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async searchAddtocartRaw(requestParameters: SearchAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchAddtocart().'
            );
        }

        if (requestParameters['addtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'addtocartSchema',
                'Required parameter "addtocartSchema" was null or undefined when calling searchAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/search/addtocart`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddtocartSchemaToJSON(requestParameters['addtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/search/addtocart</i><br><br>This event should be triggered when a shopper lands on a search results page where Athos Commerce search results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async searchAddtocart(requestParameters: SearchAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.searchAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/clickthrough</i><br><br>This event should be triggered when a shopper lands on a search results page, clicks on a Athos Commerce search result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async searchClickthroughRaw(requestParameters: SearchClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchClickthrough().'
            );
        }

        if (requestParameters['clickthroughSchema'] == null) {
            throw new runtime.RequiredError(
                'clickthroughSchema',
                'Required parameter "clickthroughSchema" was null or undefined when calling searchClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/search/clickthrough`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClickthroughSchemaToJSON(requestParameters['clickthroughSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/search/clickthrough</i><br><br>This event should be triggered when a shopper lands on a search results page, clicks on a Athos Commerce search result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async searchClickthrough(requestParameters: SearchClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.searchClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/impression</i><br><br>This event should be triggered when a shopper lands on a search results page and Athos Commerce search results receive an impression.
     * impression
     */
    async searchImpressionRaw(requestParameters: SearchImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchImpression().'
            );
        }

        if (requestParameters['impressionSchema'] == null) {
            throw new runtime.RequiredError(
                'impressionSchema',
                'Required parameter "impressionSchema" was null or undefined when calling searchImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/search/impression`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImpressionSchemaToJSON(requestParameters['impressionSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/search/impression</i><br><br>This event should be triggered when a shopper lands on a search results page and Athos Commerce search results receive an impression.
     * impression
     */
    async searchImpression(requestParameters: SearchImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.searchImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/redirect</i><br><br>This event should be triggered after a shopper lands on a search results page where Athos Commerce search results are rendered, but a redirect URL is returned in the Search API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async searchRedirectRaw(requestParameters: SearchRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchRedirect().'
            );
        }

        if (requestParameters['redirectSchema'] == null) {
            throw new runtime.RequiredError(
                'redirectSchema',
                'Required parameter "redirectSchema" was null or undefined when calling searchRedirect().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/search/redirect`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RedirectSchemaToJSON(requestParameters['redirectSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/search/redirect</i><br><br>This event should be triggered after a shopper lands on a search results page where Athos Commerce search results are rendered, but a redirect URL is returned in the Search API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async searchRedirect(requestParameters: SearchRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.searchRedirectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/render</i><br><br>This event should be triggered when a shopper lands on a search results page and Athos Commerce search results are rendered.
     * render
     */
    async searchRenderRaw(requestParameters: SearchRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchRender().'
            );
        }

        if (requestParameters['renderSchema'] == null) {
            throw new runtime.RequiredError(
                'renderSchema',
                'Required parameter "renderSchema" was null or undefined when calling searchRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/search/render`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RenderSchemaToJSON(requestParameters['renderSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/search/render</i><br><br>This event should be triggered when a shopper lands on a search results page and Athos Commerce search results are rendered.
     * render
     */
    async searchRender(requestParameters: SearchRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.searchRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
