/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Model400Response,
  Model404Response,
  SearchAddtocartSchema,
  SearchRedirectSchema,
  SearchSchema,
} from '../models/index';
import {
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
    SearchAddtocartSchemaFromJSON,
    SearchAddtocartSchemaToJSON,
    SearchRedirectSchemaFromJSON,
    SearchRedirectSchemaToJSON,
    SearchSchemaFromJSON,
    SearchSchemaToJSON,
} from '../models/index';

export interface SearchAddtocartRequest {
    siteId: string;
    searchAddtocartSchema: SearchAddtocartSchema;
}

export interface SearchClickthroughRequest {
    siteId: string;
    searchSchema: SearchSchema;
}

export interface SearchImpressionRequest {
    siteId: string;
    searchSchema: SearchSchema;
}

export interface SearchRedirectRequest {
    siteId: string;
    searchRedirectSchema: SearchRedirectSchema;
}

export interface SearchRenderRequest {
    siteId: string;
    searchSchema: SearchSchema;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/search/addtocart</i><br><br>This event should be triggered when a shopper lands on a search results page where Searchspring search results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async searchAddtocartRaw(requestParameters: SearchAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchAddtocart().'
            );
        }

        if (requestParameters['searchAddtocartSchema'] == null) {
            throw new runtime.RequiredError(
                'searchAddtocartSchema',
                'Required parameter "searchAddtocartSchema" was null or undefined when calling searchAddtocart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/search/addtocart`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchAddtocartSchemaToJSON(requestParameters['searchAddtocartSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/search/addtocart</i><br><br>This event should be triggered when a shopper lands on a search results page where Searchspring search results are rendered, and adds a result to the cart via a `Quick Add to Cart` button. **If frontend `Quick Add to Cart` is not implemented, omit usage of this endpoint.**
     * addtocart
     */
    async searchAddtocart(requestParameters: SearchAddtocartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchAddtocartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/clickthrough</i><br><br>This event should be triggered when a shopper lands on a search results page, clicks on a Searchspring search result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async searchClickthroughRaw(requestParameters: SearchClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchClickthrough().'
            );
        }

        if (requestParameters['searchSchema'] == null) {
            throw new runtime.RequiredError(
                'searchSchema',
                'Required parameter "searchSchema" was null or undefined when calling searchClickthrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/search/clickthrough`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchSchemaToJSON(requestParameters['searchSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/search/clickthrough</i><br><br>This event should be triggered when a shopper lands on a search results page, clicks on a Searchspring search result, and will be taken to the product detail page (PDP).
     * clickthrough
     */
    async searchClickthrough(requestParameters: SearchClickthroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchClickthroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/impression</i><br><br>This event should be triggered when a shopper lands on a search results page and Searchspring search results receive an impression.
     * impression
     */
    async searchImpressionRaw(requestParameters: SearchImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchImpression().'
            );
        }

        if (requestParameters['searchSchema'] == null) {
            throw new runtime.RequiredError(
                'searchSchema',
                'Required parameter "searchSchema" was null or undefined when calling searchImpression().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/search/impression`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchSchemaToJSON(requestParameters['searchSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/search/impression</i><br><br>This event should be triggered when a shopper lands on a search results page and Searchspring search results receive an impression.
     * impression
     */
    async searchImpression(requestParameters: SearchImpressionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchImpressionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/redirect</i><br><br>This event should be triggered after a shopper lands on a search results page where Searchspring search results are rendered, but a redirect URL is returned in the Search API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async searchRedirectRaw(requestParameters: SearchRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchRedirect().'
            );
        }

        if (requestParameters['searchRedirectSchema'] == null) {
            throw new runtime.RequiredError(
                'searchRedirectSchema',
                'Required parameter "searchRedirectSchema" was null or undefined when calling searchRedirect().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/search/redirect`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchRedirectSchemaToJSON(requestParameters['searchRedirectSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/search/redirect</i><br><br>This event should be triggered after a shopper lands on a search results page where Searchspring search results are rendered, but a redirect URL is returned in the Search API response and the shopper is redirected to the returned redirect URL.
     * redirect
     */
    async searchRedirect(requestParameters: SearchRedirectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchRedirectRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * <i>/beacon/v2/{siteId}/search/render</i><br><br>This event should be triggered when a shopper lands on a search results page and Searchspring search results are rendered.
     * render
     */
    async searchRenderRaw(requestParameters: SearchRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling searchRender().'
            );
        }

        if (requestParameters['searchSchema'] == null) {
            throw new runtime.RequiredError(
                'searchSchema',
                'Required parameter "searchSchema" was null or undefined when calling searchRender().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/search/render`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchSchemaToJSON(requestParameters['searchSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/search/render</i><br><br>This event should be triggered when a shopper lands on a search results page and Searchspring search results are rendered.
     * render
     */
    async searchRender(requestParameters: SearchRenderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.searchRenderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
