/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponseBody,
  InlineObject,
  InlineObject1,
  ShopperLoginSchema,
} from '../models/index';
import {
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    ShopperLoginSchemaFromJSON,
    ShopperLoginSchemaToJSON,
} from '../models/index';

export interface LoginRequest {
    siteId: string;
    shopperLoginSchema: ShopperLoginSchema;
}

/**
 * 
 */
export class ShopperApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/shopper/login</i><br><br>Shopper successfully logs into their account.
     * login
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InlineObject>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling login().'
            );
        }

        if (requestParameters['shopperLoginSchema'] == null) {
            throw new runtime.RequiredError(
                'shopperLoginSchema',
                'Required parameter "shopperLoginSchema" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';


        let urlPath = `/{siteId}/shopper/login`;
        urlPath = urlPath.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShopperLoginSchemaToJSON(requestParameters['shopperLoginSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InlineObjectFromJSON(jsonValue));
    }

    /**
     * <i>/beacon/v2/{siteId}/shopper/login</i><br><br>Shopper successfully logs into their account.
     * login
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InlineObject> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
