/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Model400Response,
  Model404Response,
  ShopperLoginSchema,
} from '../models/index';
import {
    Model400ResponseFromJSON,
    Model400ResponseToJSON,
    Model404ResponseFromJSON,
    Model404ResponseToJSON,
    ShopperLoginSchemaFromJSON,
    ShopperLoginSchemaToJSON,
} from '../models/index';

export interface LoginRequest {
    siteId: string;
    shopperLoginSchema: ShopperLoginSchema;
}

/**
 * 
 */
export class ShopperApi extends runtime.BaseAPI {

    /**
     * <i>/beacon/v2/{siteId}/shopper/login</i><br><br>Shopper successfully logs into their account.
     * login
     */
    async loginRaw(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['siteId'] == null) {
            throw new runtime.RequiredError(
                'siteId',
                'Required parameter "siteId" was null or undefined when calling login().'
            );
        }

        if (requestParameters['shopperLoginSchema'] == null) {
            throw new runtime.RequiredError(
                'shopperLoginSchema',
                'Required parameter "shopperLoginSchema" was null or undefined when calling login().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'text/plain';

        const response = await this.request({
            path: `/{siteId}/shopper/login`.replace(`{${"siteId"}}`, encodeURIComponent(String(requestParameters['siteId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ShopperLoginSchemaToJSON(requestParameters['shopperLoginSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * <i>/beacon/v2/{siteId}/shopper/login</i><br><br>Shopper successfully logs into their account.
     * login
     */
    async login(requestParameters: LoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.loginRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
