/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * Event details
 * @export
 * @interface AddtocartSchemaData
 */
export interface AddtocartSchemaData {
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof AddtocartSchemaData
     */
    responseId: string;
    /**
     * Products added to the cart
     * @type {Array<Product>}
     * @memberof AddtocartSchemaData
     */
    results: Array<Product>;
}

/**
 * Check if a given object implements the AddtocartSchemaData interface.
 */
export function instanceOfAddtocartSchemaData(value: object): value is AddtocartSchemaData {
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function AddtocartSchemaDataFromJSON(json: any): AddtocartSchemaData {
    return AddtocartSchemaDataFromJSONTyped(json, false);
}

export function AddtocartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddtocartSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'responseId': json['responseId'],
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
    };
}

export function AddtocartSchemaDataToJSON(json: any): AddtocartSchemaData {
    return AddtocartSchemaDataToJSONTyped(json, false);
}

export function AddtocartSchemaDataToJSONTyped(value?: AddtocartSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseId': value['responseId'],
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
    };
}

