/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { AddtocartSchemaData } from './AddtocartSchemaData';
import {
    AddtocartSchemaDataFromJSON,
    AddtocartSchemaDataFromJSONTyped,
    AddtocartSchemaDataToJSON,
    AddtocartSchemaDataToJSONTyped,
} from './AddtocartSchemaData';

/**
 * 
 * @export
 * @interface AddtocartSchema
 */
export interface AddtocartSchema {
    /**
     * 
     * @type {Context}
     * @memberof AddtocartSchema
     */
    context: Context;
    /**
     * 
     * @type {AddtocartSchemaData}
     * @memberof AddtocartSchema
     */
    data: AddtocartSchemaData;
}

/**
 * Check if a given object implements the AddtocartSchema interface.
 */
export function instanceOfAddtocartSchema(value: object): value is AddtocartSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AddtocartSchemaFromJSON(json: any): AddtocartSchema {
    return AddtocartSchemaFromJSONTyped(json, false);
}

export function AddtocartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddtocartSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': AddtocartSchemaDataFromJSON(json['data']),
    };
}

export function AddtocartSchemaToJSON(json: any): AddtocartSchema {
    return AddtocartSchemaToJSONTyped(json, false);
}

export function AddtocartSchemaToJSONTyped(value?: AddtocartSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': AddtocartSchemaDataToJSON(value['data']),
    };
}

