/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttributionInner
 */
export interface AttributionInner {
    /**
     * 
     * @type {string}
     * @memberof AttributionInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AttributionInner
     */
    id: string;
}

/**
 * Check if a given object implements the AttributionInner interface.
 */
export function instanceOfAttributionInner(value: object): value is AttributionInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AttributionInnerFromJSON(json: any): AttributionInner {
    return AttributionInnerFromJSONTyped(json, false);
}

export function AttributionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributionInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function AttributionInnerToJSON(json: any): AttributionInner {
    return AttributionInnerToJSONTyped(json, false);
}

export function AttributionInnerToJSONTyped(value?: AttributionInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

