/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { AutocompleteRedirectSchemaData } from './AutocompleteRedirectSchemaData';
import {
    AutocompleteRedirectSchemaDataFromJSON,
    AutocompleteRedirectSchemaDataFromJSONTyped,
    AutocompleteRedirectSchemaDataToJSON,
    AutocompleteRedirectSchemaDataToJSONTyped,
} from './AutocompleteRedirectSchemaData';

/**
 * 
 * @export
 * @interface AutocompleteRedirectSchema
 */
export interface AutocompleteRedirectSchema {
    /**
     * 
     * @type {Context}
     * @memberof AutocompleteRedirectSchema
     */
    context: Context;
    /**
     * 
     * @type {AutocompleteRedirectSchemaData}
     * @memberof AutocompleteRedirectSchema
     */
    data: AutocompleteRedirectSchemaData;
}

/**
 * Check if a given object implements the AutocompleteRedirectSchema interface.
 */
export function instanceOfAutocompleteRedirectSchema(value: object): value is AutocompleteRedirectSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AutocompleteRedirectSchemaFromJSON(json: any): AutocompleteRedirectSchema {
    return AutocompleteRedirectSchemaFromJSONTyped(json, false);
}

export function AutocompleteRedirectSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteRedirectSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': AutocompleteRedirectSchemaDataFromJSON(json['data']),
    };
}

  export function AutocompleteRedirectSchemaToJSON(json: any): AutocompleteRedirectSchema {
      return AutocompleteRedirectSchemaToJSONTyped(json, false);
  }

  export function AutocompleteRedirectSchemaToJSONTyped(value?: AutocompleteRedirectSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': AutocompleteRedirectSchemaDataToJSON(value['data']),
    };
}

