/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { AutocompleteAddtocartSchemaData } from './AutocompleteAddtocartSchemaData';
import {
    AutocompleteAddtocartSchemaDataFromJSON,
    AutocompleteAddtocartSchemaDataFromJSONTyped,
    AutocompleteAddtocartSchemaDataToJSON,
    AutocompleteAddtocartSchemaDataToJSONTyped,
} from './AutocompleteAddtocartSchemaData';

/**
 * 
 * @export
 * @interface AutocompleteAddtocartSchema
 */
export interface AutocompleteAddtocartSchema {
    /**
     * 
     * @type {Context}
     * @memberof AutocompleteAddtocartSchema
     */
    context: Context;
    /**
     * 
     * @type {AutocompleteAddtocartSchemaData}
     * @memberof AutocompleteAddtocartSchema
     */
    data: AutocompleteAddtocartSchemaData;
}

/**
 * Check if a given object implements the AutocompleteAddtocartSchema interface.
 */
export function instanceOfAutocompleteAddtocartSchema(value: object): value is AutocompleteAddtocartSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AutocompleteAddtocartSchemaFromJSON(json: any): AutocompleteAddtocartSchema {
    return AutocompleteAddtocartSchemaFromJSONTyped(json, false);
}

export function AutocompleteAddtocartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAddtocartSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': AutocompleteAddtocartSchemaDataFromJSON(json['data']),
    };
}

  export function AutocompleteAddtocartSchemaToJSON(json: any): AutocompleteAddtocartSchema {
      return AutocompleteAddtocartSchemaToJSONTyped(json, false);
  }

  export function AutocompleteAddtocartSchemaToJSONTyped(value?: AutocompleteAddtocartSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': AutocompleteAddtocartSchemaDataToJSON(value['data']),
    };
}

