/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination data returned from the Autocomplete API
 * @export
 * @interface AutocompleteAddtocartSchemaDataPagination
 */
export interface AutocompleteAddtocartSchemaDataPagination {
    /**
     * Total results returned as `pagination.totalResults` from Autocomplete API
     * @type {number}
     * @memberof AutocompleteAddtocartSchemaDataPagination
     */
    totalResults: number;
    /**
     * Current page returned as `pagination.currentPage` from Autocomplete API
     * @type {number}
     * @memberof AutocompleteAddtocartSchemaDataPagination
     */
    page: number;
    /**
     * Results per page returned as `pagination.resultsPerPage` from Autocomplete API
     * @type {number}
     * @memberof AutocompleteAddtocartSchemaDataPagination
     */
    resultsPerPage: number;
}

/**
 * Check if a given object implements the AutocompleteAddtocartSchemaDataPagination interface.
 */
export function instanceOfAutocompleteAddtocartSchemaDataPagination(value: object): value is AutocompleteAddtocartSchemaDataPagination {
    if (!('totalResults' in value) || value['totalResults'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('resultsPerPage' in value) || value['resultsPerPage'] === undefined) return false;
    return true;
}

export function AutocompleteAddtocartSchemaDataPaginationFromJSON(json: any): AutocompleteAddtocartSchemaDataPagination {
    return AutocompleteAddtocartSchemaDataPaginationFromJSONTyped(json, false);
}

export function AutocompleteAddtocartSchemaDataPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAddtocartSchemaDataPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResults': json['totalResults'],
        'page': json['page'],
        'resultsPerPage': json['resultsPerPage'],
    };
}

  export function AutocompleteAddtocartSchemaDataPaginationToJSON(json: any): AutocompleteAddtocartSchemaDataPagination {
      return AutocompleteAddtocartSchemaDataPaginationToJSONTyped(json, false);
  }

  export function AutocompleteAddtocartSchemaDataPaginationToJSONTyped(value?: AutocompleteAddtocartSchemaDataPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalResults': value['totalResults'],
        'page': value['page'],
        'resultsPerPage': value['resultsPerPage'],
    };
}

