/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteAddtocartSchemaDataFilterInner
 */
export interface AutocompleteAddtocartSchemaDataFilterInner {
    /**
     * Field of active filter
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaDataFilterInner
     */
    field?: string;
    /**
     * Value of active filter
     * @type {Array<string>}
     * @memberof AutocompleteAddtocartSchemaDataFilterInner
     */
    value?: Array<string>;
}

/**
 * Check if a given object implements the AutocompleteAddtocartSchemaDataFilterInner interface.
 */
export function instanceOfAutocompleteAddtocartSchemaDataFilterInner(value: object): value is AutocompleteAddtocartSchemaDataFilterInner {
    return true;
}

export function AutocompleteAddtocartSchemaDataFilterInnerFromJSON(json: any): AutocompleteAddtocartSchemaDataFilterInner {
    return AutocompleteAddtocartSchemaDataFilterInnerFromJSONTyped(json, false);
}

export function AutocompleteAddtocartSchemaDataFilterInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAddtocartSchemaDataFilterInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

  export function AutocompleteAddtocartSchemaDataFilterInnerToJSON(json: any): AutocompleteAddtocartSchemaDataFilterInner {
      return AutocompleteAddtocartSchemaDataFilterInnerToJSONTyped(json, false);
  }

  export function AutocompleteAddtocartSchemaDataFilterInnerToJSONTyped(value?: AutocompleteAddtocartSchemaDataFilterInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'value': value['value'],
    };
}

