/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
    ItemToJSONTyped,
} from './Item';
import type { BannersInner } from './BannersInner';
import {
    BannersInnerFromJSON,
    BannersInnerFromJSONTyped,
    BannersInnerToJSON,
    BannersInnerToJSONTyped,
} from './BannersInner';
import type { AutocompleteAddtocartSchemaDataBgfilterInner } from './AutocompleteAddtocartSchemaDataBgfilterInner';
import {
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataBgfilterInner';
import type { AutocompleteAddtocartSchemaDataSortInner } from './AutocompleteAddtocartSchemaDataSortInner';
import {
    AutocompleteAddtocartSchemaDataSortInnerFromJSON,
    AutocompleteAddtocartSchemaDataSortInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataSortInnerToJSON,
    AutocompleteAddtocartSchemaDataSortInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataSortInner';
import type { AutocompleteAddtocartSchemaDataPagination } from './AutocompleteAddtocartSchemaDataPagination';
import {
    AutocompleteAddtocartSchemaDataPaginationFromJSON,
    AutocompleteAddtocartSchemaDataPaginationFromJSONTyped,
    AutocompleteAddtocartSchemaDataPaginationToJSON,
    AutocompleteAddtocartSchemaDataPaginationToJSONTyped,
} from './AutocompleteAddtocartSchemaDataPagination';
import type { AutocompleteAddtocartSchemaDataMerchandising } from './AutocompleteAddtocartSchemaDataMerchandising';
import {
    AutocompleteAddtocartSchemaDataMerchandisingFromJSON,
    AutocompleteAddtocartSchemaDataMerchandisingFromJSONTyped,
    AutocompleteAddtocartSchemaDataMerchandisingToJSON,
    AutocompleteAddtocartSchemaDataMerchandisingToJSONTyped,
} from './AutocompleteAddtocartSchemaDataMerchandising';
import type { AutocompleteAddtocartSchemaDataFilterInner } from './AutocompleteAddtocartSchemaDataFilterInner';
import {
    AutocompleteAddtocartSchemaDataFilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataFilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataFilterInnerToJSON,
    AutocompleteAddtocartSchemaDataFilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataFilterInner';

/**
 * Event details
 * @export
 * @interface AutocompleteSchemaData
 */
export interface AutocompleteSchemaData {
    /**
     * Search query passed as the `q` query string parameter to the Autocomplete API
     * @type {string}
     * @memberof AutocompleteSchemaData
     */
    q: string;
    /**
     * If spell correction occurs, value will be `query.correctedQuery` from the Autocomplete API
     * @type {string}
     * @memberof AutocompleteSchemaData
     */
    correctedQuery?: string;
    /**
     * If autocomplete API response returns `didYouMean`, value must be `didYouMean.query`
     * @type {string}
     * @memberof AutocompleteSchemaData
     */
    didYouMean?: string;
    /**
     * Refined query passed as the `rq` query string parameter to the Autocomplete API. This should be omitted if search within search results is not implemented.
     * @type {string}
     * @memberof AutocompleteSchemaData
     */
    rq?: string;
    /**
     * Indicates the type of search matching that was required for this search, returned as `query.matchType` from Autocomplete API
     * @type {string}
     * @memberof AutocompleteSchemaData
     */
    matchType: AutocompleteSchemaDataMatchTypeEnum;
    /**
     * List of active background filters passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataBgfilterInner>}
     * @memberof AutocompleteSchemaData
     */
    bgfilter?: Array<AutocompleteAddtocartSchemaDataBgfilterInner>;
    /**
     * List of active filters passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataFilterInner>}
     * @memberof AutocompleteSchemaData
     */
    filter?: Array<AutocompleteAddtocartSchemaDataFilterInner>;
    /**
     * List of active sorts passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataSortInner>}
     * @memberof AutocompleteSchemaData
     */
    sort?: Array<AutocompleteAddtocartSchemaDataSortInner>;
    /**
     * 
     * @type {AutocompleteAddtocartSchemaDataPagination}
     * @memberof AutocompleteSchemaData
     */
    pagination: AutocompleteAddtocartSchemaDataPagination;
    /**
     * 
     * @type {AutocompleteAddtocartSchemaDataMerchandising}
     * @memberof AutocompleteSchemaData
     */
    merchandising?: AutocompleteAddtocartSchemaDataMerchandising;
    /**
     * List of tracked Searchspring result(s). An empty array will indicate zero results were returned in the API response.
     * @type {Array<Item>}
     * @memberof AutocompleteSchemaData
     */
    results: Array<Item>;
    /**
     * List of banners UID's returned in `merchandising.content`. Omitting this field indicates zero banners were returned in the API response.
     * @type {Array<BannersInner>}
     * @memberof AutocompleteSchemaData
     */
    banners: Array<BannersInner>;
}


/**
 * @export
 */
export const AutocompleteSchemaDataMatchTypeEnum = {
    Primary: 'primary',
    Expanded: 'expanded'
} as const;
export type AutocompleteSchemaDataMatchTypeEnum = typeof AutocompleteSchemaDataMatchTypeEnum[keyof typeof AutocompleteSchemaDataMatchTypeEnum];


/**
 * Check if a given object implements the AutocompleteSchemaData interface.
 */
export function instanceOfAutocompleteSchemaData(value: object): value is AutocompleteSchemaData {
    if (!('q' in value) || value['q'] === undefined) return false;
    if (!('matchType' in value) || value['matchType'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('banners' in value) || value['banners'] === undefined) return false;
    return true;
}

export function AutocompleteSchemaDataFromJSON(json: any): AutocompleteSchemaData {
    return AutocompleteSchemaDataFromJSONTyped(json, false);
}

export function AutocompleteSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'q': json['q'],
        'correctedQuery': json['correctedQuery'] == null ? undefined : json['correctedQuery'],
        'didYouMean': json['didYouMean'] == null ? undefined : json['didYouMean'],
        'rq': json['rq'] == null ? undefined : json['rq'],
        'matchType': json['matchType'],
        'bgfilter': json['bgfilter'] == null ? undefined : ((json['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON)),
        'filter': json['filter'] == null ? undefined : ((json['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerFromJSON)),
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerFromJSON)),
        'pagination': AutocompleteAddtocartSchemaDataPaginationFromJSON(json['pagination']),
        'merchandising': json['merchandising'] == null ? undefined : AutocompleteAddtocartSchemaDataMerchandisingFromJSON(json['merchandising']),
        'results': ((json['results'] as Array<any>).map(ItemFromJSON)),
        'banners': ((json['banners'] as Array<any>).map(BannersInnerFromJSON)),
    };
}

  export function AutocompleteSchemaDataToJSON(json: any): AutocompleteSchemaData {
      return AutocompleteSchemaDataToJSONTyped(json, false);
  }

  export function AutocompleteSchemaDataToJSONTyped(value?: AutocompleteSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'q': value['q'],
        'correctedQuery': value['correctedQuery'],
        'didYouMean': value['didYouMean'],
        'rq': value['rq'],
        'matchType': value['matchType'],
        'bgfilter': value['bgfilter'] == null ? undefined : ((value['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerToJSON)),
        'filter': value['filter'] == null ? undefined : ((value['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerToJSON)),
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerToJSON)),
        'pagination': AutocompleteAddtocartSchemaDataPaginationToJSON(value['pagination']),
        'merchandising': AutocompleteAddtocartSchemaDataMerchandisingToJSON(value['merchandising']),
        'results': ((value['results'] as Array<any>).map(ItemToJSON)),
        'banners': ((value['banners'] as Array<any>).map(BannersInnerToJSON)),
    };
}

