/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteAddtocartSchemaDataSortInner
 */
export interface AutocompleteAddtocartSchemaDataSortInner {
    /**
     * Field of active sort
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaDataSortInner
     */
    field?: string;
    /**
     * Direction of active sort
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaDataSortInner
     */
    dir?: AutocompleteAddtocartSchemaDataSortInnerDirEnum;
}


/**
 * @export
 */
export const AutocompleteAddtocartSchemaDataSortInnerDirEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type AutocompleteAddtocartSchemaDataSortInnerDirEnum = typeof AutocompleteAddtocartSchemaDataSortInnerDirEnum[keyof typeof AutocompleteAddtocartSchemaDataSortInnerDirEnum];


/**
 * Check if a given object implements the AutocompleteAddtocartSchemaDataSortInner interface.
 */
export function instanceOfAutocompleteAddtocartSchemaDataSortInner(value: object): value is AutocompleteAddtocartSchemaDataSortInner {
    return true;
}

export function AutocompleteAddtocartSchemaDataSortInnerFromJSON(json: any): AutocompleteAddtocartSchemaDataSortInner {
    return AutocompleteAddtocartSchemaDataSortInnerFromJSONTyped(json, false);
}

export function AutocompleteAddtocartSchemaDataSortInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAddtocartSchemaDataSortInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'dir': json['dir'] == null ? undefined : json['dir'],
    };
}

  export function AutocompleteAddtocartSchemaDataSortInnerToJSON(json: any): AutocompleteAddtocartSchemaDataSortInner {
      return AutocompleteAddtocartSchemaDataSortInnerToJSONTyped(json, false);
  }

  export function AutocompleteAddtocartSchemaDataSortInnerToJSONTyped(value?: AutocompleteAddtocartSchemaDataSortInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'dir': value['dir'],
    };
}

