/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutocompleteAddtocartSchemaDataBgfilterInner } from './AutocompleteAddtocartSchemaDataBgfilterInner';
import {
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataBgfilterInner';
import type { AutocompleteAddtocartSchemaDataSortInner } from './AutocompleteAddtocartSchemaDataSortInner';
import {
    AutocompleteAddtocartSchemaDataSortInnerFromJSON,
    AutocompleteAddtocartSchemaDataSortInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataSortInnerToJSON,
    AutocompleteAddtocartSchemaDataSortInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataSortInner';
import type { AutocompleteAddtocartSchemaDataPagination } from './AutocompleteAddtocartSchemaDataPagination';
import {
    AutocompleteAddtocartSchemaDataPaginationFromJSON,
    AutocompleteAddtocartSchemaDataPaginationFromJSONTyped,
    AutocompleteAddtocartSchemaDataPaginationToJSON,
    AutocompleteAddtocartSchemaDataPaginationToJSONTyped,
} from './AutocompleteAddtocartSchemaDataPagination';
import type { AutocompleteAddtocartSchemaDataMerchandising } from './AutocompleteAddtocartSchemaDataMerchandising';
import {
    AutocompleteAddtocartSchemaDataMerchandisingFromJSON,
    AutocompleteAddtocartSchemaDataMerchandisingFromJSONTyped,
    AutocompleteAddtocartSchemaDataMerchandisingToJSON,
    AutocompleteAddtocartSchemaDataMerchandisingToJSONTyped,
} from './AutocompleteAddtocartSchemaDataMerchandising';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';
import type { AutocompleteAddtocartSchemaDataFilterInner } from './AutocompleteAddtocartSchemaDataFilterInner';
import {
    AutocompleteAddtocartSchemaDataFilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataFilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataFilterInnerToJSON,
    AutocompleteAddtocartSchemaDataFilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataFilterInner';

/**
 * Event details
 * @export
 * @interface AutocompleteAddtocartSchemaData
 */
export interface AutocompleteAddtocartSchemaData {
    /**
     * Search query passed as the `q` query string parameter to the Autocomplete API
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaData
     */
    q: string;
    /**
     * If spell correction occurs, value will be `query.correctedQuery` from the Autocomplete API
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaData
     */
    correctedQuery?: string;
    /**
     * If autocomplete API response returns `didYouMean`, value must be `didYouMean.query`
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaData
     */
    didYouMean?: string;
    /**
     * Refined query passed as the `rq` query string parameter to the Autocomplete API. This should be omitted if search within search results is not implemented.
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaData
     */
    rq?: string;
    /**
     * Indicates the type of search matching that was required for this search, returned as `query.matchType` from Autocomplete API
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaData
     */
    matchType: string;
    /**
     * List of active background filters passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataBgfilterInner>}
     * @memberof AutocompleteAddtocartSchemaData
     */
    bgfilter?: Array<AutocompleteAddtocartSchemaDataBgfilterInner>;
    /**
     * List of active filters passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataFilterInner>}
     * @memberof AutocompleteAddtocartSchemaData
     */
    filter?: Array<AutocompleteAddtocartSchemaDataFilterInner>;
    /**
     * List of active sorts passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataSortInner>}
     * @memberof AutocompleteAddtocartSchemaData
     */
    sort?: Array<AutocompleteAddtocartSchemaDataSortInner>;
    /**
     * 
     * @type {AutocompleteAddtocartSchemaDataPagination}
     * @memberof AutocompleteAddtocartSchemaData
     */
    pagination: AutocompleteAddtocartSchemaDataPagination;
    /**
     * 
     * @type {AutocompleteAddtocartSchemaDataMerchandising}
     * @memberof AutocompleteAddtocartSchemaData
     */
    merchandising?: AutocompleteAddtocartSchemaDataMerchandising;
    /**
     * Products added to the cart
     * @type {Array<Product>}
     * @memberof AutocompleteAddtocartSchemaData
     */
    results: Array<Product>;
}

/**
 * Check if a given object implements the AutocompleteAddtocartSchemaData interface.
 */
export function instanceOfAutocompleteAddtocartSchemaData(value: object): value is AutocompleteAddtocartSchemaData {
    if (!('q' in value) || value['q'] === undefined) return false;
    if (!('matchType' in value) || value['matchType'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function AutocompleteAddtocartSchemaDataFromJSON(json: any): AutocompleteAddtocartSchemaData {
    return AutocompleteAddtocartSchemaDataFromJSONTyped(json, false);
}

export function AutocompleteAddtocartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAddtocartSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'q': json['q'],
        'correctedQuery': json['correctedQuery'] == null ? undefined : json['correctedQuery'],
        'didYouMean': json['didYouMean'] == null ? undefined : json['didYouMean'],
        'rq': json['rq'] == null ? undefined : json['rq'],
        'matchType': json['matchType'],
        'bgfilter': json['bgfilter'] == null ? undefined : ((json['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON)),
        'filter': json['filter'] == null ? undefined : ((json['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerFromJSON)),
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerFromJSON)),
        'pagination': AutocompleteAddtocartSchemaDataPaginationFromJSON(json['pagination']),
        'merchandising': json['merchandising'] == null ? undefined : AutocompleteAddtocartSchemaDataMerchandisingFromJSON(json['merchandising']),
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
    };
}

  export function AutocompleteAddtocartSchemaDataToJSON(json: any): AutocompleteAddtocartSchemaData {
      return AutocompleteAddtocartSchemaDataToJSONTyped(json, false);
  }

  export function AutocompleteAddtocartSchemaDataToJSONTyped(value?: AutocompleteAddtocartSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'q': value['q'],
        'correctedQuery': value['correctedQuery'],
        'didYouMean': value['didYouMean'],
        'rq': value['rq'],
        'matchType': value['matchType'],
        'bgfilter': value['bgfilter'] == null ? undefined : ((value['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerToJSON)),
        'filter': value['filter'] == null ? undefined : ((value['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerToJSON)),
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerToJSON)),
        'pagination': AutocompleteAddtocartSchemaDataPaginationToJSON(value['pagination']),
        'merchandising': AutocompleteAddtocartSchemaDataMerchandisingToJSON(value['merchandising']),
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
    };
}

