/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AutocompleteAddtocartSchemaDataBgfilterInner
 */
export interface AutocompleteAddtocartSchemaDataBgfilterInner {
    /**
     * Field of active background filter
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaDataBgfilterInner
     */
    field?: string;
    /**
     * Value of active background filter
     * @type {Array<string>}
     * @memberof AutocompleteAddtocartSchemaDataBgfilterInner
     */
    value?: Array<string>;
}

/**
 * Check if a given object implements the AutocompleteAddtocartSchemaDataBgfilterInner interface.
 */
export function instanceOfAutocompleteAddtocartSchemaDataBgfilterInner(value: object): value is AutocompleteAddtocartSchemaDataBgfilterInner {
    return true;
}

export function AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON(json: any): AutocompleteAddtocartSchemaDataBgfilterInner {
    return AutocompleteAddtocartSchemaDataBgfilterInnerFromJSONTyped(json, false);
}

export function AutocompleteAddtocartSchemaDataBgfilterInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAddtocartSchemaDataBgfilterInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

  export function AutocompleteAddtocartSchemaDataBgfilterInnerToJSON(json: any): AutocompleteAddtocartSchemaDataBgfilterInner {
      return AutocompleteAddtocartSchemaDataBgfilterInnerToJSONTyped(json, false);
  }

  export function AutocompleteAddtocartSchemaDataBgfilterInnerToJSONTyped(value?: AutocompleteAddtocartSchemaDataBgfilterInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'value': value['value'],
    };
}

