/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { AutocompleteSchemaData } from './AutocompleteSchemaData';
import {
    AutocompleteSchemaDataFromJSON,
    AutocompleteSchemaDataFromJSONTyped,
    AutocompleteSchemaDataToJSON,
    AutocompleteSchemaDataToJSONTyped,
} from './AutocompleteSchemaData';

/**
 * 
 * @export
 * @interface AutocompleteSchema
 */
export interface AutocompleteSchema {
    /**
     * 
     * @type {Context}
     * @memberof AutocompleteSchema
     */
    context: Context;
    /**
     * 
     * @type {AutocompleteSchemaData}
     * @memberof AutocompleteSchema
     */
    data: AutocompleteSchemaData;
}

/**
 * Check if a given object implements the AutocompleteSchema interface.
 */
export function instanceOfAutocompleteSchema(value: object): value is AutocompleteSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AutocompleteSchemaFromJSON(json: any): AutocompleteSchema {
    return AutocompleteSchemaFromJSONTyped(json, false);
}

export function AutocompleteSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': AutocompleteSchemaDataFromJSON(json['data']),
    };
}

  export function AutocompleteSchemaToJSON(json: any): AutocompleteSchema {
      return AutocompleteSchemaToJSONTyped(json, false);
  }

  export function AutocompleteSchemaToJSONTyped(value?: AutocompleteSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': AutocompleteSchemaDataToJSON(value['data']),
    };
}

