/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface AutocompleteRedirectSchemaData
 */
export interface AutocompleteRedirectSchemaData {
    /**
     * Value returned as `merchandising.redirect` from Autocomplete API if a Searchspring configured redirect is triggered.
     * @type {string}
     * @memberof AutocompleteRedirectSchemaData
     */
    redirect: string;
}

/**
 * Check if a given object implements the AutocompleteRedirectSchemaData interface.
 */
export function instanceOfAutocompleteRedirectSchemaData(value: object): value is AutocompleteRedirectSchemaData {
    if (!('redirect' in value) || value['redirect'] === undefined) return false;
    return true;
}

export function AutocompleteRedirectSchemaDataFromJSON(json: any): AutocompleteRedirectSchemaData {
    return AutocompleteRedirectSchemaDataFromJSONTyped(json, false);
}

export function AutocompleteRedirectSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteRedirectSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'redirect': json['redirect'],
    };
}

  export function AutocompleteRedirectSchemaDataToJSON(json: any): AutocompleteRedirectSchemaData {
      return AutocompleteRedirectSchemaDataToJSONTyped(json, false);
  }

  export function AutocompleteRedirectSchemaDataToJSONTyped(value?: AutocompleteRedirectSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect': value['redirect'],
    };
}

