/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInner } from './AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInner';
import {
    AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSON,
    AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSON,
    AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInner';

/**
 * Merchandising data returned from the Autocomplete API
 * @export
 * @interface AutocompleteAddtocartSchemaDataMerchandising
 */
export interface AutocompleteAddtocartSchemaDataMerchandising {
    /**
     * Redirect URL returned as `merchandising.redirect` from Search API if a Searchspring configured redirect is triggered.
     * @type {string}
     * @memberof AutocompleteAddtocartSchemaDataMerchandising
     */
    redirect?: string;
    /**
     * Personalized value returned as `merchandising.personalized` from Autocomplete API
     * @type {boolean}
     * @memberof AutocompleteAddtocartSchemaDataMerchandising
     */
    personalized?: AutocompleteAddtocartSchemaDataMerchandisingPersonalizedEnum;
    /**
     * List of triggered campaigns returned as `merchandising.triggeredCampaigns` from the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInner>}
     * @memberof AutocompleteAddtocartSchemaDataMerchandising
     */
    triggeredCampaigns?: Array<AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInner>;
}


/**
 * @export
 */
export const AutocompleteAddtocartSchemaDataMerchandisingPersonalizedEnum = {
    True: true,
    False: false
} as const;
export type AutocompleteAddtocartSchemaDataMerchandisingPersonalizedEnum = typeof AutocompleteAddtocartSchemaDataMerchandisingPersonalizedEnum[keyof typeof AutocompleteAddtocartSchemaDataMerchandisingPersonalizedEnum];


/**
 * Check if a given object implements the AutocompleteAddtocartSchemaDataMerchandising interface.
 */
export function instanceOfAutocompleteAddtocartSchemaDataMerchandising(value: object): value is AutocompleteAddtocartSchemaDataMerchandising {
    return true;
}

export function AutocompleteAddtocartSchemaDataMerchandisingFromJSON(json: any): AutocompleteAddtocartSchemaDataMerchandising {
    return AutocompleteAddtocartSchemaDataMerchandisingFromJSONTyped(json, false);
}

export function AutocompleteAddtocartSchemaDataMerchandisingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AutocompleteAddtocartSchemaDataMerchandising {
    if (json == null) {
        return json;
    }
    return {
        
        'redirect': json['redirect'] == null ? undefined : json['redirect'],
        'personalized': json['personalized'] == null ? undefined : json['personalized'],
        'triggeredCampaigns': json['triggeredCampaigns'] == null ? undefined : ((json['triggeredCampaigns'] as Array<any>).map(AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSON)),
    };
}

  export function AutocompleteAddtocartSchemaDataMerchandisingToJSON(json: any): AutocompleteAddtocartSchemaDataMerchandising {
      return AutocompleteAddtocartSchemaDataMerchandisingToJSONTyped(json, false);
  }

  export function AutocompleteAddtocartSchemaDataMerchandisingToJSONTyped(value?: AutocompleteAddtocartSchemaDataMerchandising | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect': value['redirect'],
        'personalized': value['personalized'],
        'triggeredCampaigns': value['triggeredCampaigns'] == null ? undefined : ((value['triggeredCampaigns'] as Array<any>).map(AutocompleteAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSON)),
    };
}

