/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BannersInner
 */
export interface BannersInner {
    /**
     * Unique identifier of the banner
     * @type {string}
     * @memberof BannersInner
     */
    uid: string;
}

/**
 * Check if a given object implements the BannersInner interface.
 */
export function instanceOfBannersInner(value: object): value is BannersInner {
    if (!('uid' in value) || value['uid'] === undefined) return false;
    return true;
}

export function BannersInnerFromJSON(json: any): BannersInner {
    return BannersInnerFromJSONTyped(json, false);
}

export function BannersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BannersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'],
    };
}

export function BannersInnerToJSON(json: any): BannersInner {
    return BannersInnerToJSONTyped(json, false);
}

export function BannersInnerToJSONTyped(value?: BannersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

