/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BannersInner } from './BannersInner';
import { BannersInnerFromJSON, BannersInnerFromJSONTyped, BannersInnerToJSON, BannersInnerToJSONTyped } from './BannersInner';
import type { ResultsInner } from './ResultsInner';
import { ResultsInnerFromJSON, ResultsInnerFromJSONTyped, ResultsInnerToJSON, ResultsInnerToJSONTyped } from './ResultsInner';

/**
 * Event details
 * @export
 * @interface BundlesImpressionSchemaData
 */
export interface BundlesImpressionSchemaData {
	/**
	 * Tag of the personalized recommendation profile the shopper interacted with
	 * @type {string}
	 * @memberof BundlesImpressionSchemaData
	 */
	tag: string;
	/**
	 * Unique ID returned in each API response
	 * @type {string}
	 * @memberof BundlesImpressionSchemaData
	 */
	responseId: string;
	/**
	 * List of tracked result(s). An empty array will indicate zero results were returned in the API response.
	 * @type {Array<ResultsInner>}
	 * @memberof BundlesImpressionSchemaData
	 */
	results?: Array<ResultsInner>;
	/**
	 * List of banners UID's returned in the API response. An empty array will indicate zero banners were returned in the API response.
	 * @type {Array<BannersInner>}
	 * @memberof BundlesImpressionSchemaData
	 */
	banners: Array<BannersInner>;
}

/**
 * Check if a given object implements the BundlesImpressionSchemaData interface.
 */
export function instanceOfBundlesImpressionSchemaData(value: object): value is BundlesImpressionSchemaData {
	if (!('tag' in value) || value['tag'] === undefined) return false;
	if (!('responseId' in value) || value['responseId'] === undefined) return false;
	if (!('banners' in value) || value['banners'] === undefined) return false;
	return true;
}

export function BundlesImpressionSchemaDataFromJSON(json: any): BundlesImpressionSchemaData {
	return BundlesImpressionSchemaDataFromJSONTyped(json, false);
}

export function BundlesImpressionSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesImpressionSchemaData {
	if (json == null) {
		return json;
	}
	return {
		tag: json['tag'],
		responseId: json['responseId'],
		results: json['results'] == null ? undefined : (json['results'] as Array<any>).map(ResultsInnerFromJSON),
		banners: (json['banners'] as Array<any>).map(BannersInnerFromJSON),
	};
}

export function BundlesImpressionSchemaDataToJSON(json: any): BundlesImpressionSchemaData {
	return BundlesImpressionSchemaDataToJSONTyped(json, false);
}

export function BundlesImpressionSchemaDataToJSONTyped(value?: BundlesImpressionSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		tag: value['tag'],
		responseId: value['responseId'],
		results: value['results'] == null ? undefined : (value['results'] as Array<any>).map(ResultsInnerToJSON),
		banners: (value['banners'] as Array<any>).map(BannersInnerToJSON),
	};
}
