/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface BundlesRenderSchemaData
 */
export interface BundlesRenderSchemaData {
	/**
	 * Tag of the personalized recommendation profile the shopper interacted with
	 * @type {string}
	 * @memberof BundlesRenderSchemaData
	 */
	tag: string;
	/**
	 * Unique ID returned in each API response
	 * @type {string}
	 * @memberof BundlesRenderSchemaData
	 */
	responseId: string;
}

/**
 * Check if a given object implements the BundlesRenderSchemaData interface.
 */
export function instanceOfBundlesRenderSchemaData(value: object): value is BundlesRenderSchemaData {
	if (!('tag' in value) || value['tag'] === undefined) return false;
	if (!('responseId' in value) || value['responseId'] === undefined) return false;
	return true;
}

export function BundlesRenderSchemaDataFromJSON(json: any): BundlesRenderSchemaData {
	return BundlesRenderSchemaDataFromJSONTyped(json, false);
}

export function BundlesRenderSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesRenderSchemaData {
	if (json == null) {
		return json;
	}
	return {
		tag: json['tag'],
		responseId: json['responseId'],
	};
}

export function BundlesRenderSchemaDataToJSON(json: any): BundlesRenderSchemaData {
	return BundlesRenderSchemaDataToJSONTyped(json, false);
}

export function BundlesRenderSchemaDataToJSONTyped(value?: BundlesRenderSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		tag: value['tag'],
		responseId: value['responseId'],
	};
}
