/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClickthroughBannersSchema1 } from './ClickthroughBannersSchema1';
import {
	instanceOfClickthroughBannersSchema1,
	ClickthroughBannersSchema1FromJSON,
	ClickthroughBannersSchema1FromJSONTyped,
	ClickthroughBannersSchema1ToJSON,
} from './ClickthroughBannersSchema1';
import type { ClickthroughResultsSchema1 } from './ClickthroughResultsSchema1';
import {
	instanceOfClickthroughResultsSchema1,
	ClickthroughResultsSchema1FromJSON,
	ClickthroughResultsSchema1FromJSONTyped,
	ClickthroughResultsSchema1ToJSON,
} from './ClickthroughResultsSchema1';

/**
 * @type BundlesClickthroughSchemaData
 * Event details
 * @export
 */
export type BundlesClickthroughSchemaData = ClickthroughBannersSchema1 | ClickthroughResultsSchema1;

export function BundlesClickthroughSchemaDataFromJSON(json: any): BundlesClickthroughSchemaData {
	return BundlesClickthroughSchemaDataFromJSONTyped(json, false);
}

export function BundlesClickthroughSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesClickthroughSchemaData {
	if (json == null) {
		return json;
	}
	if (typeof json !== 'object') {
		return json;
	}
	if (instanceOfClickthroughBannersSchema1(json)) {
		return ClickthroughBannersSchema1FromJSONTyped(json, true);
	}
	if (instanceOfClickthroughResultsSchema1(json)) {
		return ClickthroughResultsSchema1FromJSONTyped(json, true);
	}
	return {} as any;
}

export function BundlesClickthroughSchemaDataToJSON(json: any): any {
	return BundlesClickthroughSchemaDataToJSONTyped(json, false);
}

export function BundlesClickthroughSchemaDataToJSONTyped(value?: BundlesClickthroughSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}
	if (typeof value !== 'object') {
		return value;
	}
	if (instanceOfClickthroughBannersSchema1(value)) {
		return ClickthroughBannersSchema1ToJSON(value as ClickthroughBannersSchema1);
	}
	if (instanceOfClickthroughResultsSchema1(value)) {
		return ClickthroughResultsSchema1ToJSON(value as ClickthroughResultsSchema1);
	}
	return {};
}
