/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { BundlesClickthroughSchemaData } from './BundlesClickthroughSchemaData';
import {
	BundlesClickthroughSchemaDataFromJSON,
	BundlesClickthroughSchemaDataFromJSONTyped,
	BundlesClickthroughSchemaDataToJSON,
	BundlesClickthroughSchemaDataToJSONTyped,
} from './BundlesClickthroughSchemaData';

/**
 *
 * @export
 * @interface BundlesClickthroughSchema
 */
export interface BundlesClickthroughSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof BundlesClickthroughSchema
	 */
	context: Context;
	/**
	 *
	 * @type {BundlesClickthroughSchemaData}
	 * @memberof BundlesClickthroughSchema
	 */
	data: BundlesClickthroughSchemaData;
}

/**
 * Check if a given object implements the BundlesClickthroughSchema interface.
 */
export function instanceOfBundlesClickthroughSchema(value: object): value is BundlesClickthroughSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function BundlesClickthroughSchemaFromJSON(json: any): BundlesClickthroughSchema {
	return BundlesClickthroughSchemaFromJSONTyped(json, false);
}

export function BundlesClickthroughSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesClickthroughSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: BundlesClickthroughSchemaDataFromJSON(json['data']),
	};
}

export function BundlesClickthroughSchemaToJSON(json: any): BundlesClickthroughSchema {
	return BundlesClickthroughSchemaToJSONTyped(json, false);
}

export function BundlesClickthroughSchemaToJSONTyped(value?: BundlesClickthroughSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: BundlesClickthroughSchemaDataToJSON(value['data']),
	};
}
