/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { BundlesAddtocartSchemaData } from './BundlesAddtocartSchemaData';
import {
	BundlesAddtocartSchemaDataFromJSON,
	BundlesAddtocartSchemaDataFromJSONTyped,
	BundlesAddtocartSchemaDataToJSON,
	BundlesAddtocartSchemaDataToJSONTyped,
} from './BundlesAddtocartSchemaData';

/**
 *
 * @export
 * @interface BundlesAddtocartSchema
 */
export interface BundlesAddtocartSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof BundlesAddtocartSchema
	 */
	context: Context;
	/**
	 *
	 * @type {BundlesAddtocartSchemaData}
	 * @memberof BundlesAddtocartSchema
	 */
	data: BundlesAddtocartSchemaData;
}

/**
 * Check if a given object implements the BundlesAddtocartSchema interface.
 */
export function instanceOfBundlesAddtocartSchema(value: object): value is BundlesAddtocartSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function BundlesAddtocartSchemaFromJSON(json: any): BundlesAddtocartSchema {
	return BundlesAddtocartSchemaFromJSONTyped(json, false);
}

export function BundlesAddtocartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesAddtocartSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: BundlesAddtocartSchemaDataFromJSON(json['data']),
	};
}

export function BundlesAddtocartSchemaToJSON(json: any): BundlesAddtocartSchema {
	return BundlesAddtocartSchemaToJSONTyped(json, false);
}

export function BundlesAddtocartSchemaToJSONTyped(value?: BundlesAddtocartSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: BundlesAddtocartSchemaDataToJSON(value['data']),
	};
}
