/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { BundlesRenderSchemaData } from './BundlesRenderSchemaData';
import {
	BundlesRenderSchemaDataFromJSON,
	BundlesRenderSchemaDataFromJSONTyped,
	BundlesRenderSchemaDataToJSON,
	BundlesRenderSchemaDataToJSONTyped,
} from './BundlesRenderSchemaData';

/**
 *
 * @export
 * @interface BundlesRenderSchema
 */
export interface BundlesRenderSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof BundlesRenderSchema
	 */
	context: Context;
	/**
	 *
	 * @type {BundlesRenderSchemaData}
	 * @memberof BundlesRenderSchema
	 */
	data: BundlesRenderSchemaData;
}

/**
 * Check if a given object implements the BundlesRenderSchema interface.
 */
export function instanceOfBundlesRenderSchema(value: object): value is BundlesRenderSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function BundlesRenderSchemaFromJSON(json: any): BundlesRenderSchema {
	return BundlesRenderSchemaFromJSONTyped(json, false);
}

export function BundlesRenderSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesRenderSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: BundlesRenderSchemaDataFromJSON(json['data']),
	};
}

export function BundlesRenderSchemaToJSON(json: any): BundlesRenderSchema {
	return BundlesRenderSchemaToJSONTyped(json, false);
}

export function BundlesRenderSchemaToJSONTyped(value?: BundlesRenderSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: BundlesRenderSchemaDataToJSON(value['data']),
	};
}
