/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import { ContextFromJSON, ContextFromJSONTyped, ContextToJSON, ContextToJSONTyped } from './Context';
import type { BundlesImpressionSchemaData } from './BundlesImpressionSchemaData';
import {
	BundlesImpressionSchemaDataFromJSON,
	BundlesImpressionSchemaDataFromJSONTyped,
	BundlesImpressionSchemaDataToJSON,
	BundlesImpressionSchemaDataToJSONTyped,
} from './BundlesImpressionSchemaData';

/**
 *
 * @export
 * @interface BundlesImpressionSchema
 */
export interface BundlesImpressionSchema {
	/**
	 *
	 * @type {Context}
	 * @memberof BundlesImpressionSchema
	 */
	context: Context;
	/**
	 *
	 * @type {BundlesImpressionSchemaData}
	 * @memberof BundlesImpressionSchema
	 */
	data: BundlesImpressionSchemaData;
}

/**
 * Check if a given object implements the BundlesImpressionSchema interface.
 */
export function instanceOfBundlesImpressionSchema(value: object): value is BundlesImpressionSchema {
	if (!('context' in value) || value['context'] === undefined) return false;
	if (!('data' in value) || value['data'] === undefined) return false;
	return true;
}

export function BundlesImpressionSchemaFromJSON(json: any): BundlesImpressionSchema {
	return BundlesImpressionSchemaFromJSONTyped(json, false);
}

export function BundlesImpressionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesImpressionSchema {
	if (json == null) {
		return json;
	}
	return {
		context: ContextFromJSON(json['context']),
		data: BundlesImpressionSchemaDataFromJSON(json['data']),
	};
}

export function BundlesImpressionSchemaToJSON(json: any): BundlesImpressionSchema {
	return BundlesImpressionSchemaToJSONTyped(json, false);
}

export function BundlesImpressionSchemaToJSONTyped(value?: BundlesImpressionSchema | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		context: ContextToJSON(value['context']),
		data: BundlesImpressionSchemaDataToJSON(value['data']),
	};
}
