/* tslint:disable */
/* eslint-disable */
/**
 * analytics.athoscommerce.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import { ProductFromJSON, ProductFromJSONTyped, ProductToJSON, ProductToJSONTyped } from './Product';

/**
 * Event details
 * @export
 * @interface BundlesAddtocartSchemaData
 */
export interface BundlesAddtocartSchemaData {
	/**
	 * Unique ID returned in each API response
	 * @type {string}
	 * @memberof BundlesAddtocartSchemaData
	 */
	responseId: string;
	/**
	 * Tag of the personalized recommendation profile the shopper interacted with
	 * @type {string}
	 * @memberof BundlesAddtocartSchemaData
	 */
	tag: string;
	/**
	 * Products added to the cart
	 * @type {Array<Product>}
	 * @memberof BundlesAddtocartSchemaData
	 */
	results: Array<Product>;
}

/**
 * Check if a given object implements the BundlesAddtocartSchemaData interface.
 */
export function instanceOfBundlesAddtocartSchemaData(value: object): value is BundlesAddtocartSchemaData {
	if (!('responseId' in value) || value['responseId'] === undefined) return false;
	if (!('tag' in value) || value['tag'] === undefined) return false;
	if (!('results' in value) || value['results'] === undefined) return false;
	return true;
}

export function BundlesAddtocartSchemaDataFromJSON(json: any): BundlesAddtocartSchemaData {
	return BundlesAddtocartSchemaDataFromJSONTyped(json, false);
}

export function BundlesAddtocartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundlesAddtocartSchemaData {
	if (json == null) {
		return json;
	}
	return {
		responseId: json['responseId'],
		tag: json['tag'],
		results: (json['results'] as Array<any>).map(ProductFromJSON),
	};
}

export function BundlesAddtocartSchemaDataToJSON(json: any): BundlesAddtocartSchemaData {
	return BundlesAddtocartSchemaDataToJSONTyped(json, false);
}

export function BundlesAddtocartSchemaDataToJSONTyped(value?: BundlesAddtocartSchemaData | null, ignoreDiscriminator: boolean = false): any {
	if (value == null) {
		return value;
	}

	return {
		responseId: value['responseId'],
		tag: value['tag'],
		results: (value['results'] as Array<any>).map(ProductToJSON),
	};
}
