/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartSchemaData } from './CartSchemaData';
import {
    CartSchemaDataFromJSON,
    CartSchemaDataFromJSONTyped,
    CartSchemaDataToJSON,
    CartSchemaDataToJSONTyped,
} from './CartSchemaData';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';

/**
 * 
 * @export
 * @interface CartSchema
 */
export interface CartSchema {
    /**
     * 
     * @type {Context}
     * @memberof CartSchema
     */
    context: Context;
    /**
     * 
     * @type {CartSchemaData}
     * @memberof CartSchema
     */
    data: CartSchemaData;
}

/**
 * Check if a given object implements the CartSchema interface.
 */
export function instanceOfCartSchema(value: object): value is CartSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CartSchemaFromJSON(json: any): CartSchema {
    return CartSchemaFromJSONTyped(json, false);
}

export function CartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': CartSchemaDataFromJSON(json['data']),
    };
}

export function CartSchemaToJSON(json: any): CartSchema {
    return CartSchemaToJSONTyped(json, false);
}

export function CartSchemaToJSONTyped(value?: CartSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': CartSchemaDataToJSON(value['data']),
    };
}

