/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * Event details
 * @export
 * @interface CartSchemaData
 */
export interface CartSchemaData {
    /**
     * Product(s) that modified the cart
     * @type {Array<Product>}
     * @memberof CartSchemaData
     */
    results: Array<Product>;
    /**
     * Updated current cart products
     * @type {Array<Product>}
     * @memberof CartSchemaData
     */
    cart: Array<Product>;
}

/**
 * Check if a given object implements the CartSchemaData interface.
 */
export function instanceOfCartSchemaData(value: object): value is CartSchemaData {
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('cart' in value) || value['cart'] === undefined) return false;
    return true;
}

export function CartSchemaDataFromJSON(json: any): CartSchemaData {
    return CartSchemaDataFromJSONTyped(json, false);
}

export function CartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
        'cart': ((json['cart'] as Array<any>).map(ProductFromJSON)),
    };
}

export function CartSchemaDataToJSON(json: any): CartSchemaData {
    return CartSchemaDataToJSONTyped(json, false);
}

export function CartSchemaDataToJSONTyped(value?: CartSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
        'cart': ((value['cart'] as Array<any>).map(ProductToJSON)),
    };
}

