/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner
 */
export interface CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner {
    /**
     * Unique ID of the triggered campaign returned as `merchandising.triggeredCampaigns[i].id` from the Search API
     * @type {string}
     * @memberof CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner
     */
    id?: string;
    /**
     * If an A/B test is active for a triggered campaign, value will be returned as `merchandising.experiments[i].experimentId` WHERE the `merchandising.experiments[i].campaignId` matches `merchandising.triggeredCampaigns[i].id` from the Search API
     * @type {string}
     * @memberof CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner
     */
    experimentId?: string;
    /**
     * If an A/B test is active for a triggered campaign, value will be returned as `merchandising.experiments[i].variationId` WHERE the `merchandising.experiments[i].campaignId` matches `merchandising.triggeredCampaigns[i].id` from the Search API
     * @type {string}
     * @memberof CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner
     */
    variationId?: string;
}

/**
 * Check if a given object implements the CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner interface.
 */
export function instanceOfCategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner(value: object): value is CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner {
    return true;
}

export function CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSON(json: any): CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner {
    return CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSONTyped(json, false);
}

export function CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'experimentId': json['experimentId'] == null ? undefined : json['experimentId'],
        'variationId': json['variationId'] == null ? undefined : json['variationId'],
    };
}

  export function CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSON(json: any): CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner {
      return CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSONTyped(json, false);
  }

  export function CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSONTyped(value?: CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'experimentId': value['experimentId'],
        'variationId': value['variationId'],
    };
}

