/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner } from './CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner';
import {
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSON,
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSONTyped,
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSON,
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSONTyped,
} from './CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner';

/**
 * Merchandising data returned from the Search API
 * @export
 * @interface CategoryAddtocartSchemaDataMerchandising
 */
export interface CategoryAddtocartSchemaDataMerchandising {
    /**
     * Personalized value returned as `merchandising.personalized` from Search API
     * @type {boolean}
     * @memberof CategoryAddtocartSchemaDataMerchandising
     */
    personalized?: CategoryAddtocartSchemaDataMerchandisingPersonalizedEnum;
    /**
     * List of triggered campaigns returned as `merchandising.triggeredCampaigns` from the Search API
     * @type {Array<CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner>}
     * @memberof CategoryAddtocartSchemaDataMerchandising
     */
    triggeredCampaigns?: Array<CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner>;
}


/**
 * @export
 */
export const CategoryAddtocartSchemaDataMerchandisingPersonalizedEnum = {
    True: true,
    False: false
} as const;
export type CategoryAddtocartSchemaDataMerchandisingPersonalizedEnum = typeof CategoryAddtocartSchemaDataMerchandisingPersonalizedEnum[keyof typeof CategoryAddtocartSchemaDataMerchandisingPersonalizedEnum];


/**
 * Check if a given object implements the CategoryAddtocartSchemaDataMerchandising interface.
 */
export function instanceOfCategoryAddtocartSchemaDataMerchandising(value: object): value is CategoryAddtocartSchemaDataMerchandising {
    return true;
}

export function CategoryAddtocartSchemaDataMerchandisingFromJSON(json: any): CategoryAddtocartSchemaDataMerchandising {
    return CategoryAddtocartSchemaDataMerchandisingFromJSONTyped(json, false);
}

export function CategoryAddtocartSchemaDataMerchandisingFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryAddtocartSchemaDataMerchandising {
    if (json == null) {
        return json;
    }
    return {
        
        'personalized': json['personalized'] == null ? undefined : json['personalized'],
        'triggeredCampaigns': json['triggeredCampaigns'] == null ? undefined : ((json['triggeredCampaigns'] as Array<any>).map(CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSON)),
    };
}

  export function CategoryAddtocartSchemaDataMerchandisingToJSON(json: any): CategoryAddtocartSchemaDataMerchandising {
      return CategoryAddtocartSchemaDataMerchandisingToJSONTyped(json, false);
  }

  export function CategoryAddtocartSchemaDataMerchandisingToJSONTyped(value?: CategoryAddtocartSchemaDataMerchandising | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personalized': value['personalized'],
        'triggeredCampaigns': value['triggeredCampaigns'] == null ? undefined : ((value['triggeredCampaigns'] as Array<any>).map(CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSON)),
    };
}

