/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { CategorySchemaData } from './CategorySchemaData';
import {
    CategorySchemaDataFromJSON,
    CategorySchemaDataFromJSONTyped,
    CategorySchemaDataToJSON,
    CategorySchemaDataToJSONTyped,
} from './CategorySchemaData';

/**
 * 
 * @export
 * @interface CategorySchema
 */
export interface CategorySchema {
    /**
     * 
     * @type {Context}
     * @memberof CategorySchema
     */
    context: Context;
    /**
     * 
     * @type {CategorySchemaData}
     * @memberof CategorySchema
     */
    data: CategorySchemaData;
}

/**
 * Check if a given object implements the CategorySchema interface.
 */
export function instanceOfCategorySchema(value: object): value is CategorySchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CategorySchemaFromJSON(json: any): CategorySchema {
    return CategorySchemaFromJSONTyped(json, false);
}

export function CategorySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorySchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': CategorySchemaDataFromJSON(json['data']),
    };
}

  export function CategorySchemaToJSON(json: any): CategorySchema {
      return CategorySchemaToJSONTyped(json, false);
  }

  export function CategorySchemaToJSONTyped(value?: CategorySchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': CategorySchemaDataToJSON(value['data']),
    };
}

