/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pagination data returned from the Search API
 * @export
 * @interface CategoryAddtocartSchemaDataPagination
 */
export interface CategoryAddtocartSchemaDataPagination {
    /**
     * Total results returned as `pagination.totalResults` from Search API
     * @type {number}
     * @memberof CategoryAddtocartSchemaDataPagination
     */
    totalResults: number;
    /**
     * Current page returned as `pagination.currentPage` from Search API
     * @type {number}
     * @memberof CategoryAddtocartSchemaDataPagination
     */
    page: number;
    /**
     * Results per page returned as `pagination.resultsPerPage` from Search API
     * @type {number}
     * @memberof CategoryAddtocartSchemaDataPagination
     */
    resultsPerPage: number;
}

/**
 * Check if a given object implements the CategoryAddtocartSchemaDataPagination interface.
 */
export function instanceOfCategoryAddtocartSchemaDataPagination(value: object): value is CategoryAddtocartSchemaDataPagination {
    if (!('totalResults' in value) || value['totalResults'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('resultsPerPage' in value) || value['resultsPerPage'] === undefined) return false;
    return true;
}

export function CategoryAddtocartSchemaDataPaginationFromJSON(json: any): CategoryAddtocartSchemaDataPagination {
    return CategoryAddtocartSchemaDataPaginationFromJSONTyped(json, false);
}

export function CategoryAddtocartSchemaDataPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryAddtocartSchemaDataPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'totalResults': json['totalResults'],
        'page': json['page'],
        'resultsPerPage': json['resultsPerPage'],
    };
}

  export function CategoryAddtocartSchemaDataPaginationToJSON(json: any): CategoryAddtocartSchemaDataPagination {
      return CategoryAddtocartSchemaDataPaginationToJSONTyped(json, false);
  }

  export function CategoryAddtocartSchemaDataPaginationToJSONTyped(value?: CategoryAddtocartSchemaDataPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalResults': value['totalResults'],
        'page': value['page'],
        'resultsPerPage': value['resultsPerPage'],
    };
}

