/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { CategoryAddtocartSchemaData } from './CategoryAddtocartSchemaData';
import {
    CategoryAddtocartSchemaDataFromJSON,
    CategoryAddtocartSchemaDataFromJSONTyped,
    CategoryAddtocartSchemaDataToJSON,
    CategoryAddtocartSchemaDataToJSONTyped,
} from './CategoryAddtocartSchemaData';

/**
 * 
 * @export
 * @interface CategoryAddtocartSchema
 */
export interface CategoryAddtocartSchema {
    /**
     * 
     * @type {Context}
     * @memberof CategoryAddtocartSchema
     */
    context: Context;
    /**
     * 
     * @type {CategoryAddtocartSchemaData}
     * @memberof CategoryAddtocartSchema
     */
    data: CategoryAddtocartSchemaData;
}

/**
 * Check if a given object implements the CategoryAddtocartSchema interface.
 */
export function instanceOfCategoryAddtocartSchema(value: object): value is CategoryAddtocartSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CategoryAddtocartSchemaFromJSON(json: any): CategoryAddtocartSchema {
    return CategoryAddtocartSchemaFromJSONTyped(json, false);
}

export function CategoryAddtocartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryAddtocartSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': CategoryAddtocartSchemaDataFromJSON(json['data']),
    };
}

  export function CategoryAddtocartSchemaToJSON(json: any): CategoryAddtocartSchema {
      return CategoryAddtocartSchemaToJSONTyped(json, false);
  }

  export function CategoryAddtocartSchemaToJSONTyped(value?: CategoryAddtocartSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': CategoryAddtocartSchemaDataToJSON(value['data']),
    };
}

