/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AutocompleteAddtocartSchemaDataBgfilterInner } from './AutocompleteAddtocartSchemaDataBgfilterInner';
import {
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataBgfilterInner';
import type { AutocompleteAddtocartSchemaDataSortInner } from './AutocompleteAddtocartSchemaDataSortInner';
import {
    AutocompleteAddtocartSchemaDataSortInnerFromJSON,
    AutocompleteAddtocartSchemaDataSortInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataSortInnerToJSON,
    AutocompleteAddtocartSchemaDataSortInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataSortInner';
import type { CategoryAddtocartSchemaDataMerchandising } from './CategoryAddtocartSchemaDataMerchandising';
import {
    CategoryAddtocartSchemaDataMerchandisingFromJSON,
    CategoryAddtocartSchemaDataMerchandisingFromJSONTyped,
    CategoryAddtocartSchemaDataMerchandisingToJSON,
    CategoryAddtocartSchemaDataMerchandisingToJSONTyped,
} from './CategoryAddtocartSchemaDataMerchandising';
import type { CategoryAddtocartSchemaDataPagination } from './CategoryAddtocartSchemaDataPagination';
import {
    CategoryAddtocartSchemaDataPaginationFromJSON,
    CategoryAddtocartSchemaDataPaginationFromJSONTyped,
    CategoryAddtocartSchemaDataPaginationToJSON,
    CategoryAddtocartSchemaDataPaginationToJSONTyped,
} from './CategoryAddtocartSchemaDataPagination';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';
import type { AutocompleteAddtocartSchemaDataFilterInner } from './AutocompleteAddtocartSchemaDataFilterInner';
import {
    AutocompleteAddtocartSchemaDataFilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataFilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataFilterInnerToJSON,
    AutocompleteAddtocartSchemaDataFilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataFilterInner';

/**
 * Event details
 * @export
 * @interface CategoryAddtocartSchemaData
 */
export interface CategoryAddtocartSchemaData {
    /**
     * Refined query passed as the `rq` query string parameter to the Search API. This should be omitted if search within search results is not implemented.
     * @type {string}
     * @memberof CategoryAddtocartSchemaData
     */
    rq?: string;
    /**
     * Indicates the type of search matching that was required for this search, returned as `query.matchType` from Autocomplete API
     * @type {string}
     * @memberof CategoryAddtocartSchemaData
     */
    matchType: string;
    /**
     * List of active background filters passed to the Search API
     * @type {Array<AutocompleteAddtocartSchemaDataBgfilterInner>}
     * @memberof CategoryAddtocartSchemaData
     */
    bgfilter?: Array<AutocompleteAddtocartSchemaDataBgfilterInner>;
    /**
     * List of active filters passed to the Search API
     * @type {Array<AutocompleteAddtocartSchemaDataFilterInner>}
     * @memberof CategoryAddtocartSchemaData
     */
    filter?: Array<AutocompleteAddtocartSchemaDataFilterInner>;
    /**
     * List of active sorts passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataSortInner>}
     * @memberof CategoryAddtocartSchemaData
     */
    sort?: Array<AutocompleteAddtocartSchemaDataSortInner>;
    /**
     * 
     * @type {CategoryAddtocartSchemaDataPagination}
     * @memberof CategoryAddtocartSchemaData
     */
    pagination: CategoryAddtocartSchemaDataPagination;
    /**
     * 
     * @type {CategoryAddtocartSchemaDataMerchandising}
     * @memberof CategoryAddtocartSchemaData
     */
    merchandising?: CategoryAddtocartSchemaDataMerchandising;
    /**
     * Products added to the cart
     * @type {Array<Product>}
     * @memberof CategoryAddtocartSchemaData
     */
    results: Array<Product>;
}

/**
 * Check if a given object implements the CategoryAddtocartSchemaData interface.
 */
export function instanceOfCategoryAddtocartSchemaData(value: object): value is CategoryAddtocartSchemaData {
    if (!('matchType' in value) || value['matchType'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function CategoryAddtocartSchemaDataFromJSON(json: any): CategoryAddtocartSchemaData {
    return CategoryAddtocartSchemaDataFromJSONTyped(json, false);
}

export function CategoryAddtocartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryAddtocartSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'rq': json['rq'] == null ? undefined : json['rq'],
        'matchType': json['matchType'],
        'bgfilter': json['bgfilter'] == null ? undefined : ((json['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON)),
        'filter': json['filter'] == null ? undefined : ((json['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerFromJSON)),
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerFromJSON)),
        'pagination': CategoryAddtocartSchemaDataPaginationFromJSON(json['pagination']),
        'merchandising': json['merchandising'] == null ? undefined : CategoryAddtocartSchemaDataMerchandisingFromJSON(json['merchandising']),
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
    };
}

  export function CategoryAddtocartSchemaDataToJSON(json: any): CategoryAddtocartSchemaData {
      return CategoryAddtocartSchemaDataToJSONTyped(json, false);
  }

  export function CategoryAddtocartSchemaDataToJSONTyped(value?: CategoryAddtocartSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rq': value['rq'],
        'matchType': value['matchType'],
        'bgfilter': value['bgfilter'] == null ? undefined : ((value['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerToJSON)),
        'filter': value['filter'] == null ? undefined : ((value['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerToJSON)),
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerToJSON)),
        'pagination': CategoryAddtocartSchemaDataPaginationToJSON(value['pagination']),
        'merchandising': CategoryAddtocartSchemaDataMerchandisingToJSON(value['merchandising']),
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
    };
}

