/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClickthroughResultsInner } from './ClickthroughResultsInner';
import {
    ClickthroughResultsInnerFromJSON,
    ClickthroughResultsInnerFromJSONTyped,
    ClickthroughResultsInnerToJSON,
    ClickthroughResultsInnerToJSONTyped,
} from './ClickthroughResultsInner';

/**
 * 
 * @export
 * @interface ClickthroughResultsSchema1
 */
export interface ClickthroughResultsSchema1 {
    /**
     * Tag of the personalized recommendation profile the shopper interacted with
     * @type {string}
     * @memberof ClickthroughResultsSchema1
     */
    tag: string;
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof ClickthroughResultsSchema1
     */
    responseId: string;
    /**
     * List of tracked result(s). Can be a result that is either a product or a banner.
     * @type {Array<ClickthroughResultsInner>}
     * @memberof ClickthroughResultsSchema1
     */
    results: Array<ClickthroughResultsInner>;
}

/**
 * Check if a given object implements the ClickthroughResultsSchema1 interface.
 */
export function instanceOfClickthroughResultsSchema1(value: object): value is ClickthroughResultsSchema1 {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ClickthroughResultsSchema1FromJSON(json: any): ClickthroughResultsSchema1 {
    return ClickthroughResultsSchema1FromJSONTyped(json, false);
}

export function ClickthroughResultsSchema1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickthroughResultsSchema1 {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'responseId': json['responseId'],
        'results': ((json['results'] as Array<any>).map(ClickthroughResultsInnerFromJSON)),
    };
}

export function ClickthroughResultsSchema1ToJSON(json: any): ClickthroughResultsSchema1 {
    return ClickthroughResultsSchema1ToJSONTyped(json, false);
}

export function ClickthroughResultsSchema1ToJSONTyped(value?: ClickthroughResultsSchema1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'responseId': value['responseId'],
        'results': ((value['results'] as Array<any>).map(ClickthroughResultsInnerToJSON)),
    };
}

