/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClickthroughBannersInner } from './ClickthroughBannersInner';
import {
    ClickthroughBannersInnerFromJSON,
    ClickthroughBannersInnerFromJSONTyped,
    ClickthroughBannersInnerToJSON,
    ClickthroughBannersInnerToJSONTyped,
} from './ClickthroughBannersInner';

/**
 * 
 * @export
 * @interface ClickthroughBannersSchema
 */
export interface ClickthroughBannersSchema {
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof ClickthroughBannersSchema
     */
    responseId: string;
    /**
     * List of banners UID's returned in the API response. An empty array will indicate zero banners were returned in the API response.
     * @type {Array<ClickthroughBannersInner>}
     * @memberof ClickthroughBannersSchema
     */
    banners: Array<ClickthroughBannersInner>;
}

/**
 * Check if a given object implements the ClickthroughBannersSchema interface.
 */
export function instanceOfClickthroughBannersSchema(value: object): value is ClickthroughBannersSchema {
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('banners' in value) || value['banners'] === undefined) return false;
    return true;
}

export function ClickthroughBannersSchemaFromJSON(json: any): ClickthroughBannersSchema {
    return ClickthroughBannersSchemaFromJSONTyped(json, false);
}

export function ClickthroughBannersSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickthroughBannersSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'responseId': json['responseId'],
        'banners': ((json['banners'] as Array<any>).map(ClickthroughBannersInnerFromJSON)),
    };
}

export function ClickthroughBannersSchemaToJSON(json: any): ClickthroughBannersSchema {
    return ClickthroughBannersSchemaToJSONTyped(json, false);
}

export function ClickthroughBannersSchemaToJSONTyped(value?: ClickthroughBannersSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseId': value['responseId'],
        'banners': ((value['banners'] as Array<any>).map(ClickthroughBannersInnerToJSON)),
    };
}

