/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ClickthroughBannersSchema } from './ClickthroughBannersSchema';
import {
    instanceOfClickthroughBannersSchema,
    ClickthroughBannersSchemaFromJSON,
    ClickthroughBannersSchemaFromJSONTyped,
    ClickthroughBannersSchemaToJSON,
} from './ClickthroughBannersSchema';
import type { ClickthroughResultsSchema } from './ClickthroughResultsSchema';
import {
    instanceOfClickthroughResultsSchema,
    ClickthroughResultsSchemaFromJSON,
    ClickthroughResultsSchemaFromJSONTyped,
    ClickthroughResultsSchemaToJSON,
} from './ClickthroughResultsSchema';

/**
 * @type ClickthroughSchemaData
 * Event details
 * @export
 */
export type ClickthroughSchemaData = ClickthroughBannersSchema | ClickthroughResultsSchema;

export function ClickthroughSchemaDataFromJSON(json: any): ClickthroughSchemaData {
    return ClickthroughSchemaDataFromJSONTyped(json, false);
}

export function ClickthroughSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickthroughSchemaData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfClickthroughBannersSchema(json)) {
        return ClickthroughBannersSchemaFromJSONTyped(json, true);
    }
    if (instanceOfClickthroughResultsSchema(json)) {
        return ClickthroughResultsSchemaFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ClickthroughSchemaDataToJSON(json: any): any {
    return ClickthroughSchemaDataToJSONTyped(json, false);
}

export function ClickthroughSchemaDataToJSONTyped(value?: ClickthroughSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfClickthroughBannersSchema(value)) {
        return ClickthroughBannersSchemaToJSON(value as ClickthroughBannersSchema);
    }
    if (instanceOfClickthroughResultsSchema(value)) {
        return ClickthroughResultsSchemaToJSON(value as ClickthroughResultsSchema);
    }
    return {};
}

