/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClickthroughBannersInner } from './ClickthroughBannersInner';
import {
    ClickthroughBannersInnerFromJSON,
    ClickthroughBannersInnerFromJSONTyped,
    ClickthroughBannersInnerToJSON,
    ClickthroughBannersInnerToJSONTyped,
} from './ClickthroughBannersInner';

/**
 * 
 * @export
 * @interface ClickthroughBannersSchema1
 */
export interface ClickthroughBannersSchema1 {
    /**
     * Tag of the personalized recommendation profile the shopper interacted with
     * @type {string}
     * @memberof ClickthroughBannersSchema1
     */
    tag: string;
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof ClickthroughBannersSchema1
     */
    responseId: string;
    /**
     * List of banners UID's returned in the API response. An empty array will indicate zero banners were returned in the API response.
     * @type {Array<ClickthroughBannersInner>}
     * @memberof ClickthroughBannersSchema1
     */
    banners: Array<ClickthroughBannersInner>;
}

/**
 * Check if a given object implements the ClickthroughBannersSchema1 interface.
 */
export function instanceOfClickthroughBannersSchema1(value: object): value is ClickthroughBannersSchema1 {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('banners' in value) || value['banners'] === undefined) return false;
    return true;
}

export function ClickthroughBannersSchema1FromJSON(json: any): ClickthroughBannersSchema1 {
    return ClickthroughBannersSchema1FromJSONTyped(json, false);
}

export function ClickthroughBannersSchema1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickthroughBannersSchema1 {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'responseId': json['responseId'],
        'banners': ((json['banners'] as Array<any>).map(ClickthroughBannersInnerFromJSON)),
    };
}

export function ClickthroughBannersSchema1ToJSON(json: any): ClickthroughBannersSchema1 {
    return ClickthroughBannersSchema1ToJSONTyped(json, false);
}

export function ClickthroughBannersSchema1ToJSONTyped(value?: ClickthroughBannersSchema1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'responseId': value['responseId'],
        'banners': ((value['banners'] as Array<any>).map(ClickthroughBannersInnerToJSON)),
    };
}

