/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { ClickthroughSchemaData } from './ClickthroughSchemaData';
import {
    ClickthroughSchemaDataFromJSON,
    ClickthroughSchemaDataFromJSONTyped,
    ClickthroughSchemaDataToJSON,
    ClickthroughSchemaDataToJSONTyped,
} from './ClickthroughSchemaData';

/**
 * 
 * @export
 * @interface ClickthroughSchema
 */
export interface ClickthroughSchema {
    /**
     * 
     * @type {Context}
     * @memberof ClickthroughSchema
     */
    context: Context;
    /**
     * 
     * @type {ClickthroughSchemaData}
     * @memberof ClickthroughSchema
     */
    data: ClickthroughSchemaData;
}

/**
 * Check if a given object implements the ClickthroughSchema interface.
 */
export function instanceOfClickthroughSchema(value: object): value is ClickthroughSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ClickthroughSchemaFromJSON(json: any): ClickthroughSchema {
    return ClickthroughSchemaFromJSONTyped(json, false);
}

export function ClickthroughSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickthroughSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': ClickthroughSchemaDataFromJSON(json['data']),
    };
}

export function ClickthroughSchemaToJSON(json: any): ClickthroughSchema {
    return ClickthroughSchemaToJSONTyped(json, false);
}

export function ClickthroughSchemaToJSONTyped(value?: ClickthroughSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': ClickthroughSchemaDataToJSON(value['data']),
    };
}

