/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClickthroughBannersInner
 */
export interface ClickthroughBannersInner {
    /**
     * Unique identifier of the banner
     * @type {string}
     * @memberof ClickthroughBannersInner
     */
    uid: string;
}

/**
 * Check if a given object implements the ClickthroughBannersInner interface.
 */
export function instanceOfClickthroughBannersInner(value: object): value is ClickthroughBannersInner {
    if (!('uid' in value) || value['uid'] === undefined) return false;
    return true;
}

export function ClickthroughBannersInnerFromJSON(json: any): ClickthroughBannersInner {
    return ClickthroughBannersInnerFromJSONTyped(json, false);
}

export function ClickthroughBannersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickthroughBannersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'],
    };
}

export function ClickthroughBannersInnerToJSON(json: any): ClickthroughBannersInner {
    return ClickthroughBannersInnerToJSONTyped(json, false);
}

export function ClickthroughBannersInnerToJSONTyped(value?: ClickthroughBannersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
    };
}

