/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClickthroughResultsInner } from './ClickthroughResultsInner';
import {
    ClickthroughResultsInnerFromJSON,
    ClickthroughResultsInnerFromJSONTyped,
    ClickthroughResultsInnerToJSON,
    ClickthroughResultsInnerToJSONTyped,
} from './ClickthroughResultsInner';

/**
 * 
 * @export
 * @interface ClickthroughResultsSchema
 */
export interface ClickthroughResultsSchema {
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof ClickthroughResultsSchema
     */
    responseId: string;
    /**
     * List of tracked result(s). Can be a result that is either a product or a banner.
     * @type {Array<ClickthroughResultsInner>}
     * @memberof ClickthroughResultsSchema
     */
    results: Array<ClickthroughResultsInner>;
}

/**
 * Check if a given object implements the ClickthroughResultsSchema interface.
 */
export function instanceOfClickthroughResultsSchema(value: object): value is ClickthroughResultsSchema {
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ClickthroughResultsSchemaFromJSON(json: any): ClickthroughResultsSchema {
    return ClickthroughResultsSchemaFromJSONTyped(json, false);
}

export function ClickthroughResultsSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClickthroughResultsSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'responseId': json['responseId'],
        'results': ((json['results'] as Array<any>).map(ClickthroughResultsInnerFromJSON)),
    };
}

export function ClickthroughResultsSchemaToJSON(json: any): ClickthroughResultsSchema {
    return ClickthroughResultsSchemaToJSONTyped(json, false);
}

export function ClickthroughResultsSchemaToJSONTyped(value?: ClickthroughResultsSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseId': value['responseId'],
        'results': ((value['results'] as Array<any>).map(ClickthroughResultsInnerToJSON)),
    };
}

