/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContextAttributionInner
 */
export interface ContextAttributionInner {
    /**
     * 
     * @type {string}
     * @memberof ContextAttributionInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ContextAttributionInner
     */
    id: string;
}

/**
 * Check if a given object implements the ContextAttributionInner interface.
 */
export function instanceOfContextAttributionInner(value: object): value is ContextAttributionInner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ContextAttributionInnerFromJSON(json: any): ContextAttributionInner {
    return ContextAttributionInnerFromJSONTyped(json, false);
}

export function ContextAttributionInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextAttributionInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

  export function ContextAttributionInnerToJSON(json: any): ContextAttributionInner {
      return ContextAttributionInnerToJSONTyped(json, false);
  }

  export function ContextAttributionInnerToJSONTyped(value?: ContextAttributionInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
    };
}

