/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Active currency type on the site
 * @export
 * @interface ContextCurrency
 */
export interface ContextCurrency {
    /**
     * currency code in [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html#:~:text=The%20first%20two%20letters%20of,and%20the%20D%20for%20dollar.) format
     * @type {string}
     * @memberof ContextCurrency
     */
    code?: string;
}

/**
 * Check if a given object implements the ContextCurrency interface.
 */
export function instanceOfContextCurrency(value: object): value is ContextCurrency {
    return true;
}

export function ContextCurrencyFromJSON(json: any): ContextCurrency {
    return ContextCurrencyFromJSONTyped(json, false);
}

export function ContextCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextCurrency {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
    };
}

  export function ContextCurrencyToJSON(json: any): ContextCurrency {
      return ContextCurrencyToJSONTyped(json, false);
  }

  export function ContextCurrencyToJSONTyped(value?: ContextCurrency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

