/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseBody
 */
export interface ErrorResponseBody {
    /**
     * Data sent but not received due to an error
     * @type {boolean}
     * @memberof ErrorResponseBody
     */
    success?: boolean;
    /**
     * Cause of error
     * @type {string}
     * @memberof ErrorResponseBody
     */
    error?: string;
    /**
     * Cause of failure(s)
     * @type {Array<string>}
     * @memberof ErrorResponseBody
     */
    messages?: Array<string>;
}

/**
 * Check if a given object implements the ErrorResponseBody interface.
 */
export function instanceOfErrorResponseBody(value: object): value is ErrorResponseBody {
    return true;
}

export function ErrorResponseBodyFromJSON(json: any): ErrorResponseBody {
    return ErrorResponseBodyFromJSONTyped(json, false);
}

export function ErrorResponseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

export function ErrorResponseBodyToJSON(json: any): ErrorResponseBody {
    return ErrorResponseBodyToJSONTyped(json, false);
}

export function ErrorResponseBodyToJSONTyped(value?: ErrorResponseBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'messages': value['messages'],
    };
}

