/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { ImpressionSchemaData } from './ImpressionSchemaData';
import {
    ImpressionSchemaDataFromJSON,
    ImpressionSchemaDataFromJSONTyped,
    ImpressionSchemaDataToJSON,
    ImpressionSchemaDataToJSONTyped,
} from './ImpressionSchemaData';

/**
 * 
 * @export
 * @interface ImpressionSchema
 */
export interface ImpressionSchema {
    /**
     * 
     * @type {Context}
     * @memberof ImpressionSchema
     */
    context: Context;
    /**
     * 
     * @type {ImpressionSchemaData}
     * @memberof ImpressionSchema
     */
    data: ImpressionSchemaData;
}

/**
 * Check if a given object implements the ImpressionSchema interface.
 */
export function instanceOfImpressionSchema(value: object): value is ImpressionSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ImpressionSchemaFromJSON(json: any): ImpressionSchema {
    return ImpressionSchemaFromJSONTyped(json, false);
}

export function ImpressionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpressionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': ImpressionSchemaDataFromJSON(json['data']),
    };
}

export function ImpressionSchemaToJSON(json: any): ImpressionSchema {
    return ImpressionSchemaToJSONTyped(json, false);
}

export function ImpressionSchemaToJSONTyped(value?: ImpressionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': ImpressionSchemaDataToJSON(value['data']),
    };
}

