/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BannersInner } from './BannersInner';
import {
    BannersInnerFromJSON,
    BannersInnerFromJSONTyped,
    BannersInnerToJSON,
    BannersInnerToJSONTyped,
} from './BannersInner';
import type { ResultsInner } from './ResultsInner';
import {
    ResultsInnerFromJSON,
    ResultsInnerFromJSONTyped,
    ResultsInnerToJSON,
    ResultsInnerToJSONTyped,
} from './ResultsInner';

/**
 * Event details
 * @export
 * @interface ImpressionSchemaData
 */
export interface ImpressionSchemaData {
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof ImpressionSchemaData
     */
    responseId: string;
    /**
     * List of tracked result(s). An empty array will indicate zero results were returned in the API response.
     * @type {Array<ResultsInner>}
     * @memberof ImpressionSchemaData
     */
    results: Array<ResultsInner>;
    /**
     * List of banners UID's returned in the API response. An empty array will indicate zero banners were returned in the API response.
     * @type {Array<BannersInner>}
     * @memberof ImpressionSchemaData
     */
    banners: Array<BannersInner>;
}

/**
 * Check if a given object implements the ImpressionSchemaData interface.
 */
export function instanceOfImpressionSchemaData(value: object): value is ImpressionSchemaData {
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    if (!('banners' in value) || value['banners'] === undefined) return false;
    return true;
}

export function ImpressionSchemaDataFromJSON(json: any): ImpressionSchemaData {
    return ImpressionSchemaDataFromJSONTyped(json, false);
}

export function ImpressionSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImpressionSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'responseId': json['responseId'],
        'results': ((json['results'] as Array<any>).map(ResultsInnerFromJSON)),
        'banners': ((json['banners'] as Array<any>).map(BannersInnerFromJSON)),
    };
}

export function ImpressionSchemaDataToJSON(json: any): ImpressionSchemaData {
    return ImpressionSchemaDataToJSONTyped(json, false);
}

export function ImpressionSchemaDataToJSONTyped(value?: ImpressionSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseId': value['responseId'],
        'results': ((value['results'] as Array<any>).map(ResultsInnerToJSON)),
        'banners': ((value['banners'] as Array<any>).map(BannersInnerToJSON)),
    };
}

