/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationErrorWithDataField } from './ValidationErrorWithDataField';
import {
    ValidationErrorWithDataFieldFromJSON,
    ValidationErrorWithDataFieldFromJSONTyped,
    ValidationErrorWithDataFieldToJSON,
    ValidationErrorWithDataFieldToJSONTyped,
} from './ValidationErrorWithDataField';
import type { ErrorResponseBody } from './ErrorResponseBody';
import {
    ErrorResponseBodyFromJSON,
    ErrorResponseBodyFromJSONTyped,
    ErrorResponseBodyToJSON,
    ErrorResponseBodyToJSONTyped,
} from './ErrorResponseBody';

/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * Data sent but not received due to an error
     * @type {boolean}
     * @memberof InlineObject1
     */
    success?: boolean;
    /**
     * Cause of error
     * @type {string}
     * @memberof InlineObject1
     */
    error?: string;
    /**
     * Cause of failure(s)
     * @type {Array<string>}
     * @memberof InlineObject1
     */
    messages?: Array<string>;
    /**
     * Data sent where an error is identified
     * @type {string}
     * @memberof InlineObject1
     */
    data?: string;
}

/**
 * Check if a given object implements the InlineObject1 interface.
 */
export function instanceOfInlineObject1(value: object): value is InlineObject1 {
    return true;
}

export function InlineObject1FromJSON(json: any): InlineObject1 {
    return InlineObject1FromJSONTyped(json, false);
}

export function InlineObject1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject1 {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'messages': json['messages'] == null ? undefined : json['messages'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function InlineObject1ToJSON(json: any): InlineObject1 {
    return InlineObject1ToJSONTyped(json, false);
}

export function InlineObject1ToJSONTyped(value?: InlineObject1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'messages': value['messages'],
        'data': value['data'],
    };
}

