/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Log data about the event
 * @export
 * @interface Log
 */
export interface Log {
    /**
     * Error message
     * @type {string}
     * @memberof Log
     */
    message: string;
    /**
     * Stack trace of the error
     * @type {string}
     * @memberof Log
     */
    stack?: string;
    /**
     * Additional optional error details
     * @type {object}
     * @memberof Log
     */
    details?: object;
}

/**
 * Check if a given object implements the Log interface.
 */
export function instanceOfLog(value: object): value is Log {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LogFromJSON(json: any): Log {
    return LogFromJSONTyped(json, false);
}

export function LogFromJSONTyped(json: any, ignoreDiscriminator: boolean): Log {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'stack': json['stack'] == null ? undefined : json['stack'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

  export function LogToJSON(json: any): Log {
      return LogToJSONTyped(json, false);
  }

  export function LogToJSONTyped(value?: Log | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'stack': value['stack'],
        'details': value['details'],
    };
}

