/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { LogSchemaData } from './LogSchemaData';
import {
    LogSchemaDataFromJSON,
    LogSchemaDataFromJSONTyped,
    LogSchemaDataToJSON,
    LogSchemaDataToJSONTyped,
} from './LogSchemaData';

/**
 * 
 * @export
 * @interface LogSchema
 */
export interface LogSchema {
    /**
     * 
     * @type {Context}
     * @memberof LogSchema
     */
    context: Context;
    /**
     * 
     * @type {LogSchemaData}
     * @memberof LogSchema
     */
    data: LogSchemaData;
}

/**
 * Check if a given object implements the LogSchema interface.
 */
export function instanceOfLogSchema(value: object): value is LogSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LogSchemaFromJSON(json: any): LogSchema {
    return LogSchemaFromJSONTyped(json, false);
}

export function LogSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': LogSchemaDataFromJSON(json['data']),
    };
}

export function LogSchemaToJSON(json: any): LogSchema {
    return LogSchemaToJSONTyped(json, false);
}

export function LogSchemaToJSONTyped(value?: LogSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': LogSchemaDataToJSON(value['data']),
    };
}

