/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Log data about the event
 * @export
 * @interface LogSchemaData
 */
export interface LogSchemaData {
    /**
     * Error message
     * @type {string}
     * @memberof LogSchemaData
     */
    message: string;
    /**
     * Stack trace of the error
     * @type {string}
     * @memberof LogSchemaData
     */
    stack?: string;
    /**
     * Additional optional error details
     * @type {object}
     * @memberof LogSchemaData
     */
    details?: object;
}

/**
 * Check if a given object implements the LogSchemaData interface.
 */
export function instanceOfLogSchemaData(value: object): value is LogSchemaData {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LogSchemaDataFromJSON(json: any): LogSchemaData {
    return LogSchemaDataFromJSONTyped(json, false);
}

export function LogSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'stack': json['stack'] == null ? undefined : json['stack'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function LogSchemaDataToJSON(json: any): LogSchemaData {
    return LogSchemaDataToJSONTyped(json, false);
}

export function LogSchemaDataToJSONTyped(value?: LogSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'stack': value['stack'],
        'details': value['details'],
    };
}

