/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MessagingSchemaContext } from './MessagingSchemaContext';
import {
    MessagingSchemaContextFromJSON,
    MessagingSchemaContextFromJSONTyped,
    MessagingSchemaContextToJSON,
    MessagingSchemaContextToJSONTyped,
} from './MessagingSchemaContext';
import type { MessagingSchemaData } from './MessagingSchemaData';
import {
    MessagingSchemaDataFromJSON,
    MessagingSchemaDataFromJSONTyped,
    MessagingSchemaDataToJSON,
    MessagingSchemaDataToJSONTyped,
} from './MessagingSchemaData';

/**
 * 
 * @export
 * @interface MessagingSchema
 */
export interface MessagingSchema {
    /**
     * 
     * @type {MessagingSchemaContext}
     * @memberof MessagingSchema
     */
    context: MessagingSchemaContext;
    /**
     * 
     * @type {MessagingSchemaData}
     * @memberof MessagingSchema
     */
    data: MessagingSchemaData;
}

/**
 * Check if a given object implements the MessagingSchema interface.
 */
export function instanceOfMessagingSchema(value: object): value is MessagingSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MessagingSchemaFromJSON(json: any): MessagingSchema {
    return MessagingSchemaFromJSONTyped(json, false);
}

export function MessagingSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagingSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': MessagingSchemaContextFromJSON(json['context']),
        'data': MessagingSchemaDataFromJSON(json['data']),
    };
}

export function MessagingSchemaToJSON(json: any): MessagingSchema {
    return MessagingSchemaToJSONTyped(json, false);
}

export function MessagingSchemaToJSONTyped(value?: MessagingSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': MessagingSchemaContextToJSON(value['context']),
        'data': MessagingSchemaDataToJSON(value['data']),
    };
}

