/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contextual data about the event
 * @export
 * @interface MessagingSchemaContext
 */
export interface MessagingSchemaContext {
    /**
     * The unique identifier of the user
     * @type {string}
     * @memberof MessagingSchemaContext
     */
    userId: string;
    /**
     * RFC3339 formatted timestamp represents time of event
     * @type {string}
     * @memberof MessagingSchemaContext
     */
    timestamp: string;
    /**
     * Developer mode flag. If set to `true`, the event data will not populate in reporting
     * @type {boolean}
     * @memberof MessagingSchemaContext
     */
    dev?: boolean;
}

/**
 * Check if a given object implements the MessagingSchemaContext interface.
 */
export function instanceOfMessagingSchemaContext(value: object): value is MessagingSchemaContext {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function MessagingSchemaContextFromJSON(json: any): MessagingSchemaContext {
    return MessagingSchemaContextFromJSONTyped(json, false);
}

export function MessagingSchemaContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagingSchemaContext {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'timestamp': json['timestamp'],
        'dev': json['dev'] == null ? undefined : json['dev'],
    };
}

export function MessagingSchemaContextToJSON(json: any): MessagingSchemaContext {
    return MessagingSchemaContextToJSONTyped(json, false);
}

export function MessagingSchemaContextToJSONTyped(value?: MessagingSchemaContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'timestamp': value['timestamp'],
        'dev': value['dev'],
    };
}

