/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface MessagingSchemaData
 */
export interface MessagingSchemaData {
    /**
     * The unique identifier of the recommendation profile
     * @type {string}
     * @memberof MessagingSchemaData
     */
    uid: string;
    /**
     * Tag of the messaging recommendation profile the shopper interacted with
     * @type {string}
     * @memberof MessagingSchemaData
     */
    tag: string;
}

/**
 * Check if a given object implements the MessagingSchemaData interface.
 */
export function instanceOfMessagingSchemaData(value: object): value is MessagingSchemaData {
    if (!('uid' in value) || value['uid'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    return true;
}

export function MessagingSchemaDataFromJSON(json: any): MessagingSchemaData {
    return MessagingSchemaDataFromJSONTyped(json, false);
}

export function MessagingSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessagingSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'],
        'tag': json['tag'],
    };
}

export function MessagingSchemaDataToJSON(json: any): MessagingSchemaData {
    return MessagingSchemaDataToJSONTyped(json, false);
}

export function MessagingSchemaDataToJSONTyped(value?: MessagingSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'tag': value['tag'],
    };
}

