/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model404Response
 */
export interface Model404Response {
    /**
     * Data sent but not received due to an error
     * @type {boolean}
     * @memberof Model404Response
     */
    success?: boolean;
    /**
     * Cause of error
     * @type {string}
     * @memberof Model404Response
     */
    error?: string;
    /**
     * Cause of failure(s)
     * @type {Array<string>}
     * @memberof Model404Response
     */
    messages?: Array<string>;
}

/**
 * Check if a given object implements the Model404Response interface.
 */
export function instanceOfModel404Response(value: object): value is Model404Response {
    return true;
}

export function Model404ResponseFromJSON(json: any): Model404Response {
    return Model404ResponseFromJSONTyped(json, false);
}

export function Model404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'messages': json['messages'] == null ? undefined : json['messages'],
    };
}

  export function Model404ResponseToJSON(json: any): Model404Response {
      return Model404ResponseToJSONTyped(json, false);
  }

  export function Model404ResponseToJSONTyped(value?: Model404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'messages': value['messages'],
    };
}

