/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model400Response
 */
export interface Model400Response {
    /**
     * Data sent but not received due to an error
     * @type {boolean}
     * @memberof Model400Response
     */
    success?: boolean;
    /**
     * Cause of error
     * @type {string}
     * @memberof Model400Response
     */
    error?: string;
    /**
     * Cause of failure(s)
     * @type {Array<string>}
     * @memberof Model400Response
     */
    messages?: Array<string>;
    /**
     * Data sent where an error is identified
     * @type {string}
     * @memberof Model400Response
     */
    data?: string;
}

/**
 * Check if a given object implements the Model400Response interface.
 */
export function instanceOfModel400Response(value: object): value is Model400Response {
    return true;
}

export function Model400ResponseFromJSON(json: any): Model400Response {
    return Model400ResponseFromJSONTyped(json, false);
}

export function Model400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'messages': json['messages'] == null ? undefined : json['messages'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

  export function Model400ResponseToJSON(json: any): Model400Response {
      return Model400ResponseToJSONTyped(json, false);
  }

  export function Model400ResponseToJSONTyped(value?: Model400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'messages': value['messages'],
        'data': value['data'],
    };
}

