/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { OrderTransactionSchemaData } from './OrderTransactionSchemaData';
import {
    OrderTransactionSchemaDataFromJSON,
    OrderTransactionSchemaDataFromJSONTyped,
    OrderTransactionSchemaDataToJSON,
    OrderTransactionSchemaDataToJSONTyped,
} from './OrderTransactionSchemaData';

/**
 * 
 * @export
 * @interface OrderTransactionSchema
 */
export interface OrderTransactionSchema {
    /**
     * 
     * @type {Context}
     * @memberof OrderTransactionSchema
     */
    context: Context;
    /**
     * 
     * @type {OrderTransactionSchemaData}
     * @memberof OrderTransactionSchema
     */
    data: OrderTransactionSchemaData;
}

/**
 * Check if a given object implements the OrderTransactionSchema interface.
 */
export function instanceOfOrderTransactionSchema(value: object): value is OrderTransactionSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OrderTransactionSchemaFromJSON(json: any): OrderTransactionSchema {
    return OrderTransactionSchemaFromJSONTyped(json, false);
}

export function OrderTransactionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderTransactionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': OrderTransactionSchemaDataFromJSON(json['data']),
    };
}

export function OrderTransactionSchemaToJSON(json: any): OrderTransactionSchema {
    return OrderTransactionSchemaToJSONTyped(json, false);
}

export function OrderTransactionSchemaToJSONTyped(value?: OrderTransactionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': OrderTransactionSchemaDataToJSON(value['data']),
    };
}

