/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * Event details
 * @export
 * @interface OrderTransactionSchemaData
 */
export interface OrderTransactionSchemaData {
    /**
     * Unique order ID
     * @type {string}
     * @memberof OrderTransactionSchemaData
     */
    orderId: string;
    /**
     * Total order amount before discounts, taxes, and shipping
     * @type {number}
     * @memberof OrderTransactionSchemaData
     */
    transactionTotal: number;
    /**
     * Total order amount including discounts, taxes, and shipping
     * @type {number}
     * @memberof OrderTransactionSchemaData
     */
    total: number;
    /**
     * Value added tax(VAT) rate as a decimal value (e.g. 0.20 for 20%)
     * @type {number}
     * @memberof OrderTransactionSchemaData
     */
    vat?: number;
    /**
     * Customer's shipping address City
     * @type {string}
     * @memberof OrderTransactionSchemaData
     */
    city?: string;
    /**
     * Customer's shipping address State
     * @type {string}
     * @memberof OrderTransactionSchemaData
     */
    state?: string;
    /**
     * Customer's shipping address 2-letter Country Code
     * @type {string}
     * @memberof OrderTransactionSchemaData
     */
    country?: string;
    /**
     * 
     * @type {Array<Product>}
     * @memberof OrderTransactionSchemaData
     */
    results: Array<Product>;
}

/**
 * Check if a given object implements the OrderTransactionSchemaData interface.
 */
export function instanceOfOrderTransactionSchemaData(value: object): value is OrderTransactionSchemaData {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('transactionTotal' in value) || value['transactionTotal'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function OrderTransactionSchemaDataFromJSON(json: any): OrderTransactionSchemaData {
    return OrderTransactionSchemaDataFromJSONTyped(json, false);
}

export function OrderTransactionSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderTransactionSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'transactionTotal': json['transactionTotal'],
        'total': json['total'],
        'vat': json['vat'] == null ? undefined : json['vat'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
    };
}

  export function OrderTransactionSchemaDataToJSON(json: any): OrderTransactionSchemaData {
      return OrderTransactionSchemaDataToJSONTyped(json, false);
  }

  export function OrderTransactionSchemaDataToJSONTyped(value?: OrderTransactionSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'transactionTotal': value['transactionTotal'],
        'total': value['total'],
        'vat': value['vat'],
        'city': value['city'],
        'state': value['state'],
        'country': value['country'],
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
    };
}

