/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contextual information about the event
 * @export
 * @interface PersonalizationLogEventContext
 */
export interface PersonalizationLogEventContext {
    /**
     * RFC3339 formatted timestamp represents time of event
     * @type {string}
     * @memberof PersonalizationLogEventContext
     */
    timestamp: string;
    /**
     * Developer mode flag. If set to `true`, the event data will not populate in reporting
     * @type {boolean}
     * @memberof PersonalizationLogEventContext
     */
    dev?: boolean;
}

/**
 * Check if a given object implements the PersonalizationLogEventContext interface.
 */
export function instanceOfPersonalizationLogEventContext(value: object): value is PersonalizationLogEventContext {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PersonalizationLogEventContextFromJSON(json: any): PersonalizationLogEventContext {
    return PersonalizationLogEventContextFromJSONTyped(json, false);
}

export function PersonalizationLogEventContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalizationLogEventContext {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'dev': json['dev'] == null ? undefined : json['dev'],
    };
}

  export function PersonalizationLogEventContextToJSON(json: any): PersonalizationLogEventContext {
      return PersonalizationLogEventContextToJSONTyped(json, false);
  }

  export function PersonalizationLogEventContextToJSONTyped(value?: PersonalizationLogEventContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'dev': value['dev'],
    };
}

