/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonalizationLogContext
 */
export interface PersonalizationLogContext {
    /**
     * RFC3339 formatted timestamp represents time of event
     * @type {string}
     * @memberof PersonalizationLogContext
     */
    timestamp: string;
    /**
     * Developer mode flag. If set to `true`, the event data will not populate in reporting
     * @type {boolean}
     * @memberof PersonalizationLogContext
     */
    dev?: boolean;
}

/**
 * Check if a given object implements the PersonalizationLogContext interface.
 */
export function instanceOfPersonalizationLogContext(value: object): value is PersonalizationLogContext {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function PersonalizationLogContextFromJSON(json: any): PersonalizationLogContext {
    return PersonalizationLogContextFromJSONTyped(json, false);
}

export function PersonalizationLogContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalizationLogContext {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'],
        'dev': json['dev'] == null ? undefined : json['dev'],
    };
}

export function PersonalizationLogContextToJSON(json: any): PersonalizationLogContext {
    return PersonalizationLogContextToJSONTyped(json, false);
}

export function PersonalizationLogContextToJSONTyped(value?: PersonalizationLogContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'],
        'dev': value['dev'],
    };
}

