/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonalizationLogSchemaData } from './PersonalizationLogSchemaData';
import {
    PersonalizationLogSchemaDataFromJSON,
    PersonalizationLogSchemaDataFromJSONTyped,
    PersonalizationLogSchemaDataToJSON,
    PersonalizationLogSchemaDataToJSONTyped,
} from './PersonalizationLogSchemaData';
import type { PersonalizationLogContext } from './PersonalizationLogContext';
import {
    PersonalizationLogContextFromJSON,
    PersonalizationLogContextFromJSONTyped,
    PersonalizationLogContextToJSON,
    PersonalizationLogContextToJSONTyped,
} from './PersonalizationLogContext';

/**
 * 
 * @export
 * @interface PersonalizationLogSchema
 */
export interface PersonalizationLogSchema {
    /**
     * 
     * @type {PersonalizationLogContext}
     * @memberof PersonalizationLogSchema
     */
    context: PersonalizationLogContext;
    /**
     * 
     * @type {PersonalizationLogSchemaData}
     * @memberof PersonalizationLogSchema
     */
    data: PersonalizationLogSchemaData;
}

/**
 * Check if a given object implements the PersonalizationLogSchema interface.
 */
export function instanceOfPersonalizationLogSchema(value: object): value is PersonalizationLogSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PersonalizationLogSchemaFromJSON(json: any): PersonalizationLogSchema {
    return PersonalizationLogSchemaFromJSONTyped(json, false);
}

export function PersonalizationLogSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalizationLogSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': PersonalizationLogContextFromJSON(json['context']),
        'data': PersonalizationLogSchemaDataFromJSON(json['data']),
    };
}

export function PersonalizationLogSchemaToJSON(json: any): PersonalizationLogSchema {
    return PersonalizationLogSchemaToJSONTyped(json, false);
}

export function PersonalizationLogSchemaToJSONTyped(value?: PersonalizationLogSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': PersonalizationLogContextToJSON(value['context']),
        'data': PersonalizationLogSchemaDataToJSON(value['data']),
    };
}

