/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonalizationLogEventContext } from './PersonalizationLogEventContext';
import {
    PersonalizationLogEventContextFromJSON,
    PersonalizationLogEventContextFromJSONTyped,
    PersonalizationLogEventContextToJSON,
    PersonalizationLogEventContextToJSONTyped,
} from './PersonalizationLogEventContext';
import type { Log } from './Log';
import {
    LogFromJSON,
    LogFromJSONTyped,
    LogToJSON,
    LogToJSONTyped,
} from './Log';

/**
 * 
 * @export
 * @interface PersonalizationLogEvent
 */
export interface PersonalizationLogEvent {
    /**
     * 
     * @type {PersonalizationLogEventContext}
     * @memberof PersonalizationLogEvent
     */
    context: PersonalizationLogEventContext;
    /**
     * 
     * @type {Log}
     * @memberof PersonalizationLogEvent
     */
    data: Log;
}

/**
 * Check if a given object implements the PersonalizationLogEvent interface.
 */
export function instanceOfPersonalizationLogEvent(value: object): value is PersonalizationLogEvent {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PersonalizationLogEventFromJSON(json: any): PersonalizationLogEvent {
    return PersonalizationLogEventFromJSONTyped(json, false);
}

export function PersonalizationLogEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalizationLogEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'context': PersonalizationLogEventContextFromJSON(json['context']),
        'data': LogFromJSON(json['data']),
    };
}

  export function PersonalizationLogEventToJSON(json: any): PersonalizationLogEvent {
      return PersonalizationLogEventToJSONTyped(json, false);
  }

  export function PersonalizationLogEventToJSONTyped(value?: PersonalizationLogEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': PersonalizationLogEventContextToJSON(value['context']),
        'data': LogToJSON(value['data']),
    };
}

