/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Log data about the event
 * @export
 * @interface PersonalizationLogSchemaData
 */
export interface PersonalizationLogSchemaData {
    /**
     * Error message
     * @type {string}
     * @memberof PersonalizationLogSchemaData
     */
    message?: string;
    /**
     * Stack trace of the error
     * @type {string}
     * @memberof PersonalizationLogSchemaData
     */
    stack?: string;
    /**
     * Additional optional error details
     * @type {object}
     * @memberof PersonalizationLogSchemaData
     */
    details?: object;
}

/**
 * Check if a given object implements the PersonalizationLogSchemaData interface.
 */
export function instanceOfPersonalizationLogSchemaData(value: object): value is PersonalizationLogSchemaData {
    return true;
}

export function PersonalizationLogSchemaDataFromJSON(json: any): PersonalizationLogSchemaData {
    return PersonalizationLogSchemaDataFromJSONTyped(json, false);
}

export function PersonalizationLogSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalizationLogSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'stack': json['stack'] == null ? undefined : json['stack'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function PersonalizationLogSchemaDataToJSON(json: any): PersonalizationLogSchemaData {
    return PersonalizationLogSchemaDataToJSONTyped(json, false);
}

export function PersonalizationLogSchemaDataToJSONTyped(value?: PersonalizationLogSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'stack': value['stack'],
        'details': value['details'],
    };
}

