/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { ProductPageviewSchemaData } from './ProductPageviewSchemaData';
import {
    ProductPageviewSchemaDataFromJSON,
    ProductPageviewSchemaDataFromJSONTyped,
    ProductPageviewSchemaDataToJSON,
    ProductPageviewSchemaDataToJSONTyped,
} from './ProductPageviewSchemaData';

/**
 * 
 * @export
 * @interface ProductPageviewSchema
 */
export interface ProductPageviewSchema {
    /**
     * 
     * @type {Context}
     * @memberof ProductPageviewSchema
     */
    context: Context;
    /**
     * 
     * @type {ProductPageviewSchemaData}
     * @memberof ProductPageviewSchema
     */
    data: ProductPageviewSchemaData;
}

/**
 * Check if a given object implements the ProductPageviewSchema interface.
 */
export function instanceOfProductPageviewSchema(value: object): value is ProductPageviewSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ProductPageviewSchemaFromJSON(json: any): ProductPageviewSchema {
    return ProductPageviewSchemaFromJSONTyped(json, false);
}

export function ProductPageviewSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPageviewSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': ProductPageviewSchemaDataFromJSON(json['data']),
    };
}

export function ProductPageviewSchemaToJSON(json: any): ProductPageviewSchema {
    return ProductPageviewSchemaToJSONTyped(json, false);
}

export function ProductPageviewSchemaToJSONTyped(value?: ProductPageviewSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': ProductPageviewSchemaDataToJSON(value['data']),
    };
}

