/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a tracked Searchspring result.
 * @export
 * @interface ProductPageviewSchemaDataResult
 */
export interface ProductPageviewSchemaDataResult {
    /**
     * Unique product identifier of the Searchspring indexed product (also provide `sku`, `childSku`, and `childId` if available)
     * @type {string}
     * @memberof ProductPageviewSchemaDataResult
     */
    uid: string;
    /**
     * Unique product variant identifier
     * @type {string}
     * @memberof ProductPageviewSchemaDataResult
     */
    childUid?: string;
    /**
     * Unique product identifier (also provide `childSku` if available)
     * @type {string}
     * @memberof ProductPageviewSchemaDataResult
     */
    sku?: string;
    /**
     * Unique product variant identifier (also provide `sku` if available)
     * @type {string}
     * @memberof ProductPageviewSchemaDataResult
     */
    childSku?: string;
}

/**
 * Check if a given object implements the ProductPageviewSchemaDataResult interface.
 */
export function instanceOfProductPageviewSchemaDataResult(value: object): value is ProductPageviewSchemaDataResult {
    if (!('uid' in value) || value['uid'] === undefined) return false;
    return true;
}

export function ProductPageviewSchemaDataResultFromJSON(json: any): ProductPageviewSchemaDataResult {
    return ProductPageviewSchemaDataResultFromJSONTyped(json, false);
}

export function ProductPageviewSchemaDataResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPageviewSchemaDataResult {
    if (json == null) {
        return json;
    }
    return {
        
        'uid': json['uid'],
        'childUid': json['childUid'] == null ? undefined : json['childUid'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'childSku': json['childSku'] == null ? undefined : json['childSku'],
    };
}

  export function ProductPageviewSchemaDataResultToJSON(json: any): ProductPageviewSchemaDataResult {
      return ProductPageviewSchemaDataResultToJSONTyped(json, false);
  }

  export function ProductPageviewSchemaDataResultToJSONTyped(value?: ProductPageviewSchemaDataResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'uid': value['uid'],
        'childUid': value['childUid'],
        'sku': value['sku'],
        'childSku': value['childSku'],
    };
}

