/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Describes a tracked Athos Commerce result.
 * @export
 * @interface ProductPageviewSchemaDataResult
 */
export interface ProductPageviewSchemaDataResult {
    /**
     * Unique product identifier of the parent product interacted with
     * @type {string}
     * @memberof ProductPageviewSchemaDataResult
     */
    parentId: string;
    /**
     * Unique product identifier of the product interacted with
     * @type {string}
     * @memberof ProductPageviewSchemaDataResult
     */
    uid: string;
    /**
     * SKU of the product interacted with
     * @type {string}
     * @memberof ProductPageviewSchemaDataResult
     */
    sku?: string;
}

/**
 * Check if a given object implements the ProductPageviewSchemaDataResult interface.
 */
export function instanceOfProductPageviewSchemaDataResult(value: object): value is ProductPageviewSchemaDataResult {
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('uid' in value) || value['uid'] === undefined) return false;
    return true;
}

export function ProductPageviewSchemaDataResultFromJSON(json: any): ProductPageviewSchemaDataResult {
    return ProductPageviewSchemaDataResultFromJSONTyped(json, false);
}

export function ProductPageviewSchemaDataResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPageviewSchemaDataResult {
    if (json == null) {
        return json;
    }
    return {
        
        'parentId': json['parentId'],
        'uid': json['uid'],
        'sku': json['sku'] == null ? undefined : json['sku'],
    };
}

export function ProductPageviewSchemaDataResultToJSON(json: any): ProductPageviewSchemaDataResult {
    return ProductPageviewSchemaDataResultToJSONTyped(json, false);
}

export function ProductPageviewSchemaDataResultToJSONTyped(value?: ProductPageviewSchemaDataResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentId': value['parentId'],
        'uid': value['uid'],
        'sku': value['sku'],
    };
}

