/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.45
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Product details
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * Unique product identifier of the parent product interacted with
     * @type {string}
     * @memberof Product
     */
    parentId: string;
    /**
     * Unique product identifier of the product interacted with
     * @type {string}
     * @memberof Product
     */
    uid: string;
    /**
     * SKU of the product interacted with
     * @type {string}
     * @memberof Product
     */
    sku?: string;
    /**
     * Quantity of the item
     * @type {number}
     * @memberof Product
     */
    qty: number;
    /**
     * Price of individual item
     * @type {number}
     * @memberof Product
     */
    price: number;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('uid' in value) || value['uid'] === undefined) return false;
    if (!('qty' in value) || value['qty'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'parentId': json['parentId'],
        'uid': json['uid'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'qty': json['qty'],
        'price': json['price'],
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Product | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parentId': value['parentId'],
        'uid': value['uid'],
        'sku': value['sku'],
        'qty': value['qty'],
        'price': value['price'],
    };
}

