/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductPageviewSchemaDataResult } from './ProductPageviewSchemaDataResult';
import {
    ProductPageviewSchemaDataResultFromJSON,
    ProductPageviewSchemaDataResultFromJSONTyped,
    ProductPageviewSchemaDataResultToJSON,
    ProductPageviewSchemaDataResultToJSONTyped,
} from './ProductPageviewSchemaDataResult';

/**
 * Event details
 * @export
 * @interface ProductPageviewSchemaData
 */
export interface ProductPageviewSchemaData {
    /**
     * 
     * @type {ProductPageviewSchemaDataResult}
     * @memberof ProductPageviewSchemaData
     */
    result: ProductPageviewSchemaDataResult;
}

/**
 * Check if a given object implements the ProductPageviewSchemaData interface.
 */
export function instanceOfProductPageviewSchemaData(value: object): value is ProductPageviewSchemaData {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ProductPageviewSchemaDataFromJSON(json: any): ProductPageviewSchemaData {
    return ProductPageviewSchemaDataFromJSONTyped(json, false);
}

export function ProductPageviewSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPageviewSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'result': ProductPageviewSchemaDataResultFromJSON(json['result']),
    };
}

export function ProductPageviewSchemaDataToJSON(json: any): ProductPageviewSchemaData {
    return ProductPageviewSchemaDataToJSONTyped(json, false);
}

export function ProductPageviewSchemaDataToJSONTyped(value?: ProductPageviewSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': ProductPageviewSchemaDataResultToJSON(value['result']),
    };
}

