/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BannersInner } from './BannersInner';
import {
    BannersInnerFromJSON,
    BannersInnerFromJSONTyped,
    BannersInnerToJSON,
    BannersInnerToJSONTyped,
} from './BannersInner';
import type { ResultsInner } from './ResultsInner';
import {
    ResultsInnerFromJSON,
    ResultsInnerFromJSONTyped,
    ResultsInnerToJSON,
    ResultsInnerToJSONTyped,
} from './ResultsInner';

/**
 * Event details
 * @export
 * @interface RecommendationsImpressionSchemaData
 */
export interface RecommendationsImpressionSchemaData {
    /**
     * Tag of the personalized recommendation profile the shopper interacted with
     * @type {string}
     * @memberof RecommendationsImpressionSchemaData
     */
    tag: string;
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof RecommendationsImpressionSchemaData
     */
    responseId: string;
    /**
     * List of tracked result(s). An empty array will indicate zero results were returned in the API response.
     * @type {Array<ResultsInner>}
     * @memberof RecommendationsImpressionSchemaData
     */
    results?: Array<ResultsInner>;
    /**
     * List of banners UID's returned in the API response. An empty array will indicate zero banners were returned in the API response.
     * @type {Array<BannersInner>}
     * @memberof RecommendationsImpressionSchemaData
     */
    banners: Array<BannersInner>;
}

/**
 * Check if a given object implements the RecommendationsImpressionSchemaData interface.
 */
export function instanceOfRecommendationsImpressionSchemaData(value: object): value is RecommendationsImpressionSchemaData {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('banners' in value) || value['banners'] === undefined) return false;
    return true;
}

export function RecommendationsImpressionSchemaDataFromJSON(json: any): RecommendationsImpressionSchemaData {
    return RecommendationsImpressionSchemaDataFromJSONTyped(json, false);
}

export function RecommendationsImpressionSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsImpressionSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'responseId': json['responseId'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ResultsInnerFromJSON)),
        'banners': ((json['banners'] as Array<any>).map(BannersInnerFromJSON)),
    };
}

export function RecommendationsImpressionSchemaDataToJSON(json: any): RecommendationsImpressionSchemaData {
    return RecommendationsImpressionSchemaDataToJSONTyped(json, false);
}

export function RecommendationsImpressionSchemaDataToJSONTyped(value?: RecommendationsImpressionSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'responseId': value['responseId'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ResultsInnerToJSON)),
        'banners': ((value['banners'] as Array<any>).map(BannersInnerToJSON)),
    };
}

