/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * Event details
 * @export
 * @interface RecommendationsAddtocartSchemaData
 */
export interface RecommendationsAddtocartSchemaData {
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof RecommendationsAddtocartSchemaData
     */
    responseId: string;
    /**
     * Tag of the personalized recommendation profile the shopper interacted with
     * @type {string}
     * @memberof RecommendationsAddtocartSchemaData
     */
    tag: string;
    /**
     * Products added to the cart
     * @type {Array<Product>}
     * @memberof RecommendationsAddtocartSchemaData
     */
    results: Array<Product>;
}

/**
 * Check if a given object implements the RecommendationsAddtocartSchemaData interface.
 */
export function instanceOfRecommendationsAddtocartSchemaData(value: object): value is RecommendationsAddtocartSchemaData {
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function RecommendationsAddtocartSchemaDataFromJSON(json: any): RecommendationsAddtocartSchemaData {
    return RecommendationsAddtocartSchemaDataFromJSONTyped(json, false);
}

export function RecommendationsAddtocartSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsAddtocartSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'responseId': json['responseId'],
        'tag': json['tag'],
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
    };
}

export function RecommendationsAddtocartSchemaDataToJSON(json: any): RecommendationsAddtocartSchemaData {
    return RecommendationsAddtocartSchemaDataToJSONTyped(json, false);
}

export function RecommendationsAddtocartSchemaDataToJSONTyped(value?: RecommendationsAddtocartSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseId': value['responseId'],
        'tag': value['tag'],
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
    };
}

