/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { RecommendationsClickthroughSchemaData } from './RecommendationsClickthroughSchemaData';
import {
    RecommendationsClickthroughSchemaDataFromJSON,
    RecommendationsClickthroughSchemaDataFromJSONTyped,
    RecommendationsClickthroughSchemaDataToJSON,
    RecommendationsClickthroughSchemaDataToJSONTyped,
} from './RecommendationsClickthroughSchemaData';

/**
 * 
 * @export
 * @interface RecommendationsClickthroughSchema
 */
export interface RecommendationsClickthroughSchema {
    /**
     * 
     * @type {Context}
     * @memberof RecommendationsClickthroughSchema
     */
    context: Context;
    /**
     * 
     * @type {RecommendationsClickthroughSchemaData}
     * @memberof RecommendationsClickthroughSchema
     */
    data: RecommendationsClickthroughSchemaData;
}

/**
 * Check if a given object implements the RecommendationsClickthroughSchema interface.
 */
export function instanceOfRecommendationsClickthroughSchema(value: object): value is RecommendationsClickthroughSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RecommendationsClickthroughSchemaFromJSON(json: any): RecommendationsClickthroughSchema {
    return RecommendationsClickthroughSchemaFromJSONTyped(json, false);
}

export function RecommendationsClickthroughSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsClickthroughSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': RecommendationsClickthroughSchemaDataFromJSON(json['data']),
    };
}

export function RecommendationsClickthroughSchemaToJSON(json: any): RecommendationsClickthroughSchema {
    return RecommendationsClickthroughSchemaToJSONTyped(json, false);
}

export function RecommendationsClickthroughSchemaToJSONTyped(value?: RecommendationsClickthroughSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': RecommendationsClickthroughSchemaDataToJSON(value['data']),
    };
}

