/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { RecommendationsRenderSchemaData } from './RecommendationsRenderSchemaData';
import {
    RecommendationsRenderSchemaDataFromJSON,
    RecommendationsRenderSchemaDataFromJSONTyped,
    RecommendationsRenderSchemaDataToJSON,
    RecommendationsRenderSchemaDataToJSONTyped,
} from './RecommendationsRenderSchemaData';

/**
 * 
 * @export
 * @interface RecommendationsRenderSchema
 */
export interface RecommendationsRenderSchema {
    /**
     * 
     * @type {Context}
     * @memberof RecommendationsRenderSchema
     */
    context: Context;
    /**
     * 
     * @type {RecommendationsRenderSchemaData}
     * @memberof RecommendationsRenderSchema
     */
    data: RecommendationsRenderSchemaData;
}

/**
 * Check if a given object implements the RecommendationsRenderSchema interface.
 */
export function instanceOfRecommendationsRenderSchema(value: object): value is RecommendationsRenderSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RecommendationsRenderSchemaFromJSON(json: any): RecommendationsRenderSchema {
    return RecommendationsRenderSchemaFromJSONTyped(json, false);
}

export function RecommendationsRenderSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsRenderSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': RecommendationsRenderSchemaDataFromJSON(json['data']),
    };
}

export function RecommendationsRenderSchemaToJSON(json: any): RecommendationsRenderSchema {
    return RecommendationsRenderSchemaToJSONTyped(json, false);
}

export function RecommendationsRenderSchemaToJSONTyped(value?: RecommendationsRenderSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': RecommendationsRenderSchemaDataToJSON(value['data']),
    };
}

