/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
    ItemToJSONTyped,
} from './Item';

/**
 * Event details
 * @export
 * @interface RecommendationsSchemaData
 */
export interface RecommendationsSchemaData {
    /**
     * Tag of the personalized recommendation profile the shopper interacted with
     * @type {string}
     * @memberof RecommendationsSchemaData
     */
    tag: string;
    /**
     * List of tracked Searchspring result(s). An empty array will indicate zero results were returned in the API response.
     * @type {Array<Item>}
     * @memberof RecommendationsSchemaData
     */
    results: Array<Item>;
}

/**
 * Check if a given object implements the RecommendationsSchemaData interface.
 */
export function instanceOfRecommendationsSchemaData(value: object): value is RecommendationsSchemaData {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function RecommendationsSchemaDataFromJSON(json: any): RecommendationsSchemaData {
    return RecommendationsSchemaDataFromJSONTyped(json, false);
}

export function RecommendationsSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'results': ((json['results'] as Array<any>).map(ItemFromJSON)),
    };
}

  export function RecommendationsSchemaDataToJSON(json: any): RecommendationsSchemaData {
      return RecommendationsSchemaDataToJSONTyped(json, false);
  }

  export function RecommendationsSchemaDataToJSONTyped(value?: RecommendationsSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'results': ((value['results'] as Array<any>).map(ItemToJSON)),
    };
}

