/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { RecommendationsAddtocartSchemaData } from './RecommendationsAddtocartSchemaData';
import {
    RecommendationsAddtocartSchemaDataFromJSON,
    RecommendationsAddtocartSchemaDataFromJSONTyped,
    RecommendationsAddtocartSchemaDataToJSON,
    RecommendationsAddtocartSchemaDataToJSONTyped,
} from './RecommendationsAddtocartSchemaData';

/**
 * 
 * @export
 * @interface RecommendationsAddtocartSchema
 */
export interface RecommendationsAddtocartSchema {
    /**
     * 
     * @type {Context}
     * @memberof RecommendationsAddtocartSchema
     */
    context: Context;
    /**
     * 
     * @type {RecommendationsAddtocartSchemaData}
     * @memberof RecommendationsAddtocartSchema
     */
    data: RecommendationsAddtocartSchemaData;
}

/**
 * Check if a given object implements the RecommendationsAddtocartSchema interface.
 */
export function instanceOfRecommendationsAddtocartSchema(value: object): value is RecommendationsAddtocartSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RecommendationsAddtocartSchemaFromJSON(json: any): RecommendationsAddtocartSchema {
    return RecommendationsAddtocartSchemaFromJSONTyped(json, false);
}

export function RecommendationsAddtocartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsAddtocartSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': RecommendationsAddtocartSchemaDataFromJSON(json['data']),
    };
}

export function RecommendationsAddtocartSchemaToJSON(json: any): RecommendationsAddtocartSchema {
    return RecommendationsAddtocartSchemaToJSONTyped(json, false);
}

export function RecommendationsAddtocartSchemaToJSONTyped(value?: RecommendationsAddtocartSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': RecommendationsAddtocartSchemaDataToJSON(value['data']),
    };
}

