/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { RecommendationsSchemaData } from './RecommendationsSchemaData';
import {
    RecommendationsSchemaDataFromJSON,
    RecommendationsSchemaDataFromJSONTyped,
    RecommendationsSchemaDataToJSON,
    RecommendationsSchemaDataToJSONTyped,
} from './RecommendationsSchemaData';

/**
 * 
 * @export
 * @interface RecommendationsSchema
 */
export interface RecommendationsSchema {
    /**
     * 
     * @type {Context}
     * @memberof RecommendationsSchema
     */
    context: Context;
    /**
     * 
     * @type {RecommendationsSchemaData}
     * @memberof RecommendationsSchema
     */
    data: RecommendationsSchemaData;
}

/**
 * Check if a given object implements the RecommendationsSchema interface.
 */
export function instanceOfRecommendationsSchema(value: object): value is RecommendationsSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RecommendationsSchemaFromJSON(json: any): RecommendationsSchema {
    return RecommendationsSchemaFromJSONTyped(json, false);
}

export function RecommendationsSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': RecommendationsSchemaDataFromJSON(json['data']),
    };
}

  export function RecommendationsSchemaToJSON(json: any): RecommendationsSchema {
      return RecommendationsSchemaToJSONTyped(json, false);
  }

  export function RecommendationsSchemaToJSONTyped(value?: RecommendationsSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': RecommendationsSchemaDataToJSON(value['data']),
    };
}

