/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { RecommendationsImpressionSchemaData } from './RecommendationsImpressionSchemaData';
import {
    RecommendationsImpressionSchemaDataFromJSON,
    RecommendationsImpressionSchemaDataFromJSONTyped,
    RecommendationsImpressionSchemaDataToJSON,
    RecommendationsImpressionSchemaDataToJSONTyped,
} from './RecommendationsImpressionSchemaData';

/**
 * 
 * @export
 * @interface RecommendationsImpressionSchema
 */
export interface RecommendationsImpressionSchema {
    /**
     * 
     * @type {Context}
     * @memberof RecommendationsImpressionSchema
     */
    context: Context;
    /**
     * 
     * @type {RecommendationsImpressionSchemaData}
     * @memberof RecommendationsImpressionSchema
     */
    data: RecommendationsImpressionSchemaData;
}

/**
 * Check if a given object implements the RecommendationsImpressionSchema interface.
 */
export function instanceOfRecommendationsImpressionSchema(value: object): value is RecommendationsImpressionSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RecommendationsImpressionSchemaFromJSON(json: any): RecommendationsImpressionSchema {
    return RecommendationsImpressionSchemaFromJSONTyped(json, false);
}

export function RecommendationsImpressionSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsImpressionSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': RecommendationsImpressionSchemaDataFromJSON(json['data']),
    };
}

export function RecommendationsImpressionSchemaToJSON(json: any): RecommendationsImpressionSchema {
    return RecommendationsImpressionSchemaToJSONTyped(json, false);
}

export function RecommendationsImpressionSchemaToJSONTyped(value?: RecommendationsImpressionSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': RecommendationsImpressionSchemaDataToJSON(value['data']),
    };
}

