/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface RecommendationsRenderSchemaData
 */
export interface RecommendationsRenderSchemaData {
    /**
     * Tag of the personalized recommendation profile the shopper interacted with
     * @type {string}
     * @memberof RecommendationsRenderSchemaData
     */
    tag: string;
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof RecommendationsRenderSchemaData
     */
    responseId: string;
}

/**
 * Check if a given object implements the RecommendationsRenderSchemaData interface.
 */
export function instanceOfRecommendationsRenderSchemaData(value: object): value is RecommendationsRenderSchemaData {
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    return true;
}

export function RecommendationsRenderSchemaDataFromJSON(json: any): RecommendationsRenderSchemaData {
    return RecommendationsRenderSchemaDataFromJSONTyped(json, false);
}

export function RecommendationsRenderSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecommendationsRenderSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'responseId': json['responseId'],
    };
}

export function RecommendationsRenderSchemaDataToJSON(json: any): RecommendationsRenderSchemaData {
    return RecommendationsRenderSchemaDataToJSONTyped(json, false);
}

export function RecommendationsRenderSchemaDataToJSONTyped(value?: RecommendationsRenderSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'responseId': value['responseId'],
    };
}

