/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface RedirectSchemaData
 */
export interface RedirectSchemaData {
    /**
     * Redirect URL returned as `merchandising.redirect` from Search API if a configured redirect is triggered.
     * @type {string}
     * @memberof RedirectSchemaData
     */
    redirect: string;
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof RedirectSchemaData
     */
    responseId: string;
}

/**
 * Check if a given object implements the RedirectSchemaData interface.
 */
export function instanceOfRedirectSchemaData(value: object): value is RedirectSchemaData {
    if (!('redirect' in value) || value['redirect'] === undefined) return false;
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    return true;
}

export function RedirectSchemaDataFromJSON(json: any): RedirectSchemaData {
    return RedirectSchemaDataFromJSONTyped(json, false);
}

export function RedirectSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedirectSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'redirect': json['redirect'],
        'responseId': json['responseId'],
    };
}

export function RedirectSchemaDataToJSON(json: any): RedirectSchemaData {
    return RedirectSchemaDataToJSONTyped(json, false);
}

export function RedirectSchemaDataToJSONTyped(value?: RedirectSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect': value['redirect'],
        'responseId': value['responseId'],
    };
}

