/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { RedirectSchemaData } from './RedirectSchemaData';
import {
    RedirectSchemaDataFromJSON,
    RedirectSchemaDataFromJSONTyped,
    RedirectSchemaDataToJSON,
    RedirectSchemaDataToJSONTyped,
} from './RedirectSchemaData';

/**
 * 
 * @export
 * @interface RedirectSchema
 */
export interface RedirectSchema {
    /**
     * 
     * @type {Context}
     * @memberof RedirectSchema
     */
    context: Context;
    /**
     * 
     * @type {RedirectSchemaData}
     * @memberof RedirectSchema
     */
    data: RedirectSchemaData;
}

/**
 * Check if a given object implements the RedirectSchema interface.
 */
export function instanceOfRedirectSchema(value: object): value is RedirectSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RedirectSchemaFromJSON(json: any): RedirectSchema {
    return RedirectSchemaFromJSONTyped(json, false);
}

export function RedirectSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedirectSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': RedirectSchemaDataFromJSON(json['data']),
    };
}

export function RedirectSchemaToJSON(json: any): RedirectSchema {
    return RedirectSchemaToJSONTyped(json, false);
}

export function RedirectSchemaToJSONTyped(value?: RedirectSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': RedirectSchemaDataToJSON(value['data']),
    };
}

