/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface RenderSchemaData
 */
export interface RenderSchemaData {
    /**
     * Unique ID returned in each API response
     * @type {string}
     * @memberof RenderSchemaData
     */
    responseId: string;
}

/**
 * Check if a given object implements the RenderSchemaData interface.
 */
export function instanceOfRenderSchemaData(value: object): value is RenderSchemaData {
    if (!('responseId' in value) || value['responseId'] === undefined) return false;
    return true;
}

export function RenderSchemaDataFromJSON(json: any): RenderSchemaData {
    return RenderSchemaDataFromJSONTyped(json, false);
}

export function RenderSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'responseId': json['responseId'],
    };
}

export function RenderSchemaDataToJSON(json: any): RenderSchemaData {
    return RenderSchemaDataToJSONTyped(json, false);
}

export function RenderSchemaDataToJSONTyped(value?: RenderSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responseId': value['responseId'],
    };
}

