/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { RenderSchemaData } from './RenderSchemaData';
import {
    RenderSchemaDataFromJSON,
    RenderSchemaDataFromJSONTyped,
    RenderSchemaDataToJSON,
    RenderSchemaDataToJSONTyped,
} from './RenderSchemaData';

/**
 * 
 * @export
 * @interface RenderSchema
 */
export interface RenderSchema {
    /**
     * 
     * @type {Context}
     * @memberof RenderSchema
     */
    context: Context;
    /**
     * 
     * @type {RenderSchemaData}
     * @memberof RenderSchema
     */
    data: RenderSchemaData;
}

/**
 * Check if a given object implements the RenderSchema interface.
 */
export function instanceOfRenderSchema(value: object): value is RenderSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RenderSchemaFromJSON(json: any): RenderSchema {
    return RenderSchemaFromJSONTyped(json, false);
}

export function RenderSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': RenderSchemaDataFromJSON(json['data']),
    };
}

export function RenderSchemaToJSON(json: any): RenderSchema {
    return RenderSchemaToJSONTyped(json, false);
}

export function RenderSchemaToJSONTyped(value?: RenderSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': RenderSchemaDataToJSON(value['data']),
    };
}

