/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ResultProduct } from './ResultProduct';
import {
    instanceOfResultProduct,
    ResultProductFromJSON,
    ResultProductFromJSONTyped,
    ResultProductToJSON,
} from './ResultProduct';
import type { ResultResultBanner } from './ResultResultBanner';
import {
    instanceOfResultResultBanner,
    ResultResultBannerFromJSON,
    ResultResultBannerFromJSONTyped,
    ResultResultBannerToJSON,
} from './ResultResultBanner';

/**
 * @type ResultsInner
 * 
 * @export
 */
export type ResultsInner = ResultProduct | ResultResultBanner;

export function ResultsInnerFromJSON(json: any): ResultsInner {
    return ResultsInnerFromJSONTyped(json, false);
}

export function ResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultsInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfResultProduct(json)) {
        return ResultProductFromJSONTyped(json, true);
    }
    if (instanceOfResultResultBanner(json)) {
        return ResultResultBannerFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ResultsInnerToJSON(json: any): any {
    return ResultsInnerToJSONTyped(json, false);
}

export function ResultsInnerToJSONTyped(value?: ResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfResultProduct(value)) {
        return ResultProductToJSON(value as ResultProduct);
    }
    if (instanceOfResultResultBanner(value)) {
        return ResultResultBannerToJSON(value as ResultResultBanner);
    }
    return {};
}

