/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultProductType } from './ResultProductType';
import {
    ResultProductTypeFromJSON,
    ResultProductTypeFromJSONTyped,
    ResultProductTypeToJSON,
    ResultProductTypeToJSONTyped,
} from './ResultProductType';

/**
 * Describes a tracked result.
 * @export
 * @interface ResultProduct
 */
export interface ResultProduct {
    /**
     * 
     * @type {ResultProductType}
     * @memberof ResultProduct
     */
    type: ResultProductType;
    /**
     * Unique product identifier of the parent product interacted with
     * @type {string}
     * @memberof ResultProduct
     */
    parentId: string;
    /**
     * Unique product identifier of the product interacted with
     * @type {string}
     * @memberof ResultProduct
     */
    uid: string;
    /**
     * SKU of the product interacted with
     * @type {string}
     * @memberof ResultProduct
     */
    sku?: string;
}



/**
 * Check if a given object implements the ResultProduct interface.
 */
export function instanceOfResultProduct(value: object): value is ResultProduct {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('parentId' in value) || value['parentId'] === undefined) return false;
    if (!('uid' in value) || value['uid'] === undefined) return false;
    return true;
}

export function ResultProductFromJSON(json: any): ResultProduct {
    return ResultProductFromJSONTyped(json, false);
}

export function ResultProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ResultProductTypeFromJSON(json['type']),
        'parentId': json['parentId'],
        'uid': json['uid'],
        'sku': json['sku'] == null ? undefined : json['sku'],
    };
}

export function ResultProductToJSON(json: any): ResultProduct {
    return ResultProductToJSONTyped(json, false);
}

export function ResultProductToJSONTyped(value?: ResultProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ResultProductTypeToJSON(value['type']),
        'parentId': value['parentId'],
        'uid': value['uid'],
        'sku': value['sku'],
    };
}

