/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the type of item tracked.
 * @export
 */
export const ResultProductType = {
    Product: 'product',
    Banner: 'banner'
} as const;
export type ResultProductType = typeof ResultProductType[keyof typeof ResultProductType];


export function instanceOfResultProductType(value: any): boolean {
    for (const key in ResultProductType) {
        if (Object.prototype.hasOwnProperty.call(ResultProductType, key)) {
            if (ResultProductType[key as keyof typeof ResultProductType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResultProductTypeFromJSON(json: any): ResultProductType {
    return ResultProductTypeFromJSONTyped(json, false);
}

export function ResultProductTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultProductType {
    return json as ResultProductType;
}

export function ResultProductTypeToJSON(value?: ResultProductType | null): any {
    return value as any;
}

export function ResultProductTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ResultProductType {
    return value as ResultProductType;
}

