/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultProductType } from './ResultProductType';
import {
    ResultProductTypeFromJSON,
    ResultProductTypeFromJSONTyped,
    ResultProductTypeToJSON,
    ResultProductTypeToJSONTyped,
} from './ResultProductType';

/**
 * Describes a tracked inline banner.
 * @export
 * @interface ResultResultBanner
 */
export interface ResultResultBanner {
    /**
     * 
     * @type {ResultProductType}
     * @memberof ResultResultBanner
     */
    type: ResultProductType;
    /**
     * Unique product identifier of the product interacted with
     * @type {string}
     * @memberof ResultResultBanner
     */
    uid: string;
}



/**
 * Check if a given object implements the ResultResultBanner interface.
 */
export function instanceOfResultResultBanner(value: object): value is ResultResultBanner {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('uid' in value) || value['uid'] === undefined) return false;
    return true;
}

export function ResultResultBannerFromJSON(json: any): ResultResultBanner {
    return ResultResultBannerFromJSONTyped(json, false);
}

export function ResultResultBannerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultResultBanner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ResultProductTypeFromJSON(json['type']),
        'uid': json['uid'],
    };
}

export function ResultResultBannerToJSON(json: any): ResultResultBanner {
    return ResultResultBannerToJSONTyped(json, false);
}

export function ResultResultBannerToJSONTyped(value?: ResultResultBanner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ResultProductTypeToJSON(value['type']),
        'uid': value['uid'],
    };
}

