/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { SearchAddtocartSchemaData } from './SearchAddtocartSchemaData';
import {
    SearchAddtocartSchemaDataFromJSON,
    SearchAddtocartSchemaDataFromJSONTyped,
    SearchAddtocartSchemaDataToJSON,
    SearchAddtocartSchemaDataToJSONTyped,
} from './SearchAddtocartSchemaData';

/**
 * 
 * @export
 * @interface SearchAddtocartSchema
 */
export interface SearchAddtocartSchema {
    /**
     * 
     * @type {Context}
     * @memberof SearchAddtocartSchema
     */
    context: Context;
    /**
     * 
     * @type {SearchAddtocartSchemaData}
     * @memberof SearchAddtocartSchema
     */
    data: SearchAddtocartSchemaData;
}

/**
 * Check if a given object implements the SearchAddtocartSchema interface.
 */
export function instanceOfSearchAddtocartSchema(value: object): value is SearchAddtocartSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SearchAddtocartSchemaFromJSON(json: any): SearchAddtocartSchema {
    return SearchAddtocartSchemaFromJSONTyped(json, false);
}

export function SearchAddtocartSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAddtocartSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': SearchAddtocartSchemaDataFromJSON(json['data']),
    };
}

  export function SearchAddtocartSchemaToJSON(json: any): SearchAddtocartSchema {
      return SearchAddtocartSchemaToJSONTyped(json, false);
  }

  export function SearchAddtocartSchemaToJSONTyped(value?: SearchAddtocartSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': SearchAddtocartSchemaDataToJSON(value['data']),
    };
}

