/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner } from './CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner';
import {
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSON,
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSONTyped,
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSON,
    CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSONTyped,
} from './CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner';

/**
 * Merchandising data returned from the Search API
 * @export
 * @interface SearchAddtocartSchemaDataMerchandising
 */
export interface SearchAddtocartSchemaDataMerchandising {
    /**
     * Redirect URL returned as `merchandising.redirect` from Search API if a Searchspring configured redirect is triggered.
     * @type {string}
     * @memberof SearchAddtocartSchemaDataMerchandising
     */
    redirect?: string;
    /**
     * Personalized value returned as `merchandising.personalized` from Search API
     * @type {boolean}
     * @memberof SearchAddtocartSchemaDataMerchandising
     */
    personalized?: SearchAddtocartSchemaDataMerchandisingPersonalizedEnum;
    /**
     * List of triggered campaigns returned as `merchandising.triggeredCampaigns` from the Search API
     * @type {Array<CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner>}
     * @memberof SearchAddtocartSchemaDataMerchandising
     */
    triggeredCampaigns?: Array<CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInner>;
}


/**
 * @export
 */
export const SearchAddtocartSchemaDataMerchandisingPersonalizedEnum = {
    True: true,
    False: false
} as const;
export type SearchAddtocartSchemaDataMerchandisingPersonalizedEnum = typeof SearchAddtocartSchemaDataMerchandisingPersonalizedEnum[keyof typeof SearchAddtocartSchemaDataMerchandisingPersonalizedEnum];


/**
 * Check if a given object implements the SearchAddtocartSchemaDataMerchandising interface.
 */
export function instanceOfSearchAddtocartSchemaDataMerchandising(value: object): value is SearchAddtocartSchemaDataMerchandising {
    return true;
}

export function SearchAddtocartSchemaDataMerchandisingFromJSON(json: any): SearchAddtocartSchemaDataMerchandising {
    return SearchAddtocartSchemaDataMerchandisingFromJSONTyped(json, false);
}

export function SearchAddtocartSchemaDataMerchandisingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchAddtocartSchemaDataMerchandising {
    if (json == null) {
        return json;
    }
    return {
        
        'redirect': json['redirect'] == null ? undefined : json['redirect'],
        'personalized': json['personalized'] == null ? undefined : json['personalized'],
        'triggeredCampaigns': json['triggeredCampaigns'] == null ? undefined : ((json['triggeredCampaigns'] as Array<any>).map(CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerFromJSON)),
    };
}

  export function SearchAddtocartSchemaDataMerchandisingToJSON(json: any): SearchAddtocartSchemaDataMerchandising {
      return SearchAddtocartSchemaDataMerchandisingToJSONTyped(json, false);
  }

  export function SearchAddtocartSchemaDataMerchandisingToJSONTyped(value?: SearchAddtocartSchemaDataMerchandising | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect': value['redirect'],
        'personalized': value['personalized'],
        'triggeredCampaigns': value['triggeredCampaigns'] == null ? undefined : ((value['triggeredCampaigns'] as Array<any>).map(CategoryAddtocartSchemaDataMerchandisingTriggeredCampaignsInnerToJSON)),
    };
}

