/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { SearchSchemaData } from './SearchSchemaData';
import {
    SearchSchemaDataFromJSON,
    SearchSchemaDataFromJSONTyped,
    SearchSchemaDataToJSON,
    SearchSchemaDataToJSONTyped,
} from './SearchSchemaData';

/**
 * 
 * @export
 * @interface SearchSchema
 */
export interface SearchSchema {
    /**
     * 
     * @type {Context}
     * @memberof SearchSchema
     */
    context: Context;
    /**
     * 
     * @type {SearchSchemaData}
     * @memberof SearchSchema
     */
    data: SearchSchemaData;
}

/**
 * Check if a given object implements the SearchSchema interface.
 */
export function instanceOfSearchSchema(value: object): value is SearchSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SearchSchemaFromJSON(json: any): SearchSchema {
    return SearchSchemaFromJSONTyped(json, false);
}

export function SearchSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': SearchSchemaDataFromJSON(json['data']),
    };
}

  export function SearchSchemaToJSON(json: any): SearchSchema {
      return SearchSchemaToJSONTyped(json, false);
  }

  export function SearchSchemaToJSONTyped(value?: SearchSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': SearchSchemaDataToJSON(value['data']),
    };
}

