/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Item } from './Item';
import {
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
    ItemToJSONTyped,
} from './Item';
import type { AutocompleteAddtocartSchemaDataBgfilterInner } from './AutocompleteAddtocartSchemaDataBgfilterInner';
import {
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSON,
    AutocompleteAddtocartSchemaDataBgfilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataBgfilterInner';
import type { AutocompleteAddtocartSchemaDataSortInner } from './AutocompleteAddtocartSchemaDataSortInner';
import {
    AutocompleteAddtocartSchemaDataSortInnerFromJSON,
    AutocompleteAddtocartSchemaDataSortInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataSortInnerToJSON,
    AutocompleteAddtocartSchemaDataSortInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataSortInner';
import type { SearchAddtocartSchemaDataMerchandising } from './SearchAddtocartSchemaDataMerchandising';
import {
    SearchAddtocartSchemaDataMerchandisingFromJSON,
    SearchAddtocartSchemaDataMerchandisingFromJSONTyped,
    SearchAddtocartSchemaDataMerchandisingToJSON,
    SearchAddtocartSchemaDataMerchandisingToJSONTyped,
} from './SearchAddtocartSchemaDataMerchandising';
import type { CategoryAddtocartSchemaDataPagination } from './CategoryAddtocartSchemaDataPagination';
import {
    CategoryAddtocartSchemaDataPaginationFromJSON,
    CategoryAddtocartSchemaDataPaginationFromJSONTyped,
    CategoryAddtocartSchemaDataPaginationToJSON,
    CategoryAddtocartSchemaDataPaginationToJSONTyped,
} from './CategoryAddtocartSchemaDataPagination';
import type { AutocompleteAddtocartSchemaDataFilterInner } from './AutocompleteAddtocartSchemaDataFilterInner';
import {
    AutocompleteAddtocartSchemaDataFilterInnerFromJSON,
    AutocompleteAddtocartSchemaDataFilterInnerFromJSONTyped,
    AutocompleteAddtocartSchemaDataFilterInnerToJSON,
    AutocompleteAddtocartSchemaDataFilterInnerToJSONTyped,
} from './AutocompleteAddtocartSchemaDataFilterInner';

/**
 * Event details
 * @export
 * @interface SearchSchemaData
 */
export interface SearchSchemaData {
    /**
     * Search query passed as the `q` query string parameter to the Search API. **If an empty string is passed, will indicate a blank search was submitted.**
     * @type {string}
     * @memberof SearchSchemaData
     */
    q: string;
    /**
     * If spell correction occurs, value will be `query.correctedQuery` from the Search API
     * @type {string}
     * @memberof SearchSchemaData
     */
    correctedQuery?: string;
    /**
     * If search API response returns `didYouMean`, value must be `didYouMean.query`
     * @type {string}
     * @memberof SearchSchemaData
     */
    didYouMean?: string;
    /**
     * Refined query passed as the `rq` query string parameter to the Autocomplete API. This should be omitted if search within search results is not implemented.
     * @type {string}
     * @memberof SearchSchemaData
     */
    rq?: string;
    /**
     * Indicates the type of search matching that was required for this search, returned as `query.matchType` from Search API
     * @type {string}
     * @memberof SearchSchemaData
     */
    matchType: string;
    /**
     * List of active background filters passed to the Search API
     * @type {Array<AutocompleteAddtocartSchemaDataBgfilterInner>}
     * @memberof SearchSchemaData
     */
    bgfilter?: Array<AutocompleteAddtocartSchemaDataBgfilterInner>;
    /**
     * List of active filters passed to the Search API
     * @type {Array<AutocompleteAddtocartSchemaDataFilterInner>}
     * @memberof SearchSchemaData
     */
    filter?: Array<AutocompleteAddtocartSchemaDataFilterInner>;
    /**
     * List of active sorts passed to the Autocomplete API
     * @type {Array<AutocompleteAddtocartSchemaDataSortInner>}
     * @memberof SearchSchemaData
     */
    sort?: Array<AutocompleteAddtocartSchemaDataSortInner>;
    /**
     * 
     * @type {CategoryAddtocartSchemaDataPagination}
     * @memberof SearchSchemaData
     */
    pagination: CategoryAddtocartSchemaDataPagination;
    /**
     * 
     * @type {SearchAddtocartSchemaDataMerchandising}
     * @memberof SearchSchemaData
     */
    merchandising?: SearchAddtocartSchemaDataMerchandising;
    /**
     * List of tracked Searchspring result(s). An empty array will indicate zero results were returned in the API response.
     * @type {Array<Item>}
     * @memberof SearchSchemaData
     */
    results: Array<Item>;
}

/**
 * Check if a given object implements the SearchSchemaData interface.
 */
export function instanceOfSearchSchemaData(value: object): value is SearchSchemaData {
    if (!('q' in value) || value['q'] === undefined) return false;
    if (!('matchType' in value) || value['matchType'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function SearchSchemaDataFromJSON(json: any): SearchSchemaData {
    return SearchSchemaDataFromJSONTyped(json, false);
}

export function SearchSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'q': json['q'],
        'correctedQuery': json['correctedQuery'] == null ? undefined : json['correctedQuery'],
        'didYouMean': json['didYouMean'] == null ? undefined : json['didYouMean'],
        'rq': json['rq'] == null ? undefined : json['rq'],
        'matchType': json['matchType'],
        'bgfilter': json['bgfilter'] == null ? undefined : ((json['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerFromJSON)),
        'filter': json['filter'] == null ? undefined : ((json['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerFromJSON)),
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerFromJSON)),
        'pagination': CategoryAddtocartSchemaDataPaginationFromJSON(json['pagination']),
        'merchandising': json['merchandising'] == null ? undefined : SearchAddtocartSchemaDataMerchandisingFromJSON(json['merchandising']),
        'results': ((json['results'] as Array<any>).map(ItemFromJSON)),
    };
}

  export function SearchSchemaDataToJSON(json: any): SearchSchemaData {
      return SearchSchemaDataToJSONTyped(json, false);
  }

  export function SearchSchemaDataToJSONTyped(value?: SearchSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'q': value['q'],
        'correctedQuery': value['correctedQuery'],
        'didYouMean': value['didYouMean'],
        'rq': value['rq'],
        'matchType': value['matchType'],
        'bgfilter': value['bgfilter'] == null ? undefined : ((value['bgfilter'] as Array<any>).map(AutocompleteAddtocartSchemaDataBgfilterInnerToJSON)),
        'filter': value['filter'] == null ? undefined : ((value['filter'] as Array<any>).map(AutocompleteAddtocartSchemaDataFilterInnerToJSON)),
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(AutocompleteAddtocartSchemaDataSortInnerToJSON)),
        'pagination': CategoryAddtocartSchemaDataPaginationToJSON(value['pagination']),
        'merchandising': SearchAddtocartSchemaDataMerchandisingToJSON(value['merchandising']),
        'results': ((value['results'] as Array<any>).map(ItemToJSON)),
    };
}

