/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Event details
 * @export
 * @interface SearchRedirectSchemaData
 */
export interface SearchRedirectSchemaData {
    /**
     * Value returned as `merchandising.redirect` from Search API if a Searchspring configured redirect is triggered.
     * @type {string}
     * @memberof SearchRedirectSchemaData
     */
    redirect: string;
}

/**
 * Check if a given object implements the SearchRedirectSchemaData interface.
 */
export function instanceOfSearchRedirectSchemaData(value: object): value is SearchRedirectSchemaData {
    if (!('redirect' in value) || value['redirect'] === undefined) return false;
    return true;
}

export function SearchRedirectSchemaDataFromJSON(json: any): SearchRedirectSchemaData {
    return SearchRedirectSchemaDataFromJSONTyped(json, false);
}

export function SearchRedirectSchemaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRedirectSchemaData {
    if (json == null) {
        return json;
    }
    return {
        
        'redirect': json['redirect'],
    };
}

  export function SearchRedirectSchemaDataToJSON(json: any): SearchRedirectSchemaData {
      return SearchRedirectSchemaDataToJSONTyped(json, false);
  }

  export function SearchRedirectSchemaDataToJSONTyped(value?: SearchRedirectSchemaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect': value['redirect'],
    };
}

