/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { SearchRedirectSchemaData } from './SearchRedirectSchemaData';
import {
    SearchRedirectSchemaDataFromJSON,
    SearchRedirectSchemaDataFromJSONTyped,
    SearchRedirectSchemaDataToJSON,
    SearchRedirectSchemaDataToJSONTyped,
} from './SearchRedirectSchemaData';

/**
 * 
 * @export
 * @interface SearchRedirectSchema
 */
export interface SearchRedirectSchema {
    /**
     * 
     * @type {Context}
     * @memberof SearchRedirectSchema
     */
    context: Context;
    /**
     * 
     * @type {SearchRedirectSchemaData}
     * @memberof SearchRedirectSchema
     */
    data: SearchRedirectSchemaData;
}

/**
 * Check if a given object implements the SearchRedirectSchema interface.
 */
export function instanceOfSearchRedirectSchema(value: object): value is SearchRedirectSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SearchRedirectSchemaFromJSON(json: any): SearchRedirectSchema {
    return SearchRedirectSchemaFromJSONTyped(json, false);
}

export function SearchRedirectSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRedirectSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': SearchRedirectSchemaDataFromJSON(json['data']),
    };
}

  export function SearchRedirectSchemaToJSON(json: any): SearchRedirectSchema {
      return SearchRedirectSchemaToJSONTyped(json, false);
  }

  export function SearchRedirectSchemaToJSONTyped(value?: SearchRedirectSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': SearchRedirectSchemaDataToJSON(value['data']),
    };
}

