/* tslint:disable */
/* eslint-disable */
/**
 * beacon.searchspring.io
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Context } from './Context';
import {
    ContextFromJSON,
    ContextFromJSONTyped,
    ContextToJSON,
    ContextToJSONTyped,
} from './Context';
import type { Log } from './Log';
import {
    LogFromJSON,
    LogFromJSONTyped,
    LogToJSON,
    LogToJSONTyped,
} from './Log';

/**
 * 
 * @export
 * @interface ShopifyPixelExtensionLogEvent
 */
export interface ShopifyPixelExtensionLogEvent {
    /**
     * 
     * @type {Context}
     * @memberof ShopifyPixelExtensionLogEvent
     */
    context: Context;
    /**
     * 
     * @type {Log}
     * @memberof ShopifyPixelExtensionLogEvent
     */
    data: Log;
}

/**
 * Check if a given object implements the ShopifyPixelExtensionLogEvent interface.
 */
export function instanceOfShopifyPixelExtensionLogEvent(value: object): value is ShopifyPixelExtensionLogEvent {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ShopifyPixelExtensionLogEventFromJSON(json: any): ShopifyPixelExtensionLogEvent {
    return ShopifyPixelExtensionLogEventFromJSONTyped(json, false);
}

export function ShopifyPixelExtensionLogEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopifyPixelExtensionLogEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ContextFromJSON(json['context']),
        'data': LogFromJSON(json['data']),
    };
}

  export function ShopifyPixelExtensionLogEventToJSON(json: any): ShopifyPixelExtensionLogEvent {
      return ShopifyPixelExtensionLogEventToJSONTyped(json, false);
  }

  export function ShopifyPixelExtensionLogEventToJSONTyped(value?: ShopifyPixelExtensionLogEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ContextToJSON(value['context']),
        'data': LogToJSON(value['data']),
    };
}

