/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShopperContext } from './ShopperContext';
import {
    ShopperContextFromJSON,
    ShopperContextFromJSONTyped,
    ShopperContextToJSON,
    ShopperContextToJSONTyped,
} from './ShopperContext';

/**
 * 
 * @export
 * @interface ShopperLoginSchema
 */
export interface ShopperLoginSchema {
    /**
     * 
     * @type {ShopperContext}
     * @memberof ShopperLoginSchema
     */
    context: ShopperContext;
}

/**
 * Check if a given object implements the ShopperLoginSchema interface.
 */
export function instanceOfShopperLoginSchema(value: object): value is ShopperLoginSchema {
    if (!('context' in value) || value['context'] === undefined) return false;
    return true;
}

export function ShopperLoginSchemaFromJSON(json: any): ShopperLoginSchema {
    return ShopperLoginSchemaFromJSONTyped(json, false);
}

export function ShopperLoginSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopperLoginSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'context': ShopperContextFromJSON(json['context']),
    };
}

export function ShopperLoginSchemaToJSON(json: any): ShopperLoginSchema {
    return ShopperLoginSchemaToJSONTyped(json, false);
}

export function ShopperLoginSchemaToJSONTyped(value?: ShopperLoginSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': ShopperContextToJSON(value['context']),
    };
}

