/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributionInner } from './AttributionInner';
import {
    AttributionInnerFromJSON,
    AttributionInnerFromJSONTyped,
    AttributionInnerToJSON,
    AttributionInnerToJSONTyped,
} from './AttributionInner';
import type { Currency } from './Currency';
import {
    CurrencyFromJSON,
    CurrencyFromJSONTyped,
    CurrencyToJSON,
    CurrencyToJSONTyped,
} from './Currency';

/**
 * Contextual data about the shopper event
 * @export
 * @interface ShopperContext
 */
export interface ShopperContext {
    /**
     * Shoppers IP address. Accepts IPv4 and IPv6 formats. Recommended this is passed for accuracy. If not, will attempt to default to the "x-forwarded-for" or the Remote Address.
     * @type {string}
     * @memberof ShopperContext
     */
    iP?: string;
    /**
     * Shoppers UserAgent. Recommended this is passed for accuracy. If not, will attempt to default to "user-agent" request header.
     * @type {string}
     * @memberof ShopperContext
     */
    userAgent?: string;
    /**
     * RFC3339 formatted timestamp represents time of event
     * @type {string}
     * @memberof ShopperContext
     */
    timestamp: string;
    /**
     * Current page `window.location.href` value
     * @type {string}
     * @memberof ShopperContext
     */
    pageUrl: string;
    /**
     * Unique identifier for the customer (usually a UUID)
     * @type {string}
     * @memberof ShopperContext
     */
    userId: string;
    /**
     * Unique identifier for the customer's current session - should expire after store visit (usually a UUID)
     * @type {string}
     * @memberof ShopperContext
     */
    sessionId: string;
    /**
     * Unique identifier that represents a unique page load. Used to tie multiple events made on a single page together.
     * @type {string}
     * @memberof ShopperContext
     */
    pageLoadId: string;
    /**
     * Unique identifier for the customer's product personalization - it is typically a user id or email and should be sent if the user is authenticated on the storefront. If the shopper has already logged in this is required.
     * @type {string}
     * @memberof ShopperContext
     */
    shopperId: string;
    /**
     * Application identifier that initiated the event
     * @type {string}
     * @memberof ShopperContext
     */
    initiator: string;
    /**
     * Provides attribution details on product landing pages - it is currently only used for email recommendations
     * @type {Array<AttributionInner>}
     * @memberof ShopperContext
     */
    attribution?: Array<AttributionInner>;
    /**
     * 
     * @type {Currency}
     * @memberof ShopperContext
     */
    currency?: Currency;
    /**
     * Developer mode flag. If set to `true`, the event data will not populate in reporting
     * @type {boolean}
     * @memberof ShopperContext
     */
    dev?: boolean;
}

/**
 * Check if a given object implements the ShopperContext interface.
 */
export function instanceOfShopperContext(value: object): value is ShopperContext {
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('pageUrl' in value) || value['pageUrl'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('pageLoadId' in value) || value['pageLoadId'] === undefined) return false;
    if (!('shopperId' in value) || value['shopperId'] === undefined) return false;
    if (!('initiator' in value) || value['initiator'] === undefined) return false;
    return true;
}

export function ShopperContextFromJSON(json: any): ShopperContext {
    return ShopperContextFromJSONTyped(json, false);
}

export function ShopperContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShopperContext {
    if (json == null) {
        return json;
    }
    return {
        
        'iP': json['IP'] == null ? undefined : json['IP'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'timestamp': json['timestamp'],
        'pageUrl': json['pageUrl'],
        'userId': json['userId'],
        'sessionId': json['sessionId'],
        'pageLoadId': json['pageLoadId'],
        'shopperId': json['shopperId'],
        'initiator': json['initiator'],
        'attribution': json['attribution'] == null ? undefined : ((json['attribution'] as Array<any>).map(AttributionInnerFromJSON)),
        'currency': json['currency'] == null ? undefined : CurrencyFromJSON(json['currency']),
        'dev': json['dev'] == null ? undefined : json['dev'],
    };
}

export function ShopperContextToJSON(json: any): ShopperContext {
    return ShopperContextToJSONTyped(json, false);
}

export function ShopperContextToJSONTyped(value?: ShopperContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'IP': value['iP'],
        'userAgent': value['userAgent'],
        'timestamp': value['timestamp'],
        'pageUrl': value['pageUrl'],
        'userId': value['userId'],
        'sessionId': value['sessionId'],
        'pageLoadId': value['pageLoadId'],
        'shopperId': value['shopperId'],
        'initiator': value['initiator'],
        'attribution': value['attribution'] == null ? undefined : ((value['attribution'] as Array<any>).map(AttributionInnerToJSON)),
        'currency': CurrencyToJSON(value['currency']),
        'dev': value['dev'],
    };
}

