/* tslint:disable */
/* eslint-disable */
/**
 * analytics.searchspring.net
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.2.48
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorWithDataField
 */
export interface ValidationErrorWithDataField {
    /**
     * Data sent but not received due to an error
     * @type {boolean}
     * @memberof ValidationErrorWithDataField
     */
    success?: boolean;
    /**
     * Cause of error
     * @type {string}
     * @memberof ValidationErrorWithDataField
     */
    error?: string;
    /**
     * Cause of failure(s)
     * @type {Array<string>}
     * @memberof ValidationErrorWithDataField
     */
    messages?: Array<string>;
    /**
     * Data sent where an error is identified
     * @type {string}
     * @memberof ValidationErrorWithDataField
     */
    data?: string;
}

/**
 * Check if a given object implements the ValidationErrorWithDataField interface.
 */
export function instanceOfValidationErrorWithDataField(value: object): value is ValidationErrorWithDataField {
    return true;
}

export function ValidationErrorWithDataFieldFromJSON(json: any): ValidationErrorWithDataField {
    return ValidationErrorWithDataFieldFromJSONTyped(json, false);
}

export function ValidationErrorWithDataFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorWithDataField {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
        'messages': json['messages'] == null ? undefined : json['messages'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function ValidationErrorWithDataFieldToJSON(json: any): ValidationErrorWithDataField {
    return ValidationErrorWithDataFieldToJSONTyped(json, false);
}

export function ValidationErrorWithDataFieldToJSONTyped(value?: ValidationErrorWithDataField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
        'messages': value['messages'],
        'data': value['data'],
    };
}

